### ISSUE TITLE
Certificates error

### ISSUE THREAD

**Issue by MHBdev2** [chiteroman/PlayIntegrityFix#1]
Hey
I install your module and run zygisk on android 13 but because I connect to a private network I place private security certificates in system/etc/security/cacerts,
And without the module everything works fine, but after installing the module the system does not trust the certificates at all,
Could it be because of the difference with the keystore?

**Comment by chiteroman** [comment]
It doesn't make sense because module only touch GMS unstable process... Do you have this problem with Displax module?

**Comment by MHBdev2** [comment]
I tried both the original version and the Displax mod and it didn't work in both (the device doesn't trust the certificates), and I assumed it was because of the change in the device's key pool
But it doesn't work in your mod either...
(By the way, it works fine on Android 11...)

**Comment by chiteroman** [comment]
Your best option is to patch manually the super.img and boot.img to pass Play Integrity API without Magisk.
