### ISSUE TITLE
Riru Version Please

### ISSUE THREAD

**Issue by VisionR1** [chiteroman/PlayIntegrityFix#1]
Hi, i want to try it this version in my Xiaomi Poco X3 NFC android 10 (12.0.8.0 EEA), it will be only zygisk? or will be and for riru and for future releases etc? because i have Magisk Delta with magiskhide and riru, because of this written by @HuskyDG

![246826407-2f5db7ab-a2c0-4c19-b1c3-abae1878c283](https://github.com/chiteroman/PlayIntegrityFix/assets/25982450/43187eef-0053-42e0-a49b-d7ee1a5becf6)

**Comment by chiteroman** [comment]
Riru is obsolete, even its developers said that all modules should be migrated to Zygisk. I'm sorry, but I'm not going to make a Riru version.

**Comment by VisionR1** [comment]
> Riru is obsolete, even its developers said that all modules should be migrated to Zygisk. I'm sorry, but I'm not going to make a Riru version.

Thanks for the information
