### ISSUE TITLE
Device Integrity Not Passing 

### ISSUE THREAD

**Issue by aintyourcupoftea** [chiteroman/PlayIntegrityFix#105]
![Screenshot_20231129-231405](https://github.com/chiteroman/PlayIntegrityFix/assets/79439692/3ce48e38-27a5-4183-8f05-c0b2f6ca6e9a)
![Screenshot_20231129-231916](https://github.com/chiteroman/PlayIntegrityFix/assets/79439692/899dfc0a-b45b-4670-a72a-9a36eebd6717)

Device integrity not passing even after installing the latest Update.
I am using Kernel SU with Zygisk Next.

**Comment by MoiZie** [comment]
Same problem with lineage 20 default kernel.

**Comment by rodgar-nvkz** [comment]
Same on magisk delta with only one module installed: only basic integrity passed, device integrity failed.

**Comment by mskonovalov** [comment]
Works for me for now, stopped working on previous version
