### ISSUE TITLE
Banking app detecting newer versions of play integrity fix

### ISSUE THREAD

**Issue by Sygmstr** [chiteroman/PlayIntegrityFix#106]
I was only able to get NLB pay working with the 13.8 beta version of the module. Have to also use Magisk delta version R655F6129 to get the banking app to work.
The app crashes on startup

**Comment by pannal** [comment]
Can't confirm on v13.9

**Comment by chiteroman** [comment]
Yep, v13.9 doesn't include custom resetprop. You can check v14.0 beta (download resetprop version)
