### ISSUE TITLE
FCM Push section removed from README?

### ISSUE THREAD

**Issue by pannal** [chiteroman/PlayIntegrityFix#108]
Hey,

[This was very helpful for me.](https://github.com/chiteroman/PlayIntegrityFix/blob/bf9ce4eb7312cf4f9e83de6b9571c799d84cfeeb/README.md#make-fcm-push-back-to-work-after-cleared-gsf-data)

Why was this removed from the README?

Thanks!

**Comment by osm0sis** [comment]
Because people shouldn't be clearing Google Service Framework.
