### ISSUE TITLE
Any work on a more permanent fix?

### ISSUE THREAD

**Issue by SapuSeven** [chiteroman/PlayIntegrityFix#109]
Hi,
first of all, thanks a lot for all the work you're doing on this module. I really appreciate it.
That being said, are there any plans to implement a more permanent fix? It's really tedious to be resetting Google Services and Wallet every few days/weeks because Google banned yet another fingerprint.
I know that I have no idea how this module works in the background so I don't know if it's even possible, but right now it feels like an arms race we're slowly loosing.

**Comment by chiteroman** [comment]
The only permanent solution is to install the stock ROM and lock bootloader.

**Comment by SapuSeven** [comment]
Sure, I get that. But I was thinking there must be another method that can't be patched by Google so easily. SafetyNet has been practically permanently defeated as well.

**Comment by furdiburd** [comment]
> Sure, I get that. But I was thinking there must be another method that can't be patched by Google so easily. SafetyNet has been practically permanently defeated as well.

Safetynet was defeated by forcing software based checks. Its not possible with play integrity only basic can be passed that way that why spoofing fingerpints is needed to pass device integrity.
