### ISSUE TITLE
Google play does not work 

### ISSUE THREAD

**Issue by russssl** [chiteroman/PlayIntegrityFix#111]
after using fix for a while Google Play started saying that the phone did not meet the security requirements even when safety net checkers show cts and basic pass

**Comment by Pick-Another-Username** [comment]
> after using fix for a while Google Play started saying that the phone did not meet the security requirements even when safety net checkers show cts and basic pass

1)You need to update the module to the latest version 
2)Wait ~24hours for it to take effect or clear cache and data of google play services for immediate effect

**Comment by zhilinli1** [comment]
> > after using fix for a while Google Play started saying that the phone did not meet the security requirements even when safety net checkers show cts and basic pass
> 
> 1)You need to update the module to the latest version 2)Wait ~24hours for it to take effect or clear cache and data of google play services for immediate effect

Also did the same thing, did not work
