### ISSUE TITLE
Device integrity fail on 14.0

### ISSUE THREAD

**Issue by Jon8RFC** [chiteroman/PlayIntegrityFix#113]
Pixel 8 Pro

Yikes. This may be the end.

**Comment by GladistonXD** [comment]
Here too, it stopped today.

**Comment by 1cmoody23** [comment]
Hi I have oneplus 8T and also now have this issue. Not a coder but willing to help test any fix you might come up with.

**Comment by GladistonXD** [comment]
Google banned the previous fingerprint, now you have to place it manually, if anyone finds a working one, share it.

**Comment by furdiburd** [comment]
> Google banned the previous fingerprint, now you have to place it manually, if anyone finds a working one, share it.

Dont share it with everyone. google just gonna ban that too. only share it in private and with ones that you can trust

**Comment by MarkusTieger** [comment]
"Trust"??? This is the internet. Technically you can trust no one. And i doubt that anyone that you know personally has there phone rooted.

**Comment by furdiburd** [comment]
> > > Google banned the previous fingerprint, now you have to place it manually, if anyone finds a working one, share it.
> > 
> > 
> > Dont share it with everyone. google just gonna ban that too. only share it in private and with ones that you can trust
> 
> "Trust"??? This is the internet. Technically you can trust no one. And i doubt that anyone that you know personally has there phone rooted.

Thats what i meant! Just dont share it on the internet with random ppl.

**Comment by MarkusTieger** [comment]
And because i am currently in the search of a fingerprint that works:

if anyone wants to put their trust in me anyway, my ssh public key: (for encryption)
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCcJCdJ7pXW2BRWmN0YIDU5mlaXZlyQY6v1l4+rhZ8CqOljXJGQTAXRrU8eB6wsqGDgfqoIew0POaj+x6Ucg/h8jRx0Pu8zEl0VBlhbhSNb1hZHCLPEPYArPPsWxv/E1S14GiWG+07IcpX6v6EU5sTPs1khByCHzCovkaIhIeWvPBP1y8Zl1NzXwt8db/vHwWJez0qRF//7PlCKfNzjaxJRDXOqwxOZKTi48mmWAlwIjBYoSx0Qr0ydvleTRxHux1bpq4KMLprvnBIhgMYYC9DFu/cHOK/37gzYS17rt2gFlBfbaRsk2NsuLS4kebddKTgf0BypmdT3XTDwhMuNk1RzCSXjOefF/g2kAldWYuMdWiwBrMxG3JQi+LfV17QHkcUL6OOLd49AUCeJw3/Qis5bWW8U9dMlfr8IJUU9XerJMJhJ/CDltM7DO7kVyrMx87K6tc7gK0zZil2nDVuvJIFhJ1to38xaUSpJ3YMdVA/AjwMN2sa1Z8IBhhjkw4r/Pz6xnV4VWALhF+10wUjB5n37TMw4vMQemDoE4yerE7/vPF5RyZnVvGLjtPmPrwc9wKulac9xMdpScT37hsXv7GxPfaIblyPu0VUqNJKVIGON10fxfYUSFn6iE6bKF3UmGBlFs2Evm/UK5boKWWpupuw5czTAZXiUW+hIYyEsSS8Yww== markustieger@ms7c56
```

**Comment by rez23** [comment]
This kind of crusade that Google has undertaken against any type of modding of its OS not carried out by OEMs is really frustrating and annoying.

Maybe, instead, they could spend more time finding solutions that permit more freedom to their users while continuing to guarantee a certain level of security.

**Comment by MarkusTieger** [comment]
> This kind of crusade that Google has undertaken against any type of modding of its OS not carried out by OEMs is really frustrating and annoying.
> 
> Maybe, instead, they could spend more time finding solutions that permit more freedom to their users while continuing to guarantee a certain level of security.

The usage of passwords with more than 16 characters would be a great start
