### ISSUE TITLE
pif.json doc and examples 

### ISSUE THREAD

**Issue by mgrybyk** [chiteroman/PlayIntegrityFix#114]
Hello,

Can somebody please provide with some examples of values in the pif json?

- Do I need to set all values in that file?
- how does values there map to the build.prop?
- how can I apply changes (just reboot)?

The content of pif.json looks like this
```
{
  "PRODUCT": "",
  "DEVICE": "",
  "MANUFACTURER": "",
  "BRAND": "",
  "MODEL": "",
  "FINGERPRINT": "",
  "SECURITY_PATCH": "",
  "FIRST_API_LEVEL": ""
}
```
The use case. I want to set values from:
```
ro.build.date.utc=1696861647
ro.build.date=Mon Oct 9 14:27:27 UTC 2023
ro.build.fingerprint=<I was asked to delete this>
ro.build.flavor=missi_phone_cn-user
ro.build.host=xiaomi.eu
ro.build.keys=release-keys
ro.build.version.incremental=V14.0.15.0.TLBCNXM
ro.build.version.security_patch=2023-10-01
ro.system.build.date.utc=1696861647
ro.system.build.date=Mon Oct 9 14:27:27 UTC 2023
ro.system.build.fingerprint=<I was asked to delete this>
ro.system.build.version.incremental=V14.0.15.0.TLBCNXM
```
How would I do that?

Thank you so much in advance!

**Comment by mgrybyk** [comment]
@HardcodedCat do you probably know the prop name of the "First api level"?
Thanks

**Comment by mgrybyk** [comment]
@HardcodedCat I fetched it with getprop, thank you.

`getprop ro.product.first_api_level`
> 31

**Comment by mgrybyk** [comment]
I guess the manufacturer and model are these:

- ro.product.system.manufacturer=QUALCOMM
- ro.product.system.model=missi system image for arm64

Quite a weird model name

**Comment by mgrybyk** [comment]
@HardcodedCat do you know how can I apply the changes? Modify the file and reboot the device or some extra steps ate required?

**Comment by TechySkills** [comment]
"BUILD_ID": "",
  "VNDK_VERSION": ""

How to get these two new values please?

**Comment by milux** [comment]
> "BUILD_ID": "", "VNDK_VERSION": ""
> 
> How to get these two new values please?

The former, according to the source code of this repo, should be what you find in `ro.build.id`.
The latter doesn't seem to exist on my device, will try empty string and see if it works.
