### ISSUE TITLE
device integrity and cts profile match? failing

### ISSUE THREAD

**Issue by Dialgatrainer02** [chiteroman/PlayIntegrityFix#121]
i have 2  newer pixel devices p6p and p7 and im trying to use nothing fingerprints my p6p is using and older fingerprint and is failing cts profile check and using hardware backed however my p7 is using a much more up to date fingerprint and is also failing cts profile but using basic.
im not sure why ctsprofile is failing as the fingerprints are still used by actual phones.
also can we send module logcats like the one specified in the readme or does that risk the fingerprint used being banned?
is it just an issue with the fingerprints should i just look elsewhere

**Comment by Fede2782** [comment]
Nothing is working. We can't do anything now. I tried almost 50 fingerprints of new and old devices and none of them worked. I'm giving up to this. I'll buy a new device since I can't use my rooted one anymore because of this or I'll return on stock.

**Comment by Homi74** [comment]
> Nothing is working. We can't do anything now. I tried almost 50 fingerprints of new and old devices and none of them worked. I'm giving up to this. I'll buy a new device since I can't use my rooted one anymore because of this or I'll return on stock.

I've tested about 30 of them and they all work

**Comment by Fede2782** [comment]
> > Nothing is working. We can't do anything now. I tried almost 50 fingerprints of new and old devices and none of them worked. I'm giving up to this. I'll buy a new device since I can't use my rooted one anymore because of this or I'll return on stock.
> 
> I've tested about 30 of them and they all work

Could you please tell me which brands are the devices you tried? And which Android version?

**Comment by Taym-X** [comment]
> Nothing is working. We can't do anything now. I tried almost 50 fingerprints of new and old devices and none of them worked. I'm giving up to this. I'll buy a new device since I can't use my rooted one anymore because of this or I'll return on stock.

I too have tried many fingerprints and none of them worked
