### ISSUE TITLE
Google pay detecting root 

### ISSUE THREAD

**Issue by ZerkerEOD** [chiteroman/PlayIntegrityFix#122]
As the title says, Google pay is detecting root send as fast as you patch it they detect it. It was working for the longest time then it started detecting it so I updated to the latest version and it started working again for about a day. Since then though nothing, keeps detecting root

**Comment by techjaw** [comment]
I have exactly the same thing, Android 13.1 Oxygen

**Comment by Mario6425** [comment]
Play integrity fix 14.2 is running like a boss. 💪

Basic & device integrity both passed. And google pay also works. No more done than safteynet fix Mod 2.4.0 zygisk 2.0 thrown out. Play integrity 14.2 flashed in recovery. Did not delete play services or anything. Clean performance bro
