### ISSUE TITLE
SafetyNet issue with MIUI-China based custom ROM 

### ISSUE THREAD

**Issue by wadkarkundan** [chiteroman/PlayIntegrityFix#127]
Hello ,
I have managed to build a custom-made pif.json file that passes 2 checks up to "MEETS DEVICE INTEGRITY" using the following method:
**KernelSU + ZysgiskNext + Playintegrity 14.0 + (pif.json file moved to data/adb).**

However, this same file works on AOSP custom ROM but it doesn't work on **MIUI China-based custom ROM** DEVICE POCO F1. When I check the safety net status, it passes then fails then again passes and continues like that. When checked in Playstore Check Integrity shows [ ] not a single pass. The same method used in AOSP Evox Rom passes straight away, and the device is also certified.

Could you please help me understand why this is happening? Is there any workaround or fix available for this issue? I know there's already a MIUI EU fix but I'm interested in China build. What I want is to understand why it's not working in MIUI rom 

Thank you.

**Comment by williamgateszhao** [comment]
See #129
