### ISSUE TITLE
no effect

### ISSUE THREAD

**Issue by jaypur15** [chiteroman/PlayIntegrityFix#128]
your mod has no effect. it's useless.

**Comment by YurKa336** [comment]
> your mod has no effect. it's useless.
Are you sure you did everything right?  Everything works
![Screenshot_2023-12-04-12-10-30-765_com henrikherzig playintegritychecker](https://github.com/chiteroman/PlayIntegrityFix/assets/107347313/d7eefef6-3919-422b-adcd-0c057e8554da)
![Screenshot_2023-12-04-12-10-39-927_com henrikherzig playintegritychecker](https://github.com/chiteroman/PlayIntegrityFix/assets/107347313/8ff86910-b7b1-4c81-becb-f1f6783c1bb9)

**Comment by mateusdnc** [comment]
> your mod has no effect. it's useless.

As @YurKa336 showed, version 14.1 works as proposed. Learn to read the documentation and installation steps
