### ISSUE TITLE
Xiaomi EU race condition

### ISSUE THREAD

**Issue by re7gog** [chiteroman/PlayIntegrityFix#134]
There is a race condition with the module included in the EU firmware, so the module works sometimes, but most of the time it doesn't
https://xiaomi.eu/community/threads/safetynet-pass-disabling.68703/

**Comment by nyakze** [comment]
This is a thread from April. What does it have to do with the current state of things?

**Comment by re7gog** [comment]
Now i have this module with custom PIF and sometimes it gives DEVICE integrity, but most of time - NO integrity, result is random, and the same problem with safety net - basic or no attestation.
There is a workaround in the Displax's fork: https://github.com/Displax/safetynet-fix/commit/79920e9eab14ba6aed22c0f242efb7f37ef3064e
It just simply not changing fields because EU rom already does it, but it will not help there because we need custom PIF that is not in EU
I think we should block changing fields by EU somehow

**Comment by re7gog** [comment]
Sorry, I have found that EU is now has it's own fix method

**Comment by realazizk** [comment]
@re7gog hey, what's the fix, I have this issue

**Comment by nyakze** [comment]
> @re7gog hey, what's the fix, I have this issue

https://xiaomi.eu/community/threads/xiaomieu-module-app.70890/
