### ISSUE TITLE
dev-v1 issue

### ISSUE THREAD

**Issue by Artiom97es** [chiteroman/PlayIntegrityFix#139]
dev-v1 deleted magisk for no reason, any kind of issue there
(no problem after unistall fix 14.2)
(but dissapear on Dev Ver)

**Comment by Artiom97es** [comment]
thanks :)

**Comment by pmsobrado** [comment]
@chiteroman Does v2 fix this? I have a custom pif and I'm using 14.0 without issues, could I updat to this v2 dev?

**Comment by Artiom97es** [comment]
fixed
