### ISSUE TITLE
Google play services crashing on A13

### ISSUE THREAD

**Issue by PapineauD** [chiteroman/PlayIntegrityFix#14]
Process: com.google.android.gms.unstable
PID: 22219
UID: 10107
Frozen: false
Flags: 0xa0cabec5
Package: com.google.android.gms v234313039 (23.43.13 (190408-577232161))
PID: 22219
Foreground: No
Process-Runtime: 1945166
Build: realme/RMX3311EEA/RE58B2L1:13/TP1A.220905.001/S.1383667_1_12f:user/release-keys
Loading-Progress: 1.0
Dropped-Count: 0

Process name is com.google.android.gms.unstable, not key_process
keyProcess: 0
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'realme/RMX3311EEA/RE58B2L1:13/TP1A.220905.001/S.1383667_1_12f:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-11-09 00:32:32.123713909+0200
Process uptime: 1946s
Cmdline: com.google.android.gms.unstable
pid: 22219, tid: 22237, name: binder:22219_1  >>> com.google.android.gms.unstable <<<
uid: 10107
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
Cause: null pointer dereference
    x0  0000007ad8c6f2b8  x1  0000007ad8c6f1f0  x2  0000007ad8c6f1f0  x3  0000000001000000
    x4  0000007b935142c0  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  57095261bb896e1a  x10 0000000000000042  x11 fffffffffffffffd
    x12 0000007ad8c6da20  x13 0000000000000036  x14 0000007ad8c6ed68  x15 0000000034155555
    x16 0000007b8278e9c8  x17 0000007b82711d90  x18 0000007a76f1c000  x19 0000007ad8c6f2b8
    x20 0000007ad8c6f2b8  x21 0000007b9698353c  x22 0000007b969834dc  x23 0000007b82794098
    x24 0000000001000000  x25 0000007ad8c70000  x26 0000007b969834e0  x27 0000000070f0eae0
    x28 0000000000000000  x29 0000007ad8c6f1d0
    lr  0000007b82714e90  sp  0000007ad8c6f1d0  pc  0000007b935142e4  pst 0000000060001000
backtrace:
      #00 pc 00000000000c02e4  /system/lib64/libandroid_runtime.so (void android::(anonymous namespace)::ReadProperty<android::(anonymous namespace)::SystemProperties_getSS(_JNIEnv*, _jclass*, _jstring*, _jstring*)::$_0>(prop_info const*, android::(anonymous namespace)::SystemProperties_getSS(_JNIEnv*, _jclass*, _jstring*, _jstring*)::$_0&&)::'lambda'(void*, char const*, char const*, unsigned int)::__invoke(void*, char const*, char const*, unsigned int)+36) (BuildId: 9e59e66cb05b88d47dd2e4e2bf3fb3eb)
      #01 pc 000000000007ce8c  /apex/com.android.runtime/lib64/bionic/libc.so (SystemProperties::ReadCallback(prop_info const*, void (*)(void*, char const*, char const*, unsigned int), void*)+260) (BuildId: e9653d1f6c173c6b86b171a5be6af6eb)
      #02 pc 00000000000bff48  /system/lib64/libandroid_runtime.so (long android::(anonymous namespace)::SystemProperties_get_integralH<long>(long, long)+52) (BuildId: 9e59e66cb05b88d47dd2e4e2bf3fb3eb)
      #03 pc 0000000000e8e1e4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.OneTraceExtImpl.isOneTraceEnable+100)
      #04 pc 0000000000e8e888  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.OneTraceExtImpl.isEnable+40)
      #05 pc 0000000000bc565c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Binder.execTransactInternal+396)
      #06 pc 0000000000bc5410  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Binder.execTransact+288)
      #07 pc 0000000000333fa4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
      #08 pc 0000000000332020  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+772) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
      #09 pc 0000000000561490  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+192) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
      #10 pc 00000000000c4714  /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+124) (BuildId: 9e59e66cb05b88d47dd2e4e2bf3fb3eb)
      #11 pc 0000000000179020  /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+160) (BuildId: 9e59e66cb05b88d47dd2e4e2bf3fb3eb)
      #12 pc 0000000000054a1c  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+240) (BuildId: f8bf2eec502e0e2b2f0020036c32cdd5)
      #13 pc 000000000005fbd8  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1036) (BuildId: f8bf2eec502e0e2b2f0020036c32cdd5)
      #14 pc 000000000005f700  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+164) (BuildId: f8bf2eec502e0e2b2f0020036c32cdd5)
      #15 pc 000000000005ffc4  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+72) (BuildId: f8bf2eec502e0e2b2f0020036c32cdd5)
      #16 pc 000000000009007c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+28) (BuildId: f8bf2eec502e0e2b2f0020036c32cdd5)
      #17 pc 0000000000013414  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+424) (BuildId: a14105df1ece31a331c10a1341ca9da3)
      #18 pc 00000000000cd5a0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+144) (BuildId: 9e59e66cb05b88d47dd2e4e2bf3fb3eb)
      #19 pc 00000000000e5a08  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: e9653d1f6c173c6b86b171a5be6af6eb)
      #20 pc 000000000007f27c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: e9653d1f6c173c6b86b171a5be6af6eb)

**Comment by chiteroman** [comment]
Check pre-release: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v12.1
