### ISSUE TITLE
Custom props question 

### ISSUE THREAD

**Issue by Osanosa** [chiteroman/PlayIntegrityFix#153]
Hemlo can I just take props from my stock firmware and use it? Will it be banned? Can you provide a bit more information about it?

**Comment by Masamune3210** [comment]
Has to be from a device old enough to not have forced hardware backed attestation

**Comment by Masamune3210** [comment]
Anything from 2019-2020 is a maybe, anything before should be software-only. Anything after is hardware backed.

**Comment by Osanosa** [comment]
Hemlo again my friend said that if I'd take a fingerprint from anything except A6 it won't work. Can you please clarify what are requirements or just link a tutorial if such exists. Hhx.

**Comment by Osanosa** [comment]
nevermind, i think I've found one
