### ISSUE TITLE
Gapps crashing

### ISSUE THREAD

**Issue by bopv2** [chiteroman/PlayIntegrityFix#160]
YouTube, Drive & GMail crash whenever I open them. I don't really know why, but I do know that it has to do with the module cause whenever I disable it those apps work just fine.
I'm running Magisk 26.4 & PlayIntegrityFix v14.2 and also both DEVICE and BASIC integrity checks pass.

**Comment by chiteroman** [comment]
Check latest version.

**Comment by Jon8RFC** [comment]
All good here on pixel 8 pro with magisk 26.4 and play integrity 14.3.

What if you disable all of your OTHER modules and root tinkering stuff like lsposed modules, and only have play integrity enabled, and then reboot and try again?

Maybe there's some funky conflict with another module and that could help troubleshoot the issue.

**Comment by AndnixSH** [comment]
It would be nice if you could provide logs. Use LogcatReader app to record then replicate the crashes
https://github.com/darshanparajuli/LogcatReader

**Comment by HeftigerHans139** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/sweet_global/sweet:11/RKQ1.200826.002/V12.0.6.0.RKFMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-12-13 11:38:11.828938895+0100
Process uptime: 1s
Cmdline: zygote64
pid: 21631, tid: 21631, name: id.gms.unstable  >>> zygote64 <<<
uid: 99910169
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'No pending exception expected: java.lang.IllegalStateException: Expected a string but was NULL
  at java.lang.String android.util.JsonReader.nextString() (JsonReader.java:410)
  at void es.chiteroman.playintegrityfix.EntryPoint.init(java.lang.String) (SourceFile:-1)
  at int com.android.internal.os.Zygote.nativeForkAndSpecialize(int, int, int[], int, int[][], int, java.lang.String, java.lang.String, int[], int[], boolean, java.lang.String, java.lang.String, boolean, java.lang.String[], java.lang.String[], boolean, boolean) (Zygote.java:-2)
  at int com.android.internal.os.Zygote.forkAndSpecialize(int, int, int[], int, int[][], int, java.lang.String, java.lang.String, int[], int[], boolean, java.lang.String, java.lang.String, boolean, java.lang.String[], java.lang.String[], boolean, boolean) (Zygote.java:354)
  at java.lang.Runnable com.android.internal.os.ZygoteConnection.processCommand(com.android.internal.os.ZygoteServer, boolean) (ZygoteConnection.java:253)
  at java.lang.Runnable com.android.internal.os.ZygoteServer.runSelectLoop(java.lang.String) (ZygoteServer.java:558)
  at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:941)'
    x0  0000000000000000  x1  000000000000547f  x2  0000000000000006  x3  0000007ff53da140
    x4  000000741ec0b000  x5  000000741ec0b000  x6  000000741ec0b000  x7  000000000000db92
    x8  00000000000000f0  x9  00000073f3ea6cb0  x10 0000000000000001  x11 00000073f3f1b7c8
    x12 000000736f201430  x13 000000000628da18  x14 000000000628d8d8  x15 0000ef2e43e922cb
    x16 00000073f3f86a80  x17 00000073f3f5f450  x18 000000741df1e000  x19 000000000000547f
    x20 000000000000547f  x21 00000000ffffffff  x22 0000000000000009  x23 000000736a4a9838
    x24 0000000000000009  x25 000000736b013000  x26 b40000736f248280  x27 000000736b016000
    x28 000000736b016000  x29 0000007ff53da1c0
    lr  00000073f3f0c748  sp  0000007ff53da120  pc  00000073f3f0c774  pst 0000000000000000
backtrace:
      #00 pc 000000000008d774  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 449f781894033dce6346794a1ee593e0)
      #01 pc 00000000007716f0  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+904) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
      #02 pc 00000000000357d0  /apex/com.google.mainline.primary.libs@341050000/lib64/libbase.so/75d3253827fcfd7a8d7b02ad45991611ec4ca424c0278e13e8acfad4d14e597a3ecff6c0caa2b785c73838528ee6e9c2b313240ff895f50ee39b1d7bc10f390a/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
      #03 pc 0000000000034d58  /apex/com.google.mainline.primary.libs@341050000/lib64/libbase.so/75d3253827fcfd7a8d7b02ad45991611ec4ca424c0278e13e8acfad4d14e597a3ecff6c0caa2b785c73838528ee6e9c2b313240ff895f50ee39b1d7bc10f390a/libbase.so (android::base::LogMessage::~LogMessage()+352) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
      #04 pc 000000000025c8bc  /apex/com.android.art/lib64/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+10444) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
      #05 pc 000000000055878c  /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*)+696) (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
      #06 pc 000000000002cc04  /system/bin/app_process64 (BuildId: 0392f54b3dffeef9b6cad14b6f0bdd45)

Can you do something there?

**Comment by chiteroman** [comment]
Json file is bad formatted.
