### ISSUE TITLE
After the latest update 14.3 Google pay doesn't work

### ISSUE THREAD

**Issue by freebumba27** [chiteroman/PlayIntegrityFix#163]
I did clear data wallet, play service, store, service framework. Also added all of them in deny list. Pay keep saying your phone doesn't meet sequrity requirement. Using Xiaomi 11 ultra | EU rom 13.0.9 | Android 12 | Magisk 26.4 | PIF 14.3 (no other integrity mod installed). Any idea?

**Comment by mrkylegp** [comment]
Same here. It was working just before this update. Time to roll back I guess.

**Comment by giodlangel** [comment]
Same here. Using Motorola One Action (TROIKA) | LineageOS 20 | Android 13 | Magisk 26.4 | PIF 14.3

**Comment by bulletproof04** [comment]
Same with pixel 7 pro A14 november

**Comment by AndnixSH** [comment]
Are you guys passing device integrity? You can check using TB Checker app from Play Store. Mine still pass, and no alerts from GPay checker, but I haven't try to pay with Wallet again yet

**Comment by li-yifei** [comment]
Pixel 8 pro with qpr2 beta2 failed too.
![Screenshot_20231212-174458.png](https://github.com/chiteroman/PlayIntegrityFix/assets/45546645/3b242c1c-5bff-4e7f-88f1-a211f8643cc9)


Had to flash v14.0 back for spoofing BASIC evaluation type.

**Comment by li-yifei** [comment]
> > Pixel 8 pro with qpr2 beta2 failed too.
> 
> YASNAC is outdated. You should use TB Checker
> 
> > Yes only strong and virtual are failing , basic and device are passing
> 
> That's interesting. Maybe try to disable all other modules except PIF? Additionally, try GPay Checker app https://xdaforums.com/t/gpay-checker-monitor-of-google-pay-availability.4643969/. I'm very curious if it works
> You can only get Strong with locked bootloader and Virtual is for emulator only (e.g Google Play Games for PC)
> 
The checker inside Google play itself is enough for me imo.

I can get up to MEETS_DEVICE_INTEGRITY on 14.0 but only MEETS_BASIC_INTEGRITY on 14.3

![Screenshot_20231212-184318.png](https://github.com/chiteroman/PlayIntegrityFix/assets/45546645/ab905e93-4036-44d6-9d2f-c3a1f3e23e79)

**Comment by TheTou** [comment]
had the same issue, got it working again after I removed Google Wallet from the magisk blocklist

**Comment by bulletproof04** [comment]
I used a pixel 3a fingerprint on my pixel 7 pro and clear all data and cache for the google play and wallet and now google wallet is working and i am using v14.3

**Comment by halilovic2002** [comment]
> I used a pixel 3a fingerprint on my pixel 7 pro and clear all data and cache for the google play and wallet and now google wallet is working and i am using v14.3

how do I do that?

**Comment by bulletproof04** [comment]
> > I used a pixel 3a fingerprint on my pixel 7 pro and clear all data and cache for the google play and wallet and now google wallet is working and i am using v14.3
> 
> how do I do that?

I used this tutorial and selected the pixel 3a instead https://www.youtube.com/watch?v=AEi1anhLqJM

**Comment by Mirubzi** [comment]
> had the same issue, got it working again after I removed Google Wallet from the magisk blocklist

Thank you, you're really helped me

**Comment by AndnixSH** [comment]
Today, I paid using Wallet with PIF 14.3. It still works
