### ISSUE TITLE
Broken functionality when using zygisk-detach

### ISSUE THREAD

**Issue by bruhmoment21** [chiteroman/PlayIntegrityFix#166]
I've noticed that on my S9 that I use occasionally the Integrity thing is not working at all unless [zygisk-detach](https://github.com/j-hc/zygisk-detach/releases/tag/v1.8) is disabled. My S9 is running the latest stock rom (Android 10) with Magisk patched. Doesn't occur on my main phone (Stock rom magisk patched, android 13) that also has zygisk-detach enabled.
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/53657322/fae1a527-452c-49eb-8fb0-530934df013a)

**Comment by chiteroman** [comment]
Using it and it's working fine...

**Comment by bruhmoment21** [comment]
Sadly, issue persists on my S9.
