### ISSUE TITLE
loop for ever in yasnac, in tb checker when activate zyg + playsfix = basic and other not pass anymore, playstore very slow.

### ISSUE THREAD

**Issue by gss200610** [chiteroman/PlayIntegrityFix#169]
loop for ever in yasnac, in tb checker when activate zyg + playsfix = basic and other not pass anymore, playstore very slow.

**Comment by LenaTDDS** [comment]
The behavior is similar - PIF fully does not pass, although if you disable module, basic is passed. RisingOS, android 14, google pixel 6 pro

**Comment by Azuriye** [comment]
I can vouch for playstore loading very slowly, guess it occured in the latest module release... Anyone else?

**Comment by gss200610** [comment]
> I can vouch for playstore loading very slowly, guess it occured in the latest module release... Anyone else?

update you google services apk and google playstore to latest beta version, loop disapear, so fingerrprint are banned.
