### ISSUE TITLE
To use default fingerprint inbuild in the module just remove pif.json file.

### ISSUE THREAD

**Issue by ilwsm** [chiteroman/PlayIntegrityFix#171]
https://github.com/chiteroman/PlayIntegrityFix/releases

Remove from where?

**Comment by VisionR1** [comment]
> Remove from where?

/data/adb/pif.json

**Comment by ilwsm** [comment]
>You must move the template from module folder to adb dir if you want to use your custom props.
Mean: `json.pif`
```json```
{
	"PRODUCT": "",
	"DEVICE": "",
	"MANUFACTURER": "",
	"BRAND": "",
	"MODEL": "",
	"FINGERPRINT": "",
	"SECURITY_PATCH": "",
	"FIRST_API_LEVEL": "",
	"BUILD_ID": "",
	"VNDK_VERSION": ""
}
```
The template needs to be filled in with data and copied to `data/adb/pif.json`. Right?

**Comment by VisionR1** [comment]
> > You must move the template from module folder to adb dir if you want to use your custom props.
> 
> Mean: The template `json.pif`
> 
> ```json
> {
> 	"PRODUCT": "",
> 	"DEVICE": "",
> 	"MANUFACTURER": "",
> 	"BRAND": "",
> 	"MODEL": "",
> 	"FINGERPRINT": "",
> 	"SECURITY_PATCH": "",
> 	"FIRST_API_LEVEL": "",
> 	"BUILD_ID": "",
> 	"VNDK_VERSION": ""
> }
> ```
> 
> needs to be filled in with data and copied to `data/adb/pif.json`. Right?

Right, filled with fingerprint information

**Comment by ilwsm** [comment]
Thanks, exactly to `/data/adb/pif.json` or another `/data/adb/*` folder?

**Comment by Tupu4545** [comment]
> > > You must move the template from module folder to adb dir if you want to use your custom props.
> > 
> > Mean: The template `json.pif`
> > 
> > ```json
> > {
> > 	"PRODUCT": "",
> > 	"DEVICE": "",
> > 	"MANUFACTURER": "",
> > 	"BRAND": "",
> > 	"MODEL": "",
> > 	"FINGERPRINT": "",
> > 	"SECURITY_PATCH": "",
> > 	"FIRST_API_LEVEL": "",
> > 	"BUILD_ID": "",
> > 	"VNDK_VERSION": ""
> > }
> > ```
> > 
> > needs to be filled in with data and copied to `data/adb/pif.json`. Right?
> 
> Right, filled with fingerprint information 



Where do I get my custom props for my device?

**Comment by Tupu4545** [comment]
> > Remove from where?
> 
> /data/adb/pif.json

For me it is not there instead it's in /data/adb/modules/playintegrityfix/pif.json

**Comment by VisionR1** [comment]
> Thanks, exactly to `/data/adb/pif.json` or another `/data/adb/*` folder?

Exactly there

**Comment by VisionR1** [comment]
> > > > You must move the template from module folder to adb dir if you want to use your custom props.
> > > 
> > > 
> > > Mean: The template `json.pif`
> > > ```json
> > > {
> > > 	"PRODUCT": "",
> > > 	"DEVICE": "",
> > > 	"MANUFACTURER": "",
> > > 	"BRAND": "",
> > > 	"MODEL": "",
> > > 	"FINGERPRINT": "",
> > > 	"SECURITY_PATCH": "",
> > > 	"FIRST_API_LEVEL": "",
> > > 	"BUILD_ID": "",
> > > 	"VNDK_VERSION": ""
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > needs to be filled in with data and copied to `data/adb/pif.json`. Right?
> > 
> > 
> > Right, filled with fingerprint information
> 
> Where do I get my custom props for my device?

You need a old fingerprint, can found from internet and write the info inside in the pif.json

**Comment by VisionR1** [comment]
And if the file pif.json is /data/adb/modules/playintegrityfix/pif.json
You have old version of this module

**Comment by ilwsm** [comment]
Can i get info from very old phone, like [HTC Desire](https://www.gsmarena.com/htc_desire-3077.php) ?

**Comment by VisionR1** [comment]
> Can i get info from very old phone, like [HTC Desire](https://www.gsmarena.com/htc_desire-3077.php) ?

I think after android 6. Can work Android 6,7,8,9. Here a guide: https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89189572

**Comment by ladyfoxpoint** [comment]
> And if the file pif.json is /data/adb/modules/playintegrityfix/pif.json You have old version of this module

I downloaded the latest release from github and the file was in /data/adb/modules/playintegrityfix + I'm not passing device certification
Is there somewhere else to download a more recent release that I couldn't find?
Current installed version is: 14.4

**Comment by VisionR1** [comment]
> > And if the file pif.json is /data/adb/modules/playintegrityfix/pif.json You have old version of this module
> 
> I downloaded the latest release from github and the file was in /data/adb/modules/playintegrityfix + I'm not passing device certification Is there somewhere else to download a more recent release that I couldn't find? Current installed version is: 14.4

I'm using the v14 and work with custom fingerprint, but you sure using v14.4? Because the 14.4 say this

![IMG_20231216_201435](https://github.com/chiteroman/PlayIntegrityFix/assets/25982450/a12bfe0a-c26c-4381-9764-c3913eb6f17e)

**Comment by ladyfoxpoint** [comment]
> > > And if the file pif.json is /data/adb/modules/playintegrityfix/pif.json You have old version of this module
> > 
> > 
> > I downloaded the latest release from github and the file was in /data/adb/modules/playintegrityfix + I'm not passing device certification Is there somewhere else to download a more recent release that I couldn't find? Current installed version is: 14.4
> 
> I'm using the v14 and work with custom fingerprint, but you sure using v14.4? Because the 14.4 say this
> 
> ![IMG_20231216_201435](https://private-user-images.githubusercontent.com/25982450/291009148-a12bfe0a-c26c-4381-9764-c3913eb6f17e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NTUwNTAsIm5iZiI6MTcwMjc1NDc1MCwicGF0aCI6Ii8yNTk4MjQ1MC8yOTEwMDkxNDgtYTEyYmZlMGEtYzI2Yy00MzgxLTk3NjQtYzM5MTNlYjZmMTdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE5MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDJmNjYwMGE0YTg0MjVhMDc5MWY2ZmIyNzM5MTcwZDc4YjdlOGVmM2VhMzVkZWI5YjExMDAyZjYxYWQwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mvHYBodx8wGMPTRFnohAwbFnDB4NFTkCPS_OhGECYek)

Oh I see, it says it *can* read it, not that it's the only one that should exist
I'm sorry, I misunderstood the message from Vision.

**Comment by VisionR1** [comment]
> > > > And if the file pif.json is /data/adb/modules/playintegrityfix/pif.json You have old version of this module
> > > 
> > > 
> > > I downloaded the latest release from github and the file was in /data/adb/modules/playintegrityfix + I'm not passing device certification Is there somewhere else to download a more recent release that I couldn't find? Current installed version is: 14.4
> > 
> > 
> > I'm using the v14 and work with custom fingerprint, but you sure using v14.4? Because the 14.4 say this
> > ![IMG_20231216_201435](https://private-user-images.githubusercontent.com/25982450/291009148-a12bfe0a-c26c-4381-9764-c3913eb6f17e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NTUwNTAsIm5iZiI6MTcwMjc1NDc1MCwicGF0aCI6Ii8yNTk4MjQ1MC8yOTEwMDkxNDgtYTEyYmZlMGEtYzI2Yy00MzgxLTk3NjQtYzM5MTNlYjZmMTdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE5MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDJmNjYwMGE0YTg0MjVhMDc5MWY2ZmIyNzM5MTcwZDc4YjdlOGVmM2VhMzVkZWI5YjExMDAyZjYxYWQwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mvHYBodx8wGMPTRFnohAwbFnDB4NFTkCPS_OhGECYek)
> 
> Oh I see, it says it _can_ read it, not that it's the only one that should exist I'm sorry, I misunderstood the message from Vision. And yes, I'm positive I'm on 14.4.

It's ok, maybe you not passing device certification because you're custom fingerprint is not right
