### ISSUE TITLE
OTP Bank HU app does not work

### ISSUE THREAD

**Issue by dchard** [chiteroman/PlayIntegrityFix#175]
https://play.google.com/store/apps/details?id=hu.otpbank.mobile

The motherf*cker hungarian OTP Bank app does not work (detects root) no matter what I do.

Every other app (including other banking and payment apps) does work with latest Majisk + Zygisk deny list + PlayIntegrityFix, this OTP Bank app is the first one that keeps detecting this. Latest Majisk, PlayIntegrityFix 14.4 , Android 13 on XiaomiEU ROM. the app is added to the deny list.

Is there something I can try?

**Comment by MarkusTieger** [comment]
Post your problem on Reddit (r/Magisk). It technically has nothing to do with PlayIntegrityFix and no one will answer you here a solution. You can maybe try Shamiko. (But be warned, it caused bootloops on my phone)

**Comment by furdiburd** [comment]
Diaable dev option and add it to denylist. It just worked on my device with magisk alpha + newest shamiko (194) and play integrity fix

**Comment by furdiburd** [comment]
> > Can you mark this as closed?
> 
> I tried with latest magisk (not alpha) + the shamiko verison you recommended + latest play integrity fix and it still does not work. I will try later on with the alpha once I figure out a reliable source for it.

How hard is it to google magisk alpha? https://t.me/s/magiskalpha?before=590

**Comment by Kanyazsombor** [comment]
I had the same issue with other banking app. "Hide my Applist" xposed module solved it. Magisk beta 26.4 + zigisk lsposed v1.9.2

The otp app is probably able to see, that you have other apps installed, which are on their blacklist.

**Comment by chiteroman** [comment]
"Play Integrity Fix" and no "OTP Bank HU Fix"
