### ISSUE TITLE
Wallet tap to pay broke today

### ISSUE THREAD

**Issue by chx** [chiteroman/PlayIntegrityFix#18]
I saw on XDA this happened to quite a few people and I am posting here because I would like to help not just myself but others too.

So, how can I help figuring out what the change was?

I have a Pixel 4 (flame), Magisk 26.4, Safetynet v12.1. I used Displax’s before.

My Denylist contained Wallet and YASNAC. YASNAC passes Basic and CTS. Installed https://github.com/1nikolas/play-integrity-checker-app added to denylist, as expected it passed MEETS_DEVICE_INTEGRITY and MEETS_BASIC_INTEGRITY and fails MEETS_STRONG_INTEGRITY. So far so good.

But still, wallet tap to pay no longer works and complains the phone is not secure. I have hidden Magisk and rebooted, no change. 

Had Systemless Host and Tarb modules installed, disabled them and rebooted, no change.

How do I proceed?

**Comment by chx** [comment]
Strange thing is , even disabling enforce denylist and removing yasnac/integrity checker doesn't break anything. But removing Wallet from the denylist does nothing.

**Comment by Tryffin** [comment]
After yesterday's update, with Displax's safetynet fix mod 1.2 not working on my RedMagic 8S Pro with Magisk v26.4 + Zygsik+ Shamiko(Google Play and wallet are always in exclusion list), I installed PlayIntegrityFix and clear all data of Google Play Store, Play Service and rebooted, now it works fine

**Comment by chiteroman** [comment]
Wipe data and cache of Wallet, Store and GSF, reboot and check again.

**Comment by Tryffin** [comment]
> Wipe data and cache of Wallet, Store and GSF, reboot and check again.

I did the same thing, and it worked
