### ISSUE TITLE
14.5 problem with CTS and Play integrity

### ISSUE THREAD

**Issue by emas20** [chiteroman/PlayIntegrityFix#180]
In Xiaomi CTS failed, meets device integrity failed

**Comment by betterphp** [comment]
The details of the spoofed device that this module uses has been banned by Google now. You can either search for your own fingerprint (details in the XDA thread) or wait and see how my issue #179 plays out

**Comment by lbchX** [comment]
Thanks for the sharing and update but unfortunately problem again (mi 10 lite 5g)!
P.S Maybe i have to wait for the next update
Cheers!

**Comment by pegasusxz** [comment]
This fixed it for me. Not sure how long this will work

https://github.com/daboynb/PlayIntegrityNEXT

**Comment by lbchX** [comment]
> This fixed it for me. Not sure how long this will work
> 
> https://github.com/daboynb/PlayIntegrityNEXT

Unfortunately nothing happens, also i cant grant access for the "gms apk" with magisk! 
I will just wait for the next fix
