### ISSUE TITLE
14.8 fails device integrity, 14.5 worked

### ISSUE THREAD

**Issue by Jon8RFC** [chiteroman/PlayIntegrityFix#186]
Pixel 8 Pro

Just updated from 14.5 which showed passing device integrity right before updating to 14.8 and rebooting.

Is there anything I can share for troubleshooting?

**Comment by playaz44** [comment]
Pixel 7 pro same

**Comment by SirBughunter** [comment]
Same here. Pixel 4.

Do we have to do something else now? I read something in the release notes of 14.7. But I'm not sure. 🥲

**Comment by Jon8RFC** [comment]
Oops, 14.5 worked. I didn't use 14.6

**Comment by playaz44** [comment]
14.6 working fine for me

**Comment by Jon8RFC** [comment]
Maybe I'm getting the confused. 14.8 didn't work so I installed 14.6 on top, rebooted and I'm getting "no integrity", so I figured it was 14.5

Trying to figure out the "no integrity" and Google app crashes now, even when uninstall ING the module. Gsf and play services clear data and reboot didn't help. Someone said using v4 fork corrected it.

**Comment by FredxDX** [comment]
14.6 working here. 14.8 didnt

**Comment by Fusseldieb** [comment]
If I'm not mistaken @chiteroman told in his Telegram channel that he will no longer ship pif.json files in the newer versions, and that you must get them yourselves. For these that don't understand what this file is, it's basically the fingerprint. Without it, the whole thing doesn't work.
I don't know why he stopped caring (blackmail?, dmca?, ...) but in any case, as he said in his own words "Let the hunger games begin".
Kinda sad, but it is what it is.

**Comment by furdiburd** [comment]
Is someone still want to use a module with inbuild json then use playintegrityNEXT till you find a working fingerprint.  https://github.com/daboynb/PlayIntegrityNEXT

**Comment by Mario6425** [comment]
After the update to 14.8, unfortunately nothing works anymore.

**Comment by Mario6425** [comment]
@HarriBuh 
The smiley is unnecessary.
My comment reads a bit badly, I confess. I would like, or rather wanted, to add that V 14.8 also causes the same problem for me. I added the comment because there were already discrepancies in terms of functionality with V 14.2 and I merely confirmed this. Is that better for you?

**Comment by SirBughunter** [comment]
> Is someone still want to use a module with inbuild json then use playintegrityNEXT till you find a working fingerprint.  https://github.com/daboynb/PlayIntegrityNEXT
> 
> Device integrity still passes for me

I can confirm this is working for me! 🙌

**Comment by furdiburd** [comment]
> @SirBughunter Does it work with Android 14? There's no info about it on the repo's page.

Its built on pif v14.1 so if that works (pas basic integrity) then it should too but i cant test it. (I use xperia 5 and its android 12l

**Comment by SirBughunter** [comment]
> @SirBughunter Does it work with Android 14? There's no info about it on the repo's page.

Probably. Don't know, though, because I'm currently on A13.

**Comment by Mario6425** [comment]
![Screenshot_2023-12-23-16-19-52-59_dceca68b28b65a6520b4cd25ec08b8d5](https://github.com/chiteroman/PlayIntegrityFix/assets/115133131/4e2be4c6-23bf-4409-8c20-9dbf54fa93d0)

Play integrity NEXT runs on A14. I can confirm that.

P.s sorry for the little incident in the thread, doesn't belong here. but shouldn't go uncommented either.

**Comment by Dusk-Golem** [comment]
I think the fingerprint is toast, again. Tried the latest version 14.9 and still failed the device verdict. Using my custom fingerprint made it work again. Passing device and basic verdicts now without issues.

**Comment by furdiburd** [comment]
> I think the fingerprint is toast, again. Tried the latest version 14.9 and still failed the device verdict. Using my custom fingerprint made it work again. Passing device and basic verdicts now without issues.

Cuz PIF no longer have inbuild fingerprint like 3 version ago....

**Comment by gerrbuh** [comment]
Pixel 8 pro, Xiaomi Mi 9T pro - 14.6 working here. 14.8 and 14.9 didnt

**Comment by furdiburd** [comment]
> Pixel 8 pro, Xiaomi Mi 9T pro - 14.6 working here. 14.8 and 14.9 didnt

using own fingerprint?

**Comment by mesiu84** [comment]
Is three aby instruction how to pułk that fingerprint yourself?

**Comment by mesiu84** [comment]
using version higher then 14.6 breaks MEETS_DEVICE_INTEGRITY in Play Integrity API Checker app
also Mi 9T Pro
