### ISSUE TITLE
14.8 fails with device_integrity

### ISSUE THREAD

**Issue by Chaitanya36500** [chiteroman/PlayIntegrityFix#188]
It fails with device_integrity. Please try to fix it 
![Screenshot_20231223_153921_Play Integrity API Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/91261354/369a003b-124e-47a5-b09c-7d60778ef60c)

**Comment by furdiburd** [comment]
It just the same as issue:186. You need to find your own fingerprint with PIF from now on or switch to PlayintegrotyNEXT fork
https://github.com/daboynb/PlayIntegrityNEXT

**Comment by Hi-ImKyle** [comment]
> It just the same as issue:186. You need to find your own fingerprint with PIF from now on or switch to PlayintegrityNEXT

Just bricks my phone, trying to launch apps nothing works anymore and my phone just crashes after like 5 minutes. Don't use this.

**Comment by furdiburd** [comment]
> > It just the same as issue:186. You need to find your own fingerprint with PIF from now on or switch to PlayintegrityNEXT
> 
> Just bricks my phone, trying to launch apps nothing works anymore and my phone just crashes after like 5 minutes. Don't use this.

That aint supposed to happen. Then u need to find a fingerprint or fix your setup

**Comment by Hi-ImKyle** [comment]
> Then u need to find a fingerprint or fix your setup

Isn't that the whole point in PlayIntegrityNEXT, that it gives you a fingerprint automatically..? Or the app does. Idk. Followed the instructions and my phone just stopped working. It's not my fault if I follow the instructions and it doesn't work.

**Comment by furdiburd** [comment]
> Isn't that the whole point in PlayIntegrityNEXT, that it gives you a fingerprint automatically..? Or the app does. Idk. Followed the instructions and my phone just stopped working. It's not my fault if I follow the instructions and it doesn't work.

I meant that if piNEXT cradhes your phone then just use pif  with  a fingerpront if that works

**Comment by Hi-ImKyle** [comment]
> I meant that if piNEXT cradhes your phone then just use pif with a fingerpront if that works

Yeah, I would if anything opened and didn't crash.

**Comment by furdiburd** [comment]
> > I meant that if piNEXT cradhes your phone then just use pif with a fingerpront if that works
> 
> Yeah, I would if anything opened and didn't crash.

Boot into safe mode?

**Comment by Hi-ImKyle** [comment]
> Boot into safe mode?

Yeah I'm just not gonna use the NEXT one. Clearly doesn't work for me. I guess I'm SoL.

**Comment by qquiderr** [comment]
Half working, one app pass, my bank app works, but Google wallet (pay) not working!

![Screenshot_2023-12-23-14-20-54-101_gr nikolasspyr integritycheck](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/f36ce16a-ce23-4be2-a501-090fd6f2719e)
![Screenshot_2023-12-23-14-21-59-597_com google android gms](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/079a1b59-5615-4866-9562-364712320dc7)
![Screenshot_2023-12-23-14-23-14-286_rikka safetynetchecker](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/9c50fdf7-2fde-4eb3-8db9-e0b31a92e6ce)

**Comment by furdiburd** [comment]
> Half working, one app pass, my bank app works, but Google wallet (pay) not working!
> 
> ![Screenshot_2023-12-23-14-20-54-101_gr nikolasspyr integritycheck](https://private-user-images.githubusercontent.com/27881740/292628302-f36ce16a-ce23-4be2-a501-090fd6f2719e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzg5MDksIm5iZiI6MTcwMzMzODYwOSwicGF0aCI6Ii8yNzg4MTc0MC8yOTI2MjgzMDItZjM2Y2UxNmEtY2UyMy00YmUyLWE1MDEtMDkwZmQ2ZjI3MTllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEzMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTYwNWJlNmE3ODNkYWRhYmE3MmQ4ZjNiMzk3NjAzYzMyMmI3ZTE4NWI0Njk2N2JjMzNkNDcwZjA2NDAyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h7u6M_-Qytx9TLbylHUoT2xwvnWSdDHQrK98c9fPT8A) ![Screenshot_2023-12-23-14-21-59-597_com google android gms](https://private-user-images.githubusercontent.com/27881740/292628303-079a1b59-5615-4866-9562-364712320dc7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzg5MDksIm5iZiI6MTcwMzMzODYwOSwicGF0aCI6Ii8yNzg4MTc0MC8yOTI2MjgzMDMtMDc5YTFiNTktNTYxNS00ODY2LTk1NjItMzY0NzEyMzIwZGM3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEzMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MTMwMzY5NzNjZjNlNjExMTdhMTViZWM3MjkyMDQ3ZGYxNWU4MzkxMzVmYjZhZDIwNWEwMmIzNmI3MGE2NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J70_Lpfe56_QTxexA4ElTRzArWPUraXEBj68Ed-a2jc) ![Screenshot_2023-12-23-14-23-14-286_rikka safetynetchecker](https://private-user-images.githubusercontent.com/27881740/292628305-9c50fdf7-2fde-4eb3-8db9-e0b31a92e6ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzg5MDksIm5iZiI6MTcwMzMzODYwOSwicGF0aCI6Ii8yNzg4MTc0MC8yOTI2MjgzMDUtOWM1MGZkZjctMmZkZS00ZWIzLThkYjktZTBiMzFhOTJlNmNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEzMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MjUyYjdhNWYzNTliOTBhMWNjOTYyYTk3Y2NmNjAzNWQxNTJlMDlhOTBjOTA3MDU5ZjE1MDU2ZDFlZDA1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l5XOd0ybmqIO3HKt2jLaPpC2vDOLKLl55jBsmHHM3kY)

With PiNEXT? if yes, deleted the pif.json pr used the gms_cleaner?

**Comment by qquiderr** [comment]
I Havel hidden magisk.
Here Is my settings.

![Screenshot_2023-12-23-14-43-25-306_ta kfe](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/80a4e296-3d4a-4afc-8296-700f60f1da6d)
![Screenshot_2023-12-23-14-43-50-496_ta kfe](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/1b67f135-fedb-4ee2-99fd-339eb15c50d7)
![Screenshot_2023-12-23-14-44-03-666_ta kfe](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/597d92ed-af3a-48d8-8a44-fba94319c100)
![Screenshot_2023-12-23-14-44-12-503_ta kfe](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/32f04b06-fe74-41df-a9c5-08d223a042d0)
![Screenshot_2023-12-23-14-44-16-453_ta kfe](https://github.com/chiteroman/PlayIntegrityFix/assets/27881740/dc20438a-36f6-4939-a0f4-5d9a8141510e)

**Comment by furdiburd** [comment]
> I Havel hidden magisk. Here Is my settings.
> 
Pif v14.8 need to use your own fingerprint... Only playintegrityNEXT fork dont need that. Use that or get your own fingerprint. Case closed

**Comment by qquiderr** [comment]
> > I Havel hidden magisk. Here Is my settings.
> 
> Pif v14.8 need to use your own fingerprint... Only playintegrityNEXT fork dont need that. Use that or get your own fingerprint. Case closed
> 
> https://github.com/daboynb/PlayIntegrityNEXT

Big thanks, Google wallet works!

**Comment by Azur4** [comment]
Same problem with custom pif.json
14.6 workig fine.

**Comment by nit3rain** [comment]
I can confirm this issue. I'm using my custom pif.json and on my Mi Pad 5 Pro I can pass basic_integrity only with 14.8. Reverting to 14.6 makes it pass both basic and device_integrity as usual.

**Comment by MikeZeDev** [comment]
Is that possible to make my own pif.json from my official on the computer, btw?

**Comment by crok** [comment]
I experience the very same problem. I have 4 working pif.json files and all 4 works flawlessly with v14.6 but none of them are working with v14.8. Everyone copypastes the very same answer that _"you need your own fingerprint bla bla"_ and I'm tired to explain it again and again.. trust me (and us who say it): we own working pif.json files which do work with v14.6 but do not work with v14.8. You can ignore it, you can copypaste the same answere again and again.. but still.. the issue is real.

**Comment by furdiburd** [comment]
> Is that possible to make my own pif.json from my official on the computer, btw?

If its not an old phone without TEE then it just wont.work but yes its possible

**Comment by furdiburd** [comment]
> I experience the very same problem. I have 4 working pif.json files and all 4 works flawlessly with v14.6 but none of them are working with v14.8. Everyone copypastes the very same answer that _"you need your own fingerprint bla bla"_ and I'm tired to explain it again and again.. trust me (and us who say it): we own working pif.json files which do work with v14.6 but do not work with v14.8. You can ignore it, you can copypaste the same answere again and again.. but still.. the issue is real.

Seems like v14.8 having issues. Then its gonna be v14.6 till a fix to your problem

**Comment by crok** [comment]
> Seems like v14.8 having issues. Then its gonna be v14.6 till a fix to your problem

It is not only a problem of v14.8, first I experienced this with v14.7 and that build has been even deleted from the releases so I guess this issues has been introduces in v14.7. But actually it seems that noone cares.

**Comment by MikeZeDev** [comment]
> possible

Its an A51 it should work but i have no clues about the method.

**Comment by abdulhkeemGit** [comment]
Same here s23 ultra on android 14.

**Comment by chiteroman** [comment]
Module doesn't include a working fingerprint.
