### ISSUE TITLE
14.9

### ISSUE THREAD

**Issue by xFerZx** [chiteroman/PlayIntegrityFix#193]
Version 14.9, DEVICE integrity does not work the same way.
Device: POCO F3 8/256
DEVICE integrity has been fixed.

**Comment by pcroland** [comment]
Same, CTS profile match fails on Nothing Phone 1

**Comment by gerrbuh** [comment]
Version 14.9, DEVICE integrity does not work
Device Xiaomi Mi 9T Pro

**Comment by markdepalma** [comment]
CTS profile match failing. Pixel 4 XL

**Comment by xFerZx** [comment]
DEVICE integrity has been fixed.
