### ISSUE TITLE
CTS profile fail Redmi Note 12 Pro 5g

### ISSUE THREAD

**Issue by Delphiniki** [chiteroman/PlayIntegrityFix#195]
My phone is Xiaomi Redmi Note 12 Pro 5G .I have Magisk 26.4 and i use Zygisk Next v.4-0.8.1.Firmware is MIUI Global 14.0.11.0 TMOEUXM ,Android 13.Security update date - 2023-11-01.The cts profile fails.Only Play Integrity Fix v.14.4 works for me.Thanks.

**Comment by matusmlady** [comment]
Hello, I have Xiaomi mi a1 and have the same problem in microg, lineag os 20, magisk 26.4.
![Screenshot_20231226-130506_microG Services Core](https://github.com/chiteroman/PlayIntegrityFix/assets/96914042/4bc912d9-b5e4-4f3f-ad10-5b0bcd5ea220)

**Comment by realhuseyn** [comment]
Me too

**Comment by matusmlady** [comment]
after updating to 15.1 problem persists

**Comment by AGA2707** [comment]
Same on my Redmi Note 7. I never encounter this on his previous versions, only on 15.1
![Screenshot_2024-01-01-11-56-19-378_rikka safetynetchecker](https://github.com/chiteroman/PlayIntegrityFix/assets/148602118/c14f5848-5e60-4cc5-b248-487098426911)
![Screenshot_2024-01-01-11-56-38-470_gr nikolasspyr integritycheck](https://github.com/chiteroman/PlayIntegrityFix/assets/148602118/075f1ee8-ca62-412d-b3ea-391b1848fc67)
But Play Store is Certified.

**Comment by Delphiniki** [comment]
Now i am using this :
https://github.com/daboynb/PlayIntegrityNEXT
There is an app too.Screenshots:

![Screenshot_2024-01-01-21-56-29-572_com.topjohnwu.magisk.jpg](https://github.com/chiteroman/PlayIntegrityFix/assets/12499091/d0fd7a95-c8f4-4447-986b-9e09805e6927)

And:
![Screenshot_2024-01-01-22-03-39-047_rikka.safetynetchecker.jpg](https://github.com/chiteroman/PlayIntegrityFix/assets/12499091/9db2e039-fff3-4285-b298-67cb81c1d573)

Offcourse I use the Zygisk deny list option in Magysk 26.4.Its fine for a week.
