### ISSUE TITLE
Should I update from the dev version to the new 14.9 version?

### ISSUE THREAD

**Issue by vassijoseph** [chiteroman/PlayIntegrityFix#196]
I saw in the xda forum that new versions will not include a pif.json file. I have been using the dev version that was already available with a custom pif

Since the newer versions are basically the dev version with other updates should I change to that? Does 14.9 look for the pif.json file in the same place as dev? (/data/adb/pif.json)

**Comment by CRCinAU** [comment]
Yeah - I've been wondering this too.... I'm still using 14.0 - and a custom pif.json.

There were a TON of updates that I missed, and now we're at 15.1 - and I haven't been able to find any real documentation or information about what the rush of releases were, and how things operate now...

If its possible to get some info on what the story is, that would be great....

**Comment by vassijoseph** [comment]
This was closed as, Not planned. This isn't a request for a new update, which may or may not be planned, simply a question of, is the latest main release equivalent to dev 2, which uses a custom fingerprint? If we are using custom fingerprints should we update to the latest main update?
