### ISSUE TITLE
wi-fi calling

### ISSUE THREAD

**Issue by TheGoblinHero** [chiteroman/PlayIntegrityFix#2]
Samsung S23+, magisk 26.3, PIF 8.4. Works ok (everything except strong as expected), but unfortunately breaks wifi calling. There were similar problem with Displax USNF.

**Comment by chiteroman** [comment]
[PlayIntegrityFix.zip](https://github.com/chiteroman/PlayIntegrityFix/files/12650246/PlayIntegrityFix.zip)

Try this version

**Comment by TheGoblinHero** [comment]
Tried your test 8.5 version. It fixes wi-fi calling, but I have only basic integrity now:
https://ibb.co/prkv9LM
https://ibb.co/JFHmf26
Latest USNF 2.4.0mod2.0 works the same way (only basic integrity with working wifi calling) :(

**Comment by chiteroman** [comment]
Try this new build: https://forum.xda-developers.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89030723

**Comment by TheGoblinHero** [comment]
Thank you! This build fixes the problem.
