### ISSUE TITLE
Module not working with secondary user

### ISSUE THREAD

**Issue by goran-rumin** [chiteroman/PlayIntegrityFix#201]
First of all, thanks for the great work on this module. I have been using it for some time now without issues as a primary (system, admin) phone user. 
Recently I created a secondary user on my phone, and although Magisk Manager installed within that user is showing all modules as loaded, I get BASIC integrity. I tried multiple reboots and clearing Play services/Play store caches within that user, but without success. The primary user is still showing DEVICE,BASIC integrity as expected. I do not know if this is a module issue, or something else, but any info would be appreciated. Thanks

Phone: Pixel 7A, Android 13
Magisk: 26.3
Module version: 13.3

**Comment by pablovinicius332** [comment]
Up same
