### ISSUE TITLE
Dirty upgrade from v14.9 to v15.1 makes any armeabi-v7a apps crash instantly

### ISSUE THREAD

**Issue by CanglanXYA** [chiteroman/PlayIntegrityFix#202]
OS: Aosp-like Android 13

Ive just installed newest 15.1 version, and any armeabi-v7a software will crash after activate this module

I was forced to use lower version of apps in china to improve battery life, its hard for me to switch to armv8 soft which is some sort of battery nightmare.

**Comment by CanglanXYA** [comment]
Any version which is below 15.0 (not included) works fine

**Comment by saber-nyan** [comment]
Can confirm, collected some dumps: 
[crash-com-mishiranu-dashchan-31_12-16-36-03_404.zip](https://github.com/chiteroman/PlayIntegrityFix/files/13801273/crash-com-mishiranu-dashchan-31_12-16-36-03_404.zip)

**Comment by chiteroman** [comment]
Using custom fonts ?

**Comment by CanglanXYA** [comment]
> Any version which is below 15.0 (not included) works fine

Ive tried to reinstalled 14.7~15.0 directly at magisk,all of them failed to support armeabi-v7a apps, except the v14.6.

**Comment by CanglanXYA** [comment]
> Using custom fonts ?

no, default system font, full English environment

**Comment by saber-nyan** [comment]
Yep, using these modules. 
![Screenshot_2023-12-31-17-34-25-80_bde972729165103ed5fbdf4fae2143a9](https://github.com/chiteroman/PlayIntegrityFix/assets/25345196/f7563b7b-1b48-48f5-a2e0-e0ee05a43aff)

Without "Enforce DenyList" and PlayIntegrityFix crashes don't happens.

**Comment by CanglanXYA** [comment]
This bug is weird🤔, if you delete current install version and install v14.6 and v15.1 in order, everything will be ok and there is no crash at all

However , if you dirty install from v14.7~14.9 , app will keep crashing even if you roll back to v14.6
