### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by relu76** [chiteroman/PlayIntegrityFix#213]
It hasn't worked for three days.  Google pay has detected root..

**Comment by cambierguillaume** [comment]
15.2 no work rolback 15.1 CT's error

**Comment by MaverickYing** [comment]
ctsProfileMatch false
Oneplus12 kernelSU 11458
PlayintegrityFix 15.2 Shamiko1.0.1(300) ZygiskNext 4-0.9.1.1
