### ISSUE TITLE
15.2 doesn't normal work

### ISSUE THREAD

**Issue by Cyndi2002** [chiteroman/PlayIntegrityFix#215]
Because it does not include fingerprints, it cannot solve the problem of not being able to find Netflix in the play store, and importing pif.json yourself is useless.

**Comment by kaualandi** [comment]
What to do then? Google Pay (Wallet) is still not working...

**Comment by ibart** [comment]
> What to do then? Google Pay (Wallet) is still not working...

We are losing the fight. This is the point.

**Comment by Cyndi2002** [comment]
> What to do then? Google Pay (Wallet) is still not working...

I use the 15.1 again.
