### ISSUE TITLE
getprop values are not modified correctly on Waydroid

### ISSUE THREAD

**Issue by baptx** [chiteroman/PlayIntegrityFix#220]
Hello, when using the PlayIntegrityFix Magisk module on Waydroid (Android 11), I used the command `adb shell getprop` to see if the values are modified correctly and only noticed the `ro.build.tags` value was changed from `test-keys` to `release-keys` even when trying different `/data/adb/pif.json` files from https://github.com/TheFreeman193/PIFS, for example `ro.build.fingerprint` value is still `waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/70:userdebug/test-keys`, is it normal?

After saving the result of the `getprop` command in a file getprop.txt, if I execute the command `grep fingerprint getprop.txt`, I can also see the default values in several places:
```
[ro.bootimage.build.fingerprint]: [waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/68:userdebug/test-keys]
[ro.build.fingerprint]: [waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/70:userdebug/test-keys]
[ro.build.version.preview_sdk_fingerprint]: [REL]
[ro.odm.build.fingerprint]: [waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/68:userdebug/test-keys]
[ro.product.build.fingerprint]: [waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/70:userdebug/test-keys]
[ro.system.build.fingerprint]: [waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/70:userdebug/test-keys]
[ro.system_ext.build.fingerprint]: [waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/70:userdebug/test-keys]
[ro.vendor.build.fingerprint]: [waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/68:userdebug/test-keys]
```
Should I try to edit all these values manually (in `/var/lib/waydroid/waydroid_base.prop` for Waydroid) or only `ro.build.fingerprint` is necessary?

Is it even possible to pass SafetyNet / Play Integrity for Android apps on a computer (for example with Waydroid, Anbox or Android-x86 on VirtualBox)? I did not get it working yet when testing with the app Play Integrity API Checker.

**Comment by osm0sis** [comment]
Very few things are done globally because it's not a good idea to make a device fully pretend to be a different one. Those that aren't safe to be done globally are only done to DroidGuard, so you won't see them in getprop.

**Comment by osm0sis** [comment]
You should close this by the way. 😛

**Comment by brunoaduarte** [comment]
> @osm0sis Thanks for the information. Do you think there is a chance to pass SafetyNet / Play Integrity for Android apps on a computer or there is a technical reason that makes it only work on a real mobile device?

Hi @baptx , have you been able to pass Play Integrity on Waydroid?

**Comment by brunoaduarte** [comment]
> It's possible I think. Might be smart to try to get an x86 json to spoof with though so if there are background checks we're not aware of that relate to architecture they're more likely to pass.

What if running Waydroid on a arm64 host like Raspberry Pi 5? Is that a good idea?

**Comment by brunoaduarte** [comment]
> @osm0sis Thanks for the information. Do you think there is a chance to pass SafetyNet / Play Integrity for Android apps on a computer or there is a technical reason that makes it only work on a real mobile device?

Hi @baptx , have you been able to pass Play Integrity on Waydroid?

> It's possible I think. Might be smart to try to get an x86 json to spoof with though so if there are background checks we're not aware of that relate to architecture they're more likely to pass.

What if running Waydroid on a arm64 host like Raspberry Pi 5? Is that a good idea @osm0sis ?

**Comment by osm0sis** [comment]
🤷‍♂️

**Comment by baptx** [comment]
@brunoaduarte Hi, no, I did not try more than what I wrote.
If someone finds a solution, you can let us know on the dedicated issue:
https://github.com/waydroid/waydroid/issues/182
