### ISSUE TITLE
v15.3.3 beta 

### ISSUE THREAD

**Issue by seflhjn** [chiteroman/PlayIntegrityFix#224]
![Screenshot_20240123-151013](https://github.com/chiteroman/PlayIntegrityFix/assets/105164400/cfa0c3d8-6e3d-4a0d-a984-736b013f2db4)
![Screenshot_20240123-151003](https://github.com/chiteroman/PlayIntegrityFix/assets/105164400/a3176181-69c7-42cc-9660-4b7d3ce86012)
![Screenshot_20240123-150952](https://github.com/chiteroman/PlayIntegrityFix/assets/105164400/8eaae94e-e72f-4f4a-9480-def15eee67ad)

I was search netflix on play store but I can't download
and, cts profile is not match
but my device is Protect certified on play store 
I'm so tarable

I useing lg v60.
Rooted by magisk 26404
I 'am a korean
Please understand my babying english

**Comment by chiteroman** [comment]
Module doesn't include a certified fingerprint by default. You must search one by yourself and include it in pif.json file.
