### ISSUE TITLE
v15.2 Kills Camera

### ISSUE THREAD

**Issue by romanmd86** [chiteroman/PlayIntegrityFix#228]
v15.2
On OxygenOS 10.5.13 (Android 10, OnePlus 8 Pro) after installing v15.2 Camera app won't start.
After disabling PIF+restart Camera works.

**Comment by osm0sis** [comment]
Does this happen on my fork? https://github.com/osm0sis/PlayIntegrityFork

**Comment by romanmd86** [comment]
Play Integrity Fork v7 - Camera app works as expected

**Comment by osm0sis** [comment]
Thanks for checking!

**Comment by JunkyardCat** [comment]
@osm0sis 
what do i need to do to use this? i have playintegrity fix updated to 15.2. can you tell me steps on how to properly install your fork?

**Comment by osm0sis** [comment]
This isn't the place for that. Check on XDA.

**Comment by romanmd86** [comment]
Confirmed. On v15.1 Camera app works.

**Comment by romanmd86** [comment]
@chiteroman 
On 15.4 Camera app still dies.
