### ISSUE TITLE
Looping crash of home screen(?) 

### ISSUE THREAD

**Issue by TheTrueColonel** [chiteroman/PlayIntegrityFix#229]
Yesterday I tried the 15.3.4 release and once I logged in to my device (I'm assuming) some part of my home screen kept crashing after about a minute or two, while the phone was being incredibly slow. I can't be 100% sure it's the home screen crashing, as any time the "this app is not responding" dialog popped up, it almost instantly went away. This crashing, once it started, made it very difficult to even reboot my phone to disable the module. 15.2 doesn't have this issue, though it does cause my phone to be slow for a few minutes after boot.

Device Info:
Oneplus 8T KB2005 (Global) 
LineageOS 13 (20-20240119-NIGHTLY-kebab)
Nova Launcher 8.0.6 BETA

**Comment by osm0sis** [comment]
15.2 has intermittent verdict failures on some custom ROMs, you should probably go back to 15.1 for now.
