### ISSUE TITLE
CTS Fail

### ISSUE THREAD

**Issue by kazzaluis** [chiteroman/PlayIntegrityFix#231]
[v15.3.4](https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v15.3)

SM-S908E
Android 13 API 33
Security patch 2023-2-1
Version google play service
 24.02.13 (190400-599553831)

**Comment by osm0sis** [comment]
15.3 is unstable, and 15.2 has intermittent verdict failures on some custom ROMs, so you should probably go back to 15.1 for now.
