### ISSUE TITLE
Play Store shows Device is not certified but PI Checker and Play store developer options says MEETS_DEVICE_INTERGRITY is pass

### ISSUE THREAD

**Issue by zxc7895531** [chiteroman/PlayIntegrityFix#232]
Google Play Store Developer options:

![12c3814e74ab5680626982406c19fb93](https://github.com/chiteroman/PlayIntegrityFix/assets/38042972/ae89c992-38ab-4f25-8886-8fe5673d0c71)

Play Intergity Checker:

![Screenshot_2024-01-25-16-45-31-603_gr nikolasspyr](https://github.com/chiteroman/PlayIntegrityFix/assets/38042972/dd122d0e-4039-4ec4-85a1-3029c84d5507)

But shows `Device is not certified`

![Screenshot_2024-01-25-16-46-17-741_com android ve](https://github.com/chiteroman/PlayIntegrityFix/assets/38042972/bebfc4a2-7c9c-42c2-a5d4-a12ace15ed89)

**Comment by osm0sis** [comment]
15.3 is unstable, and 15.2 has intermittent verdict failures on some custom ROMs, so you should probably go back to 15.1 for now.

**Comment by Konne06** [comment]
I had the same problem as this, and it was the same when I used 15.1. I am Android 14

**Comment by osm0sis** [comment]
Go read the FAQ. Play Store stays un-Certified until you wipe data on it and wait.

**Comment by Konne06** [comment]
I had wipe the play store app data, even I  wipe the play services data, but it still remains un-Certified.

**Comment by osm0sis** [comment]
At one point people were seeing that a single wipe of Play Store data didn't work and they had to do it multiple times. I can't explain why this happens or works but it happened to me directly. Certified now.

**Comment by TecnoFran** [comment]
Hello, using the Evolution X ROM the banking apps and everything works without problems. As it does?
