### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [chiteroman/PlayIntegrityFix#234]
I'm on Android 14. I installed this module but Google Wallet is still detecting root. I'm failing the strong and device integrity checks. I'm using Lucky Patcher module and modded Playstore. Idk if that's relevant. Though, it was working fine on Android 13 with the universal safety net fix.

**Comment by MustafaErenKaplan** [comment]
because this module doesnt have fingerprint

**Comment by Konne06** [comment]
I found a solution
https://github.com/TheFreeman193/PIFS
