### ISSUE TITLE
device meets basic integrity

### ISSUE THREAD

**Issue by Pro2stinger** [chiteroman/PlayIntegrityFix#237]
this used to be device integrity but now it no longer is. can this be fixed

**Comment by srt54558** [comment]
You need to get a fingerprint yourself now.

**Comment by ShiJie137** [comment]
> You need to get a fingerprint yourself now.

How to do it? What to do after getting my fingerprint

**Comment by ShiJie137** [comment]
> You need to get a fingerprint yourself now.

How to do it? What to do after getting my fingerprint

**Comment by srt54558** [comment]
> > You need to get a fingerprint yourself now.
> 
> How to do it? What to do after getting my fingerprint

You have to fill out the pif.json file out and put it in /data/adb/ 

OR

You can use PIFS to get random already created pif.json files. It works on my device flawlessly.

https://github.com/TheFreeman193/PIFS

**Comment by ShiJie137** [comment]
> > > You need to get a fingerprint yourself now.
> > 
> > 
> > How to do it? What to do after getting my fingerprint
> 
> You have to fill out the pif.json file out and put it in /data/adb/
> 
> OR
> 
> You can use PIFS to get random already created pif.json files. It works on my device flawlessly.
> 
> https://github.com/TheFreeman193/PIFS

I tried the first option，run this script( /data/local/tmp/pickaprint.sh)，generated pif.json in /data/adb/.And I checked the content inside, but the play check still didn't pass

**Comment by ShiJie137** [comment]
> > > You need to get a fingerprint yourself now.
> > 
> > 
> > How to do it? What to do after getting my fingerprint
> 
> You have to fill out the pif.json file out and put it in /data/adb/
> 
> OR
> 
> You can use PIFS to get random already created pif.json files. It works on my device flawlessly.
> 
> https://github.com/TheFreeman193/PIFS

I tried the first option，run this script( /data/local/tmp/pickaprint.sh)，generated pif.json in /data/adb/.And I checked the content inside, but the play check still didn't pass

**Comment by davemmi** [comment]
https://github.com/chiteroman/PlayIntegrityFix/issues/236
