### ISSUE TITLE
Quick tutorial on how to get a device fingerprint 

### ISSUE THREAD

**Issue by srt54558** [chiteroman/PlayIntegrityFix#238]
Hello,
I've tried searching the web but I don't fully understand what or how to fill the pif.json file.
Can you make a quick tutorial? 
And what are the fingerprint requirements? Like what android version should the device have or so

**Comment by katazina0** [comment]
> Hello, I've tried searching the web but I don't fully understand what or how to fill the pif.json file. Can you make a quick tutorial? And what are the fingerprint requirements? Like what android version should the device have or so

https://github.com/TheFreeman193/PIFS

**Comment by srt54558** [comment]
> > Hello, I've tried searching the web but I don't fully understand what or how to fill the pif.json file. Can you make a quick tutorial? And what are the fingerprint requirements? Like what android version should the device have or so
> 
> https://github.com/TheFreeman193/PIFS

Holy hell! That works perfectly! Thank you SO much!!

But is it technically possible to take the pif.json from an older device I own? That won't get banned

If so, what props do I need to get for the Json?

**Comment by devlocalhost** [comment]
> > > Hello, I've tried searching the web but I don't fully understand what or how to fill the pif.json file. Can you make a quick tutorial? And what are the fingerprint requirements? Like what android version should the device have or so
> > 
> > 
> > https://github.com/TheFreeman193/PIFS
> 
> Holy hell! That works perfectly! Thank you SO much!!
> 
> But is it technically possible to take the pif.json from an older device I own? That won't get banned
> 
> If so, what props do I need to get for the Json?

ive made a DIY guide for that, hope this: https://laurel-updates.onrender.com/blog/pif-diy helps you.
