### ISSUE TITLE
Failed to meet device integrity

### ISSUE THREAD

**Issue by Firvrill** [chiteroman/PlayIntegrityFix#240]
I have already fill in the correct fingerprint to pif.json, and move it to /data/adb/modules/playintegrityfix/,but my phone still failed to pass device integrity check. I tried several times, cleared data of google service and play service framework, and rebooted my phone, but still failed and don't know the reason.
![Screenshot_2024-01-29-16-47-12-616_bin mt plus-edit](https://github.com/chiteroman/PlayIntegrityFix/assets/95120010/14d2e538-809d-4316-a85f-bf367e33954c)

**Comment by Firvrill** [comment]
![Screenshot_2024-01-29-16-46-43-371_gr nikolasspyr integritycheck-edit](https://github.com/chiteroman/PlayIntegrityFix/assets/95120010/ad334478-b4e5-4e11-afc1-a358b01650bc)

**Comment by RafaeloxMC** [comment]
> Then I switched to DEV v2 version and the fingerprint is working again, so I guess something on the module update changed.

This may be a stupid question but where did you get that DEV v2 version from?

**Comment by pmsobrado** [comment]
https://github.com/chiteroman/PlayIntegrityFix/releases/tag/DEV-v2
