### ISSUE TITLE
Mcdonalds app?

### ISSUE THREAD

**Issue by vegetaleb** [chiteroman/PlayIntegrityFix#242]
Installed latest version 15.4 and I can use all bank and money transfer apps, but mcdonalds app is still detecting root !!
Any additional settings to use for this app?

**Comment by chiteroman** [comment]
To use Mcdonalds app you must pass Device verdict.

**Comment by XdekHckr** [comment]
> Installed latest version 15.4 and I can use all bank and money transfer apps, but mcdonalds app is still detecting root !! Any additional settings to use for this app?

I think that you should add mcdonalds app to magisk hide/denylist
