### ISSUE TITLE
Not working on MIUI 13 Redmi note 10 pro

### ISSUE THREAD

**Issue by Zibri** [chiteroman/PlayIntegrityFix#244]
After the reboot a popup said that recording calls have been disabled!
I rechecked the integrity and nothing changed.
So I uninstalled the module and rebooted.
Fortunately recording calls is back.

**Comment by osm0sis** [comment]
Does it work on 15.1?

**Comment by Zibri** [comment]
no Idea. I like the stock miui 13 on my note 10 pro... I just tweaked it a little and got 5 days battery life (on idle) less than 1% per hour :D but still it makes me mad that even on stock rom more and more apps now check for integrity. Even macdonald's app.
Some app have a "weaker" check so I just make a "dual app" and the dual works. But that works only on a few.

**Comment by osm0sis** [comment]
Go check and find out then.

**Comment by chiteroman** [comment]
Check latest: https://github.com/chiteroman/PlayIntegrityFix/releases/latest

**Comment by Zibri** [comment]
> Go check and find out then. You should check 15.1 and 15.5.

I have a ton of stuff installed... and every new miui release seems to get worse on all aspects...
