### ISSUE TITLE
PlayIntegrityFix v15.5 unable to boot

### ISSUE THREAD

**Issue by Cisco-phipse** [chiteroman/PlayIntegrityFix#250]
I have a Xiaomi 13 Pro, (MIUI 14.0.6(UMBEUXM), Magisk 27.0 (27000).  Today I accepted the update for PIF v15.5 and on the reboot my phone would not boot, it kept going straight into recovery.

I managed to delete the PIF from the "data/adb/modules" folder and it seemed to boot up fine, however I had to reinstall Magisk and all my other modules.  Luckily I was at home with my computer close by, so I could google and fix the issue.

Is this a known issue and if I upgrade to the next version, will I encounter the same problem?

[magisk_install_log_2024-02-04T15.08.06[1].log](https://github.com/chiteroman/PlayIntegrityFix/files/14159091/magisk_install_log_2024-02-04T15.08.06.1.log)

**Comment by markfm62** [comment]
@Cisco-phipse - See https://t.me/playintegrityfix/148571/174791
(a PIF test build to fix the Xiaomi boot issue - I've seen at least  one report on it working)

**Comment by Cisco-phipse** [comment]
This worked! Thank you (●'◡'●)

**Comment by Cisco-phipse** [comment]
Issue closed!
