### ISSUE TITLE
Magisk 17 broke

### ISSUE THREAD

**Issue by Areg472** [chiteroman/PlayIntegrityFix#252]
So I updated to magisk 17 and google wallet stopped working. Pls issue a new release with the issue being fixed

**Comment by sawdoctor** [comment]
You mean magisk 2.7 not 1.7? If updating Magisk broke things then the issue is with Magisk not PIF

**Comment by rube200** [comment]
I upgrade both Magisk and PlayIntegrityFix at same time, Google Services broke and keep crashing, after downgrade PlayIntegrityFix 15.5v everything is working fine.

**Comment by chiteroman** [comment]
Check latest version: https://github.com/chiteroman/PlayIntegrityFix/releases/latest

**Comment by rube200** [comment]
It's working fine for me now, what about you @Areg472 ?

**Comment by Areg472** [comment]
It is still not working. Btw I am using samsung galaxy a24
