### ISSUE TITLE
CTS (DEVICE) still doesn't pass, any tips on what I can try?

### ISSUE THREAD

**Issue by TAbdiukov** [chiteroman/PlayIntegrityFix#253]
Device: Samsung GT-I9505
Android: 10
Build: Optimized-LineageOS-17.1-Version-9 - Release

Context: Both BASIC and DEVICE previously passed without any problems with safetynet-fix Magisk module, but CTS (DEVICE) randomly stopped passing (for no apparent reason). 
* Upgraded Magisk from v25 to v27 (both binary and app) , reboot - no change
* I deleted `safetynet-fix` upgraded to PlayIntegrityFix, reboot, but no change.
* Then I tried known-good `/data/adb/pif.json` (PlayIntegrityNEXT) , reboot, - no luck. 
* Then upgraded PlayIntegrityFix to v1.5.7.1, reboot - no change
* Then I deleted `/data/adb/pif.json` per this version recommendation, reboot - no change

Any tips on what I can try to pass DEVICE check?

**Comment by chiteroman** [comment]
Check the output of the command: "uname -r"

Google blacklisted few kernel release strings like LineageOS, to pass Device verdict you must use another kernel or patch the current kernel modifying kernel release name.

**Comment by TAbdiukov** [comment]
```
$ uname -r
3.4.112-JDCTeam-BuffCore_10.6
```

Is this string blacklisted? Notice - no "LineageOS".

[Release v15.7.2](https://github.com/chiteroman/PlayIntegrityFix/commit/3753ee5ca7106c54050b4b5a3f04dea356ae6ee1) didn't change anything yet, but thanks for the tip

**Comment by TAbdiukov** [comment]
Closing issue as it's highly likely a case of https://github.com/chiteroman/PlayIntegrityFix/issues/236
