### ISSUE TITLE
-100

### ISSUE THREAD

**Issue by N0nd** [chiteroman/PlayIntegrityFix#254]
![Screenshot_20240208-063106](https://github.com/chiteroman/PlayIntegrityFix/assets/15716960/756ada2c-414e-4685-aecf-3c5a9f1112b2)
how do I get around this error? android 9 oxygen, safetynet passes

**Comment by chiteroman** [comment]
Seems like a bug in app. Try checking PI in Play Store.

**Comment by N0nd** [comment]
> Seems like a bug in app. Try checking PI in Play Store.

No, this is definitely not an app bug.
![Screenshot_20240208-075900](https://github.com/chiteroman/PlayIntegrityFix/assets/15716960/7a6c1c8c-f668-4799-8aec-5385eea6544f)

**Comment by non-bin** [comment]
The app is getting too many requests, And he's getting rate limited. Try again a bit later, or try a different app.

It's not an issue with this module

**Comment by bruhmoment21** [comment]
try disabling other modules such as zygisk-detach if enabled

**Comment by N0nd** [comment]
> try disabling other modules such as zygisk-detach if enabled

indeed disabling zygisk-detach helped, then it's his fault
