### ISSUE TITLE
Google pay issue (9 Feb 2024)

### ISSUE THREAD

**Issue by non-bin** [chiteroman/PlayIntegrityFix#255]
I'm passing device integrity, but Google pay gives an error as soon as I bring it near a payment reader.

Anyone else having this issue? I can't try with a different PIF till tomorrow

**Comment by XdekHckr** [comment]
If you are sure that you pass basic integrity and device integrity (you can check that by checking it in few apps to be sure) then clear data of google wallet and add card again...

**Comment by non-bin** [comment]
Did that, and I tried a new PIF today but still no dice 
No one else having problems then?

**Comment by non-bin** [comment]
I messed up an OTA and had to re-root, and somewhere in there it fixed itself
