### ISSUE TITLE
New attestation method

### ISSUE THREAD

**Issue by non-bin** [chiteroman/PlayIntegrityFix#256]
I'm not nearly talented enough to make this a reality, but I wonder if it would be possible to clone or patch the Google wallet app to be able to check if it will work without having to embarrass yourself while trying to pay

**Comment by vcampitelli** [comment]
In my Wallet app, I can just click on my profile picture, go to "Tap to pay setup" and it will show me if my phone does not meet security requirements.

**Comment by non-bin** [comment]
Thank you, that's good enough 👍

**Comment by vladrevers** [comment]
@vcampitelli  the information in that item is not updated instantly... i.e. if you "fix" the problem, it will still say for some time that the device does not meet the security requirements (If you do not do additional cleaning), but the payment will still work.... I think it can be the other way around too, if the check is done during payment.

@non-bin  you can check it with this - https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck, for payment to work, the first two verdicts must be positive.

**Comment by non-bin** [comment]
I have an app similar and it was passing.

Google pay users extra tests on top of the regular play integrity, see issues #163 and #69 for examples

**Comment by chiteroman** [comment]
Maybe you are searching this: https://xdaforums.com/t/gpay-checker-monitor-of-google-pay-availability.4643969/
