### ISSUE TITLE
Samsung S9+ (g965f) random reboots on magisk 27

### ISSUE THREAD

**Issue by 7thbitch** [chiteroman/PlayIntegrityFix#257]
With magisk 26.4 everything worked as expected. After upgrade to 27, no matter what version of play integrity fix or osm0sis play integrity fork causes reboots after ~4h - ~5h. No clue in logcat logs just random reboot.

**Comment by TAbdiukov** [comment]
maybe then the problem is with Magisk, not PlayIntegrityFix?

**Comment by chiteroman** [comment]
Then, the problem is Magisk...

I recommend to report the issue to Magisk dev, try using latest Magisk debug build, it has more logs.
