### ISSUE TITLE
Annoying Bug

### ISSUE THREAD

**Issue by loli067** [chiteroman/PlayIntegrityFix#258]
So basically when i reboot my phone and open integrity checker and hit check it will give me Failed Failed Failed but if i click it one more time it will say passed the bug here is that if i open like wallet or something that checks the integrity before hitting check two times, it will say device does not meet requirements until i hit check and then it will work.
![Screenshot_20240215-170412_Play Integrity API Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/133435955/3d6195a3-2860-4681-b0b2-910b546d3ef5)
![Screenshot_20240215-170438_Play Integrity API Checker]

https://github.com/chiteroman/PlayIntegrityFix/assets/133435955/72416ada-a321-405d-ac8b-dfb579bec14c

(https://github.com/chiteroman/PlayIntegrityFix/assets/133435955/335f50d2-2e0b-453a-b2f1-4e91af4b41d5)

**Comment by chiteroman** [comment]
Try latest build: https://github.com/chiteroman/PlayIntegrityFix/releases/latest

**Comment by loli067** [comment]
Thanks chiteroman its working now.
