### ISSUE TITLE
Bluetooth module reset

### ISSUE THREAD

**Issue by rehannali** [chiteroman/PlayIntegrityFix#259]
I seem to be running into a recurring issue with my Bluetooth module resetting after each update, which results in all paired devices being removed. While the rebooting isn't a problem, I've noticed that my Galaxy products, particularly the watches, struggle to reconnect afterwards. 

To get them to pair again with my S21 Ultra, I find myself having to reset the watch each time. Interestingly, a regular reboot doesn't seem to affect this and I've tested this theory out a few times. Even after updating to 15.8, the issue persists. 

I'm not entirely sure if it's the Bluetooth module resetting or something else causing all paired devices to disconnect after a reboot.

**Comment by norbert-keseru** [comment]
Hi,

The watch issue i think is irrelevant to module.
My wife had the same issue with galaxy watch 6 and oppo find n2 flip. 
The phone is not rooted or modified in any way!

Phone lost watch wearable app opens lime fresh installed.
We had to reset watch ad setup again.
It looks like there is a bug in the watch6 plugin. Ive installed an older version now and it has not lost the watch in last few days yet. Looks promising.

**Comment by rehannali** [comment]
@norbert-keseru 

Hi, You may be right about the plugin as I'm using Watch 5 Pro. if you watch 5 or 6 plugins behaving like this, why do all paired devices get removed instead of the watch.

**Comment by norbert-keseru** [comment]
I did not say it is 100% that. 
It could be the module as well.
But we had that issue with the watch. But the earphones were remained as paired.

**Comment by rehannali** [comment]
> I did not say it is 100% that. It could be the module as well. But we had that issue with the watch. But the earphones were remained as paired.

In my case, everything that was paired got removed not only the watch. Afterwards, it works fine until the next update although if you have normal reboots, etc, works fine.
