### ISSUE TITLE
Magisk 26.4 doesn't support

### ISSUE THREAD

**Issue by Senpaixm1** [chiteroman/PlayIntegrityFix#26]
![Screenshot_2023-11-11-11-59-49-41_785cfb1f0fb0c9a2030c9b38a1c3479a](https://github.com/chiteroman/PlayIntegrityFix/assets/130349632/88417fba-d40f-424a-a289-92890bd221c7)

**Comment by chiteroman** [comment]
I'm using Magisk v26.4 and it's working, I think your Magisk isn't installed correctly.
