### ISSUE TITLE
Unable to change device fingerprint

### ISSUE THREAD

**Issue by MenKlash** [chiteroman/PlayIntegrityFix#261]
I made sure the pif.json was well written and it was in the correct location, but when I try to test my Play Integrity, in Play Store or in a third app party, both are not detecting my new device fingerprint. Instead, they're detecting the original one.

**Comment by VisionR1** [comment]
> I made sure the pif.json was well written and it was in the correct location, but when I try to test my Play Integrity, in Play Store or in a third app party, both are not detecting my new device fingerprint. Instead, they're detecting the original one.

Yeah, is all good, if you pass 2/3 
The spoof Fingerprint is only for DroidGuard, all other processes and apps see the original fingerprint

**Comment by MenKlash** [comment]
Thank you.
