### ISSUE TITLE
Play integrity fails randomly

### ISSUE THREAD

**Issue by Astronxd** [chiteroman/PlayIntegrityFix#265]
Device: OnePlus 9 Pro 5G
ROM: OxygenOS 14
Reproduction: flash play integrity fix and wait
Description: Play integrity fix makes device pass device integrity and basic integrity but after few hours later, the device fails to meet device integrity.

**Comment by markfm62** [comment]
@Astronxd - Was this with pif v15.8?  v15.9 was released just a couple hours ago, appears to be working now for many people. Google appears to have done a new round of banning prints, but the baked-in one in 15.9 is good as of right now)
