### ISSUE TITLE
Version 15.9 cannot work within Kitsune Mask.

### ISSUE THREAD

**Issue by 27161433** [chiteroman/PlayIntegrityFix#268]
Device: mi 14 pro
ROM: hyperos 1.0.32 （Android14）
Reproduction: The latest version 15.9 in Magisk Kitsune (formerly Delta) is not functioning correctly; however, it work normally when using Magisk root and ksu.

**Comment by crok** [comment]
Seems it doesn't work with Alpha either (with lates Shamiko & ZygiskNext).

**Comment by crok** [comment]
Seems it doesn't work with Magisk Alpha either (with latest Shamiko and ZygiskNext - Redmi Note 7 lavender + latest EvoX ROM).

**Comment by balu100** [comment]
It's a shadow hook issue, at least I think

**Comment by crok** [comment]
Perhaps yes, it seems v15.9.1 solved it.
