### ISSUE TITLE
Payback-app not working

### ISSUE THREAD

**Issue by wonkxin** [chiteroman/PlayIntegrityFix#271]
PlayIntegrityFix is the best and only module to get Google Wallet working on my Samsung Galaxy M51. I'm not sure if this module could fix this: but Payback-client-app

https://play.google.com/store/apps/details?id=de.payback.client.android

somehow recognises root although it's on the Magisk Deny List, LSPosed-app is not installed, Magisk-app is renamed and PlayIntegrityFix is installed.

**Comment by mik1011984** [comment]
Try the Shamiko Magisk module. Magisk's built in deny list isn't enough for some apps anymore.

**Comment by wonkxin** [comment]
thanks for the advice.  I have tested Shamiko 0.73 without success as higher versions do not currently work for me as Magisk causes bootloops from v26.2 onwards.  I will remember this note.
