### ISSUE TITLE
The module make my Phone stuck

### ISSUE THREAD

**Issue by xElkomy** [chiteroman/PlayIntegrityFix#272]
This Magisk module causes my phone to freeze on the XOS loading screen.

- Phone Model: Infinix Note 10 Pro
- Android Version: 11
- Magisk Versions Tested: Latest version and 26.2. I experienced the freezing issue on both versions during startup.

**Comment by munirrockin** [comment]
v15.9.1 Bootloop on Xiaomi 13 (fuxi) on factory ROM XiaomiHyperOS 1.0.3.0UMCMIXM Android 14  . Had to revert back to v15.9. 

But v15.9.1 work ok with Xiaomi Mi9T Pro (raphael) factory rom MIUI 12.5.2.0 RFKMIXM Android 11

**Comment by RPSouto** [comment]
Same here.

Poco F5 Pro with HyperOS.
After revert to 15.9 everything is working again.

**Comment by knasiotis** [comment]
Same here miui 14 eu rom, I cant even launch the OS in safe mode. FML

**Comment by mik1011984** [comment]
Remove the module using TWRP's file manager or ADB and your device will boot again.
I'm not sure why you're trying to use this on .EU Roms at all as they incorporate their own fix as found on their source forge page.

**Comment by RPSouto** [comment]
For those with problems you can:

1 - Boot TWRP with fastboot boot twrp.img
2 - Uses safe mode and magisk will disable all modules.

**Comment by chiteroman** [comment]
v15.9.2 released, should fix this issue.

**Comment by Hot12345** [comment]
> TWRP's file manager

How do I remove the module through with TWRP recovery the installed module? Where are the installed modules listed?

**Comment by Hot12345** [comment]
> For those with problems you can:
> 
> 1 - Boot TWRP with fastboot boot twrp.img 2 - Uses safe mode and magisk will disable all modules.

How to disable all the modules in magisk through TWRP?

**Comment by RPSouto** [comment]
> > For those with problems you can:
> > 1 - Boot TWRP with fastboot boot twrp.img 2 - Uses safe mode and magisk will disable all modules.
> 
> How to disable all the modules in magisk through TWRP?

Enter in TWRP.
Advanced > File Manager.
Go to "/data/adb" and delete the folders of the specific magisk module.
Reboot.

**Comment by Hot12345** [comment]
> > > For those with problems you can:
> > > 1 - Boot TWRP with fastboot boot twrp.img 2 - Uses safe mode and magisk will disable all modules.
> > 
> > 
> > How to disable all the modules in magisk through TWRP?
> 
> Enter in TWRP. Advanced > File Manager. Go to "/data/adb" and delete the folders of the specific magisk module. Reboot.

Thanks buddy. 
I can confirm now that the version v15.9 works. After v15.9 phone won't boot in to the ROM Xiaomi Official ROM.

**Comment by knasiotis** [comment]
15.9.3 doesn't fix the problem. EU rom latest MI 11 ultra

**Comment by xElkomy** [comment]
I know I can fix it, by removing the module by the ADB, but I was trying to know if there are any new updates that will resolve this issue to using the playintegritifix, but I use now the last update, and It works perfect for me
