### ISSUE TITLE
SafetyNet not passed

### ISSUE THREAD

**Issue by Dachoni03** [chiteroman/PlayIntegrityFix#276]
I can't get passed SafetyNet on PixelOS custom rom. I'm getting only: MEETS BASIC INTEGRITY

**Comment by GladistonXD** [comment]
The same here

**Comment by VisionR1** [comment]
If you have your own FP, Google have block it lot of FP before 2 days

**Comment by rudolphos** [comment]
Same here "CTS profile match (ctsProfileMatch): FAIL"

**Comment by GladistonXD** [comment]
It is becoming increasingly difficult to find a fingerprint that has not been banned yet, there was a mass ban recently, very few still work, I believe that in the future it will no longer be possible to use this method, I believe that the majority use it for Google wallet, I had the idea of leaving the service offline via host blocking after approval, but after a few days it asks for internet access to continue, in other words, leaving the service offline is also not viable.

**Comment by Dachoni03** [comment]
Sad I'm forced to buy a new phone, like Pixel 8 or S24 with 7 years of support. Good times with custom roms☹️
