### ISSUE TITLE
15.9.3 causing magisk detection

### ISSUE THREAD

**Issue by Tobim6** [chiteroman/PlayIntegrityFix#279]
15.9.3 is causing Magisk detection in Momo and MemoryDetector. 15.9 did not cause detection, I would use 15.9 but it is deleted.
(I think it worked on 15.9 but I'm not sure. It definitely works with 15.8)
![Screenshot_20240303_125239_Momo](https://github.com/chiteroman/PlayIntegrityFix/assets/102646588/47f572f3-ac75-4342-aa6b-ecd7a302aa9c)
![Screenshot_20240303_125223_MemoryDetector](https://github.com/chiteroman/PlayIntegrityFix/assets/102646588/2344e46a-df14-4d66-9a94-004e792fb46b)

OS: OneUI 6.0
KernelSU v0.7.6 (11458)
Device: Samsung Galaxy S20+ (SM-G985F)

**Comment by Tobim6** [comment]
I am not saying its important to hide from Momo. But some banking apps might detect it.

**Comment by xerel89** [comment]
Same here my Banking app is detected the root

**Comment by Tobim6** [comment]
For anyone who wants to fix this (@xerel89), install  15.8, install play integrity next, update fingerprint, uninstall play integrity next (it causes detection)

**Comment by Tobim6** [comment]
Fixed with 15.9.4
