### ISSUE TITLE
I have question, help

### ISSUE THREAD

**Issue by MARTINMD56** [chiteroman/PlayIntegrityFix#28]
![Screenshot_20231111-133911~2](https://github.com/chiteroman/PlayIntegrityFix/assets/150515270/f174aab7-5bab-42af-8fae-80ebd9299ad8)

Can we change this ??
Change to another fingerprint, device detail???

**Comment by chiteroman** [comment]
Well, this was already reported to me in the XDA post but I have no idea why it happens to some people and not to others. For example, it doesn't happen to me. It's quite strange, I couldn't tell you, so most likely there is no solution, we'll just have to deal with it.

**Comment by MARTINMD56** [comment]
Same, before update to latest version, that nothing happen to me.

After update, i get this problem.

**Comment by liyafe1997** [comment]
I also got this device in my Google account's device list. Seems this module replaced the device ID or something with this device?
