### ISSUE TITLE
No device integrity

### ISSUE THREAD

**Issue by non-bin** [chiteroman/PlayIntegrityFix#283]
I'm on 15.9.3, and I've tried probably 20 different PIFs.
I'm on Lineage, and `uname -a` says `Linux localhost 4.14.336-gfe61ffb52659 #1 SMP PREEMPT Thu Feb 8 06:19:35 UTC 2024 aarch64 Android` so I don't think that's the problem

**Comment by blackwind** [comment]
There's definitely something fishy going on right now. The bundled fingerprint works, but won't in a day or two when Google gets to it, and there isn't a single other fingerprint I can find online that passes device integrity. I, too, have been working on this for the past several hours. Is anyone still having success?

**Comment by non-bin** [comment]
You're right, I deleted PIF.json and it's passing, but I'm sure you're right that it'll get blocked

**Comment by VisionR1** [comment]
Yeah, Google block lot of Fingerprint in 29 February.
The 15.9.3 have FP hardcoder inside from Xiaomi.eu

**Comment by Fede2782** [comment]
About 8000 pifs have been banned the 28th of February. Currently Xiaomi.eu pif is working but this story will end soon when we will run out of fingerprints

**Comment by blackwind** [comment]
How is this possible? What about those using phones that actually bear those fingerprints?

**Comment by Fede2782** [comment]
> How is this possible? What about those using phones that actually bear those fingerprints?

Some old phones lost Play Certification but most of them still pass when the bootloader is locked since the ban is only from passing without locked bl

**Comment by non-bin** [comment]
> How is this possible? What about those using phones that actually bear those fingerprints?

I'm just repeating what someone else said, but apparently not. There must be some imperfection in the spoofing method we use.

I'm currently passing device integrity, on Evolution X ROM, Chiteroman, and PlayCurl.
Wallet isn't working but PlayCurl says it can take 24 hours for wallet to work again

**Comment by non-bin** [comment]
I think what we actually need is an open source pay app. It's not like the card company is worried that we'll reverse engineer their app, if they were they would have pulled out of Google pay ages ago.
Is there any reason Google doesn't want it to work other than *toddler voice* "it's my game, I make the rules, and you're cheating!"

**Comment by non-bin** [comment]
> Some old phones lost Play Certification but most of them still pass when the bootloader is locked since the ban is only from passing without locked bl

Do you know why we can't run root with a locked bootloader? So far all I understand is "it doesn't work'

**Comment by Fede2782** [comment]
> > Some old phones lost Play Certification but most of them still pass when the bootloader is locked since the ban is only from passing without locked bl
> 
> Do you know why we can't run root with a locked bootloader? So far all I understand is "it doesn't work"

Because locked bootloader devices want that all the software installed is signed by the OEM. When rooted at least one partition is modified and this would not allow to run with locked bl. Some devices like Google Pixel allow users to run a custom software with or without root even with the locked bootloader by setting a custom signature. Someone should try to pass play certification on a locked Pixel with root

**Comment by non-bin** [comment]
> Someone should try to pass play certification on a locked Pixel with root

I have a pixel 4a and I'd be happy to try if I knew how, do you have any tips on where to start?

**Comment by non-bin** [comment]
> @non-bin I've been using PlayCurl, too and  for the first time in months it won't give me valid fps. I've been given around 10 new fps by now and none of them works.

It's gonna stay broken for a while unfortunately. Anyone have any idea of the next steps? @chiteroman

**Comment by Fede2782** [comment]
> @non-bin I've been using PlayCurl, too and for the first time in months it won't give me valid fps. I've been given around 10 new fps by now and none of them works.

PlayCurl used to use pifs from TheFreeman but all of them have been banned. Now it uses the pif from xiaomi.eu

**Comment by Fede2782** [comment]
> @Fede2782 ...which won't work either, as it seems. This is baaaad.

For me it is working the one of motorola from xiaomi.eu. for obvious reasons i won't share here the fp

**Comment by Fede2782** [comment]
> Is it bearable to ask you how one does get one from this source? I've only done it with playcurl and it's automated there.

I downloaded the apk and extracted the file of the values fps from it. By the way it has been banned right now

**Comment by VisionR1** [comment]
> > Is it bearable to ask you how one does get one from this source? I've only done it with playcurl and it's automated there.
> 
> I downloaded the apk and extracted the file of the values fps from it. By the way it has been banned right now

You mean now is banned the FP Motorola by Xiaomi.Eu ?

**Comment by Fede2782** [comment]
> > > Is it bearable to ask you how one does get one from this source? I've only done it with playcurl and it's automated there.
> > 
> > 
> > I downloaded the apk and extracted the file of the values fps from it. By the way it has been banned right now
> 
> You mean now is banned the FP Motorola by Xiaomi.Eu ?

Yes. For me it is not passing anymore. Until a few hours ago it worked

**Comment by VisionR1** [comment]
> > > > Is it bearable to ask you how one does get one from this source? I've only done it with playcurl and it's automated there.
> > > 
> > > 
> > > I downloaded the apk and extracted the file of the values fps from it. By the way it has been banned right now
> > 
> > 
> > You mean now is banned the FP Motorola by Xiaomi.Eu ?
> 
> Yes. For me it is not passing anymore. Until a few hours ago it worked

For me still pass 2/3, just now test it. Strange

**Comment by non-bin** [comment]
Google pay "contactless setup" says I don't meet security standards, but I've just paid twice and it worked

**Comment by Fede2782** [comment]
> ![markup_1000006553.png](https://private-user-images.githubusercontent.com/123186113/311426012-7303d5c0-b3bb-4a3c-8c16-a40b8d128b42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzQ2OTUsIm5iZiI6MTcwOTk3NDM5NSwicGF0aCI6Ii8xMjMxODYxMTMvMzExNDI2MDEyLTczMDNkNWMwLWIzYmItNGEzYy04YzE2LWE0MGI4ZDEyOGI0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwODUzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzgyZDAyZWJhMzM2MDBkZWE5ZjRmMzA4MDU0YTQyODM5NTcyOTRkZDAzZGNmNTI1MjliNmU2MDkxMDRhZTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sk-7N-cGV24Qwba1xoUv0uHnk4V3Ekddhk4HYJWFujs)
> 
> I just got a valid pass from FP_downloader. It's using a Motorola fp.

Lol, is the same as Xiaomi.eu. it won't last many days

**Comment by rom4ster** [comment]
> > > Some old phones lost Play Certification but most of them still pass when the bootloader is locked since the ban is only from passing without locked bl
> > 
> > 
> > Do you know why we can't run root with a locked bootloader? So far all I understand is "it doesn't work"
> 
> Because locked bootloader devices want that all the software installed is signed by the OEM. When rooted at least one partition is modified and this would not allow to run with locked bl. Some devices like Google Pixel allow users to run a custom software with or without root even with the locked bootloader by setting a custom signature. Someone should try to pass play certification on a locked Pixel with root

That wont work it will change it to self signed which will pass network integrity checks fs
