### ISSUE TITLE
Stuck at boot / TWRP - 15.9.4 - Xiaomi

### ISSUE THREAD

**Issue by w8stin** [chiteroman/PlayIntegrityFix#285]
Hello there,
Sry if it sounds like a double but i only have seen people saying it works for them since v15.9.3.
For me it doesnt.. can't boot with 15.9.4 in xiaomi.eu rom, with Xiaomi Mi 11 Ultra device. It only reboots to TWRP.
Tell me if you need any logs.

And a big thx for your work @chiteroman (and all others contributors of course!) <3

**Comment by lpetflo** [comment]
Same here :( Removing the folder in data/adb/modules did resolve the bootloop, but reinstalling the module got me back into the bootloop.
With 15.9.3 I can't boot into Miui 14.0.13 on Xiaomi Mi 11 Ultra.

**Comment by lpetflo** [comment]
Updated to 15.9.4, but still got the same bootloop problem.

**Comment by kenethc** [comment]
I didn't test v15.9.4 on my Xiaomi Mi 11 Ultra (star).

But after the bootloops on v15.9.2 and v15.9.3, I stuck with v15.8 with custom pif and everything works fine.

**Comment by paveltar** [comment]
> I didn't test v15.9.4 on my Xiaomi Mi 11 Ultra (star) with xiaomi.eu ROM (A13/MIUI 14).
> 
> But after the bootloops on v15.9.2 and v15.9.3, I stuck with v15.8 with custom pif and everything works fine.

I had to remove these two lines from customize.sh file:

/system/product/app/XiaomiEUInject
/system/product/app/XiaomiEUInject-Stub

Flashed via magisk and it made the problem disappear, works great with PlayIntegrityNEXT now.

p.s I did run `adb shell pm disable-user --user 0 eu.xiaomi.module.inject` beforehand to disable default Xiaomi behavior.

**Comment by w8stin** [comment]
> > I didn't test v15.9.4 on my Xiaomi Mi 11 Ultra (star) with xiaomi.eu ROM (A13/MIUI 14).
> > But after the bootloops on v15.9.2 and v15.9.3, I stuck with v15.8 with custom pif and everything works fine.
> 
> I had to remove these two lines from customize.sh file:
> 
> /system/product/app/XiaomiEUInject /system/product/app/XiaomiEUInject-Stub
> 
> Flashed via magisk and it made the problem disappear, works great with PlayIntegrityNEXT now.
> 
> p.s I did run `adb shell pm disable-user --user 0 eu.xiaomi.module.inject` beforehand to disable default Xiaomi behavior.

Nice one, it works with these lines removed :)
I have replaced all the "# Remove conflict apps" section by the v15.8 one (only the part for xiaomi.eu) : 
`
# Remove xiaomi.eu apps

if [ -d "/product/app/XiaomiEUInject" ]; then
    
    directory="$MODPATH/product/app/XiaomiEUInject"
    
    [ -d "$directory" ] || mkdir -p "$directory"
    
    touch "$directory/.replace"
    
    ui_print "- XiaomiEUInject app removed."
fi

if [ -d "/product/app/XiaomiEUInject-Stub" ]; then
    
    directory="$MODPATH/product/app/XiaomiEUInject-Stub"
    
    [ -d "$directory" ] || mkdir -p "$directory"
    
    touch "$directory/.replace"
    
    ui_print "- XiaomiEUInject-Stub app removed."
fi
`
and it works perfectly fine, thx for the tricks 😉

**Comment by lpetflo** [comment]
Removing/Changing these lines seemed to do the trick for me as well. Thank you so much!

**Comment by memehammad** [comment]
marked as completed despite still being an issue? can somebody please help me unbrick my phone? i dont have twrp and i'm not sure which command i have to run to remove this module.

**Comment by kenethc** [comment]
1. Put phone into fastboot
2. With twrp.img in the same folder as your adb/fastboot driver folder,
enter command:

fastboot boot twrp.img

3. Now his will boot you temporarily into TWRP without flashing

4. Go to File Manager, and browse to /data/adb/modules
5. Delete the folder for pif
6. Navigate back to main TWRP screen and then reboot back to system
7. This should boot up your phone normally



*Please excuse any typos or terseness*
