### ISSUE TITLE
A payment application doesn't work

### ISSUE THREAD

**Issue by anyuta1166** [chiteroman/PlayIntegrityFix#286]
Hello.
I have one payment application installed. As far as I understand, this application uses encrypted storage to store its settings, and it uses Android KeyStore to store the key to this storage.
This application doesn't use Play Integrity at all, and it works fine with Kitsune Magisk + Magisk Hide, without PlayIntegrityFix.
But I need PlayIntegrityFix for Google Pay.
The issue is that this application stops working as soon as I enable PlayIntegrityFix. I guess that PlayIntegrityFix breaks Android KeyStore somehow in order to downgrade from hardware to software attestation, and it also breaks this application.
Is there anything that could be done to make this app work with PlayIntegrityFix enabled?

**Comment by chiteroman** [comment]
That should be impossible, PIF only target unstable GMS process...
