### ISSUE TITLE
Pif not applying fingerprint. 

### ISSUE THREAD

**Issue by XxTWMLxX** [chiteroman/PlayIntegrityFix#287]
I have magisk 27 and the 15.9.4 of pif module.

I generated multiple fingerprints with pickaprint.sh and manually copied them to the zip and flashed it also tried leaving in default /data/adb/ location

Devices still detects OEM fingerprint not the new one so I fail integrity. 

Also tried letting pickaprint.sh auto apply the pif.json but even rebooting, device detects OEM fingerprint only. 

Deleting the pif in /data/adb/pif.json and using the current bundled pif.json I pass. But it won't last long as google bans the bundled one quick.

**Comment by dtingley11** [comment]
Similar issue to this?

https://github.com/chiteroman/PlayIntegrityFix/issues/280

**Comment by XxTWMLxX** [comment]
my oem FP doesnt work even unrooted, but im not going to be unrooted anyway. 
the other fp in the text file is one of the pickaprint random ones. 

using currently bundled pif is only way to pass right now. google must of changed anything no way every single print is banned, there are tons in the script.

**Comment by VisionR1** [comment]
> my oem FP doesnt work even unrooted, but im not going to be unrooted anyway. the other fp in the text file is one of the pickaprint random ones.
> 
> using currently bundled pif is only way to pass right now. google must of changed anything no way every single print is banned, there are tons in the script.

Not pass because you have unlocked BL, isn't the root cause the problem not pass.
Even you unroot still can't pass, because must have locked BL to pass
