### ISSUE TITLE
Updating Play Integrity Fix breaks Mindetach

### ISSUE THREAD

**Issue by Lynquid** [chiteroman/PlayIntegrityFix#288]
I use this together with the fingerprint downloader called "Playcurl" (formerly "Play Integrity Next") on my Xiaomi Poco F5 running Evolution X (Android 13). It works perfectly, except wenever I update Play Integrity Fix, Mindetach stops working, and the apps I detached (YT Revanced and one other) get automatically updated. This is particularly strange because I've turned auto updates off for those apps AND auto updates don't even work on my phone, I have to do them all manually (for which, by the way, I'm also seeking a solution). I then have to reinstall the apps and mindetach.
Is this a known bug that happened to other people too, or is it just me? And could this be fixed in an update, or is there anything I can do myself to fix it?
Also, can someone tell me why auto updates briefly work after this module was updated and broke Mindetach? If I just don't have Mindetach installed it doesn't work either btw. Thanks already for your help! :D

**Comment by chiteroman** [comment]
Weird, but mindetach is outdated, try using zygisk-detach: https://github.com/j-hc/zygisk-detach

**Comment by Lynquid** [comment]
> zygisk-detach

I tried that one a while ago and as far as I remember it didn't work, but I'll try it again. Thank you!

**Comment by Lynquid** [comment]
> Weird, but mindetach is outdated, try using zygisk-detach: https://github.com/j-hc/zygisk-detach

Update: I switched to Zygisk Detach and it's so much better than Mindetach. But the most important thing is, that it won't break when updating Play Integrity Fix. Thanks a lot! 😊
