### ISSUE TITLE
CTS Profile fail on One UI 5.1 and microg

### ISSUE THREAD

**Issue by carloanselmini** [chiteroman/PlayIntegrityFix#29]
This module is the best I have ever tried for passing safetynet and play integrity, however, while it works on the same rom setup (rooted samsung stock one ui) with original play services, it does not seem to pass CTS Profile  check on microg no matter what I do, I tried reinstalling the rom many times and use different approaches to hide root like denylist, magisk hide and even shamiko, cts profile seems unbothered, could it be module related or does it depend on my rom?

**Comment by chiteroman** [comment]
No microG support, maybe I will fix in newer versions.
