### ISSUE TITLE
Module makes Google Music match fail

### ISSUE THREAD

**Issue by pannal** [chiteroman/PlayIntegrityFix#290]
Hey,

Thank you for this module.

Unfortunately, when installed, the Google App's Music recognition fails immediately when used (press music recognition button after voice prompt button, immediately says it couldn't find any music). The fork of this module doesn't have this issue.

This is fully reproducible on a Nothing Phone 1, latest A14 firmware.

**Comment by chiteroman** [comment]
Check latest version
