### ISSUE TITLE
15.9.5 doesn't work

### ISSUE THREAD

**Issue by ivanich** [chiteroman/PlayIntegrityFix#291]
With 15.9.5 play integrity is not passed, previous v 15.9.4 version all works. Device oneplus7Pro, crDroid rom 10.2(A14).

**Comment by bober757** [comment]
confirm. OnePlus7, LineageOS21 (A14)

**Comment by chancsy** [comment]
Same here, Poco F3 PE13

**Comment by Madaraxa** [comment]
Same here Samsung a51

**Comment by XYenon** [comment]
Pixel 7 too.

**Comment by e0003** [comment]
Redmi 4X (santoni) Android 13, Sec patch 2023 -Sep-01 had failed CTS profile since 15.9.x until latest 15.9.5

**Comment by gitdine** [comment]
+1
No longer passes basic integrity. Had to downgrade to v15.9.4.

**Comment by starsunyzl** [comment]
Same here, Xiaomi MIX 2s and Samsung S6

**Comment by isakrubin** [comment]
Same, OnePlus 12

**Comment by brock-lesnarr** [comment]
Mine too

**Comment by gu1zm0-1337** [comment]
Same on Samsung S21+

**Comment by brock-lesnarr** [comment]
> Same on Samsung S21+

Use the previous one,thats working

**Comment by poqdavid** [comment]
For me play integrity passes but it fails on the passing SafetyNet

**Comment by chiteroman** [comment]
Try v15.9.6

**Comment by gitdine** [comment]
@chiteroman 
Still failing basic integrity 🙁

**Comment by gitdine** [comment]
> @chiteroman
> 
> Still failing basic integrity 🙁

Nevermind, it actually works, (Magisk app updated it to 15.9.5 instead of 15.9.6 after I downgraded)
Passes device integrity now, thanks @chiteroman 🙂

**Comment by e0003** [comment]
Same issue 15.9.6 failed cts profile. I tried restore back to 14.x. Does not work either. Wonder whats the issue behind..

Mar 18, 2024 9:15:52 PM poqdavid ***@***.***>:

**Comment by e0003** [comment]
My linux string is
"Linux localhost 4.9.227-Jabiyeff-CAF #1 SMP PREEMPT Tue Sep 19 16:58:03 UTC 2023 aarch64 Android"

Hope it helps debug the issue

Mar 18, 2024 9:15:52 PM poqdavid ***@***.***>:

**Comment by e0003** [comment]
How to hexedit string? And edit into what value?

Mar 19, 2024 12:27:40 AM Marcos ***@***.***>:
