### ISSUE TITLE
v15.9.6 CTS Profile Match Failed

### ISSUE THREAD

**Issue by Jyun5978** [chiteroman/PlayIntegrityFix#296]
Magisk
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/25f24cb9-d5a2-4880-9f97-6dfe16014966)
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/d9de9142-f7b7-4e43-a67f-61e5905e0a09)

YASNAC
{
  "apkCertificateDigestSha256": [
    "CFMi+R9OCRrIqon0WdOwQgA4I9aG0m1sYPZuUf5a2ns="
  ],
  "apkDigestSha256": "6eSwd6Ed+f4Pab9sXTvk+hqbA8VFtfdCnYlznf+zIbc=",
  "apkPackageName": "rikka.safetynetchecker",
  "basicIntegrity": true,
  "ctsProfileMatch": false,
  "evaluationType": "BASIC",
  "nonce": "NDY3MjAxNzYtZmE5Mi00NzIwLTk4NDItYWIxNDk4MjZjZTkyCjIwMjQtMDMtMjdUMDI6NTk6MTguMDY5KzA4OjAwClJlZG1pL21hdGlzc2UvbWF0aXNzZToxMy9UUDFBLjIyMDYyNC4wMTQvVjE0LjAuMTUuMC5UTEtDTlhNOnVzZXIvcmVsZWFzZS1rZXlzCjMzCjIwMjMtMTItMDEK",
  "timestampMs": 1711479559033,
  "deprecationInformation": "The app is allowlisted to use the SafetyNet Attestation API until the full turndown: https://g.co/play/safetynet-timeline."
}
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/ffd52bcc-c495-4543-b01c-d1bc293775fc)
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/a94968da-d225-465b-ad14-b7cff4ca2fb1)

----------------------------------

Play Integrity API Checker
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/60b26149-9dcd-4ebd-b50c-2b255c812435)
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/388ff592-9562-4c11-acf8-c2df30fcd8a7)

----------------------------------

SPIC Playinteg.

{
  "accountDetails": {
    "appLicensingVerdict": "LICENSED"
  },
  "appIntegrity": {
    "appRecognitionVerdict": "PLAY_RECOGNIZED",
    "certificateSha256Digest": [
      "_zjHvW5D0vMAQ78JM2p2uWx9XLBnXWGIsg7yiyrP7ec"
    ],
    "packageName": "com.henrikherzig.playintegritychecker",
    "versionCode": "7"
  },
  "deviceIntegrity": {
    "deviceRecognitionVerdict": [
      "MEETS_BASIC_INTEGRITY"
    ]
  },
  "requestDetails": {
    "nonce": "U0Y1cTBUSHJxUnF0RDh4MDNzSXJsYURjMUdiUmpSSWhMb0Z2U2xaUktwbE1qb1NvaHE\u003d",
    "requestPackageName": "com.henrikherzig.playintegritychecker",
    "timestampMillis": 1711479687905
  }
}
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/3b5c448e-21b5-4419-a3cf-97ab695d6510)
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/e102f5a6-ec37-4990-b117-8e848bc16065)

----------------------------------

SPIC SafetyNet

{
  "apkCertificateDigestSha256": [
    "/zjHvW5D0vMAQ78JM2p2uWx9XLBnXWGIsg7yiyrP7ec\u003d"
  ],
  "apkDigestSha256": "DptbkXD9gp0gJo6lxUSvpwb8DfNB29O7WvBnFbl4P9I\u003d",
  "apkPackageName": "com.henrikherzig.playintegritychecker",
  "basicIntegrity": true,
  "ctsProfileMatch": false,
  "evaluationType": "BASIC",
  "nonce": "M2IxYjAwYjgtM2JmMC00MzA3LTgyNmYtMTgyYjRhYTQ1NWFj",
  "timestampMs": 1711479715263,
  "deprecationInformation": "The app is allowlisted to use the SafetyNet Attestation API until the full turndown: https://g.co/play/safetynet-timeline."
}
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/3a9225fd-ac87-480b-94a6-81e6e883e24c)
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/22559124/4cab1df8-27f8-4269-a209-594aebdb67ac)

**Comment by e0003** [comment]
Yes, same to my santoni (redmi 4x) kept failed CTS Profile. Current 19.x still failing even the latest ones.
Tried way back to 14.x also same issue.
It used to work in older version, forgotten which specific ones.
Anyone know what else to do?

**Comment by privacyguy123** [comment]
What does failing CTS profile even mean?

**Comment by e0003** [comment]
Apr 8, 2024 7:31:02 AM privacyguy123 ***@***.***>:

**Comment by privacyguy123** [comment]
How did you fix this?

**Comment by e0003** [comment]
I am hoping you can fix it
It was working fine in older version

Apr 12, 2024 1:07:42 AM privacyguy123 ***@***.***>:
