### ISSUE TITLE
Can you add a feature

### ISSUE THREAD

**Issue by LaplaceTor** [chiteroman/PlayIntegrityFix#3]
Sony video enhancement also fix with Kdrag0n safetynet fix, but safetynet broken after Google's update so I try some other modules to fix it.
Both yours and Displax's just fix the safetynet but video enhancement fix doesn't support yet.
Thank you so much if you can add this feature

**Comment by chiteroman** [comment]
Check v9.5: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v9.5

**Comment by LaplaceTor** [comment]
> Check v9.5: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v9.5

![Screenshot_20231019-203106.png](https://github.com/chiteroman/PlayIntegrityFix/assets/28674126/01b7eaf9-af0c-4d6e-b30e-2dff36203e95)

![Screenshot_20231019-203126.png](https://github.com/chiteroman/PlayIntegrityFix/assets/28674126/b8156348-6e8a-42ef-acf1-f75aa879b34a)


Thank you so much 😊

**Comment by LaplaceTor** [comment]
> Check v9.5: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v9.5

My friend tell me that the new version v9.7/9.8 does not fix it-----thank you for your hard work on it in the last few days, perhaps your new code doesn't support this feature yet, can you put the old version back into release?

**Comment by chiteroman** [comment]
If I add that props few devices will crash...

**Comment by LaplaceTor** [comment]
> If I add that props few devices will crash...

Is it possible to get that feature in another magisk module? Thank you 🙏
People who using Sony Xperia have already fixed it with safetynet fix module for years, but now it cannot bypass safetynet

**Comment by chiteroman** [comment]
It should be fixed in latest release, check "props" version: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v9.8

**Comment by TheSingular** [comment]
Hmm... how about adding code to detect if device is a Sony and set the relevant props depending on that? This way you won't need two different versions.
