### ISSUE TITLE
CTS Profile & Basic Integrity were failed

### ISSUE THREAD

**Issue by PepsiLee2001** [chiteroman/PlayIntegrityFix#30]
Redmi K40
xiaomi.eu 14.0.6.0 (Android 13 TKQ1.220829.002)
Magisk 26.4
LSPosed 1.9.2
PlayIntegrityFix v12.3

safetynet check result：
CTS Profile --> Failed
basic Integrity --> Failed

BUT PlayIntegrityFix downgrade to V9.8，CTS profile & basic Integrity were PASS.

**Comment by chiteroman** [comment]
Did you update to latest rom version which fix the Play Integrity issue? Or are you still using old rom, because it's very interesting than you can pass SafetyNet with it and my old module version.

**Comment by PepsiLee2001** [comment]
Latest rom for K40 is 14.0.8.0, I'm using 14.0.6.0.

**Comment by chiteroman** [comment]
If you remove my module and add all GMS processes to deny list cannot pass SN and PI ?

**Comment by PepsiLee2001** [comment]
I found that it seems that the **ro.build.fingerprint** in xiaomi.eu rom does not match the **ro.build.id** declaration. After I modified the fingerprint by magiskHidePropsConf,

safetynet checker:
  All Pass


Play Integrity API Checker:
  Meets_device_integrity-->pass
  Meets_basic_integrity-->pass
  Meets_strong_integrity-->failed
