### ISSUE TITLE
How to refresh FCM tokens after clear GSF data

### ISSUE THREAD

**Issue by liyafe1997** [chiteroman/PlayIntegrityFix#31]
Once the GSF data is cleared, it will generate a new DeviceID, and seems all the old FCM tokens stopped working. So all the apps are unable to receive FCM push by their previous registered tokens. 

In Google's official FCM document: https://firebase.google.com/docs/cloud-messaging/manage-tokens

It says the token can be invalid, and the apps should refresh the token. So is there any way to manually make the old token invalid, and let the apps register a new token, except clear data/reinstalling the apps (I don't want to re-configure lots of apps)

**Comment by chiteroman** [comment]
I don't know, I didn't know this existed. I'm sorry I can't help you :(

**Comment by liyafe1997** [comment]
> I don't know, I didn't know this existed. I'm sorry I can't help you :(

So in your device your FCM works well after cleared the GSF data?
