### ISSUE TITLE
Clarification on documentation and GMS

### ISSUE THREAD

**Issue by bengalih** [chiteroman/PlayIntegrityFix#32]
Main page here states:

`If you are using Shamiko and have deny list disabled, you must manually add GMS main and unstable processes to hide list or DroidGuard will detect root.`

However there is a bunch of conflicting info in the XDA thread.  It appears that if using the PIF module you do not need to add GMS (or any GApps) to the Deny List.  I also think I saw a post from you stating this and it is confirmed not to be needed by me and other users.

This bit in the docs brings up confusion.  Can you update it to remove or clarify this requirement for use with PIF?

Thanks man!

**Comment by chiteroman** [comment]
I haven't used Shamiko in a while so I don't know if they've done anything about that, I seem to remember that before you had to add the process manually. I'm going to remove it anyway.
