### ISSUE TITLE
 pif.json - a second, unnecessary closing bracket added in v15.9.8?

### ISSUE THREAD

**Issue by crok** [chiteroman/PlayIntegrityFix#321]
Hello,

Isn't [this](https://github.com/chiteroman/PlayIntegrityFix/blame/763607e2f8df152f2c20ec427821a3bb928b4360/module/pif.json#L21
) curly bracket breakes .json format? It introduces a second, unnecessary closing bracket.

**Comment by rayshabh** [comment]
> Hello,
> 
> Isn't [this](https://github.com/chiteroman/PlayIntegrityFix/blame/763607e2f8df152f2c20ec427821a3bb928b4360/module/pif.json#L21) curly bracket breakes .json format? It introduces a second, unnecessary closing bracket.

Everything looks fine. You can validate the json file yourself by copy-pasting the code here [JSONLint](https://jsonlint.com/).
Please close the issue!

**Comment by crok** [comment]
> Everything looks fine.
Oh, I see now.. sry!
