### ISSUE TITLE
15.8.9 failed device integrity check

### ISSUE THREAD

**Issue by sudanking** [chiteroman/PlayIntegrityFix#322]
I use Apatch with OOS14 using OnePlus 12.

Latest update gives me failed device integrity what ever update pif file with curl.
I revert back to the previous version and it works fine.

**Comment by Nitorac** [comment]
Same issue with the same symptoms here on Samsung A54 5G with OneUI 6.0 and Magisk Kitsune R65C33E4F.
Rolled back and it works again.

**Comment by PATAPOsha** [comment]
Works for me on 15.9.7.
I didn't update from 15.1 for a while - do you no more need to find .pf files manually? It just works with this module?

**Comment by asamofal** [comment]
Pixel 7 (AP1A.240305.019.A1),
APatch 10763 (Kernel patch 0.10.7)
Zygisk Next 1.0.5
Play Integrity Fix 15.9.8

```
Labels: [MEETS_BASIC_INTEGRITY]
Build fingerprint: google/panther/panther:14/AP1A.240305.019.A1/11445699:user/release-keys
Brand: google
Device: panther
Model: Pixel 7
```
Play Protect Certification: Device is not certified

I've tried to clear a cache and delete the storage data for: Google Play Services, Google Play Protect Service, Google Play Store. With reboot. Nothing helped. Still doesn't meet DEVICE_INTEGRITY level and Play Protect Certification doesn't pass. 
What I can do else?

**Comment by asamofal** [comment]
> Downgrade to previous version

@Turhvjbufv nope, didn't help. everything is the same =\

**Comment by asamofal** [comment]
Last time switching to [Play Integrity Fork by osm0sis](https://github.com/osm0sis/PlayIntegrityFork) + [playcurl](https://github.com/daboynb/PlayIntegrityNEXT/releases/download/playcurl/playcurl.zip) helped me. I see there's a new version v15.9.9 but I didn't try it yet.
