### ISSUE TITLE
Cts profile not matching on 15.9.8

### ISSUE THREAD

**Issue by Ibbu37** [chiteroman/PlayIntegrityFix#323]
I am on latest oxygen os base android 14 on my one plus open i cannot pass cts profile match and even tried different fps but it meets device integrity...!

**Comment by Lucid-Window** [comment]
Same on the stock ROM on my pixel 8 pro

**Comment by Razib092** [comment]
Same problem on my OnePlus Nord 3 . Release 15.9.8 CTS profile mach, device integrity faill, bug
![Screenshot_2024-05-17-13-53-02-87_710528209a6e8323786b539cad831607](https://github.com/chiteroman/PlayIntegrityFix/assets/129007408/8ba61db9-a623-460c-a889-2679ae2dad9f)
![Screenshot_2024-05-17-13-53-11-10_710528209a6e8323786b539cad831607](https://github.com/chiteroman/PlayIntegrityFix/assets/129007408/6985b9c1-fc79-4ec4-9022-358c2e5a82e5)

**Comment by Zerogoki00** [comment]
Same here on Pixel 7 Pro

**Comment by Dialgatrainer02** [comment]
Same error on pixel 7

**Comment by Suburban-Vampire** [comment]
Another OnePlus 12 user over here, can confirm that 
1-the issue is present on 15.9.8 for me, and 
2-rolling back to 15.9.7 resolved the issue

**Comment by Zerogoki00** [comment]
I tested it with 100% working pif.json and it breaks after update. Pixel 7 Pro
