### ISSUE TITLE
Release 15.9.8 Device integrity faill and cts profile mach

### ISSUE THREAD

**Issue by Razib092** [chiteroman/PlayIntegrityFix#324]
I flashed the latest Play integrity fix 15.9.8 and latest playcurl but still not passing cts profile mach and device integrity faill. Any one have solutions 
![Screenshot_2024-05-17-13-53-11-10_710528209a6e8323786b539cad831607](https://github.com/chiteroman/PlayIntegrityFix/assets/129007408/4696dfab-c1ee-4e7c-a8b2-b80e5287f55e)
![Screenshot_2024-05-17-13-53-02-87_710528209a6e8323786b539cad831607](https://github.com/chiteroman/PlayIntegrityFix/assets/129007408/4905ba50-36c9-471a-a10e-4ae5951c3d4d)
![Screenshot_2024-05-17-17-50-17-12_e3c858dec9480e162968a6ac680e89b1](https://github.com/chiteroman/PlayIntegrityFix/assets/129007408/461f1b44-8829-46a1-913a-dda909b96190)

**Comment by Tomadock** [comment]
Confirmed I am having the same issue. Rolling back to 15.9.7 fixed the issue.

**Comment by Razib092** [comment]
> Confirmed I am having the same issue. Rolling back to 15.9.7 fixed the issue.

Thank you soo much, problem is fix I rolling back 15.9.7 everything is good

**Comment by Razib092** [comment]
Rolling back 15.9.7 all problem solved
