### ISSUE TITLE
US State ID not working

### ISSUE THREAD

**Issue by MulverineX** [chiteroman/PlayIntegrityFix#33]
I was able to setup a credit card, but when attempting to add a state ID I got an error.

![Screenshot_20231112-224039_Google Play services](https://github.com/chiteroman/PlayIntegrityFix/assets/12068027/3ab957fa-09c3-44bc-84bc-5b9bb0e63e14)
![Screenshot_20231112-223959_Google Play services](https://github.com/chiteroman/PlayIntegrityFix/assets/12068027/a6576516-627e-478c-ae02-6fa3f8067906)
[magisk_log_2023-11-12T22.42.19.log](https://github.com/chiteroman/PlayIntegrityFix/files/13331085/magisk_log_2023-11-12T22.42.19.log)

**Comment by MulverineX** [comment]
![Screenshot_20231112-224353_Yet Another SafetyNet Attestation Checker.png](https://github.com/chiteroman/PlayIntegrityFix/assets/12068027/64398772-6808-433a-8fd9-85852b6eef60)

![Screenshot_20231112-224347_Google Play Store.png](https://github.com/chiteroman/PlayIntegrityFix/assets/12068027/59365ed6-694a-4b0b-9461-91591ec223d7)

**Comment by liyafe1997** [comment]
Have you cleared GSF and GMS data?

**Comment by MulverineX** [comment]
@liyafe1997 yes

**Comment by liyafe1997** [comment]
> @liyafe1997 yes

https://play.google.com/store/apps/details?id=com.henrikherzig.playintegritychecker

You can use this app to check is it passed Play Integrity or not.

**Comment by MulverineX** [comment]
Looks like I'm not passing strong integrity.

![Screenshot_20231114-204111_Simple Play Integrity Checker.png](https://github.com/chiteroman/PlayIntegrityFix/assets/12068027/9c9b4a34-5bb2-4eff-9d07-2c70b38d166d)

**Comment by liyafe1997** [comment]
> > [liyafe1997](/liyafe1997)
> 
> I'm on miui china base. Can't find any  GSF and GMS there is some app manager alternative to clear those caches?

Seems you don't really have Google service framework? If you have it you should find it.

**Comment by MulverineX** [comment]
Looks like patching some part of the protocol to spoof a hardware backed integrity response is out of scope for this library unfortunately. Hopefully someone picks up this task soon, even if its done in a really awful way like patching individual apps.
