### ISSUE TITLE
Doesn't meet device integrity 15.9.9

### ISSUE THREAD

**Issue by vasyl91** [chiteroman/PlayIntegrityFix#330]
MEETS_DEVICE_INTEGRITY false
CTS profile match fail 

15.9.9 on Xiaomi Redmi Note 8T

Solved CTS profile match by replacing pif.json with the file that comes from 15.9.7 version but device integrity still glows red.

EDIT: issue with integrity persists after downgrading to 15.9.7
EDIT2: PixelOS

**Comment by non-bin** [comment]
Ditto, I'm on Evolution X and I was passing for a few months without updating, until a few days ago. Last update fixed it, but then it broke again and this latest update didn't help.

**Comment by alpha4041** [comment]
signed custom ROMs are now needed, ask your maintainers if your ROM is signed.
