### ISSUE TITLE
15.9.9 Not passing device Integrity 

### ISSUE THREAD

**Issue by rogergithubbing** [chiteroman/PlayIntegrityFix#331]
Hello,

After upgrading from 15.9.8 using chiron crdroid with Android 13, clearing data from google play services, play store and gms, and rebooting, the device is still not passing the device integrity.

Thanks in advance !

**Comment by dest4590** [comment]
current fingerprint is banned

**Comment by rogergithubbing** [comment]
Thanks; On 15.9.9?

So the only thing we can do is to wait for the next release?

**Comment by dest4590** [comment]
> Thanks; On 15.9.9?
> 
> So the only thing we can do is to wait for the next release?

yes, when there is a new release, the error will be fixed

**Comment by Promptly1432** [comment]
15.9.9 doesn't work for me but the last 5 months all worked well so i thank you for that!

**Comment by rogergithubbing** [comment]
> > Thanks; On 15.9.9?
> > So the only thing we can do is to wait for the next release?
> 
> yes, when there is a new release, the error will be fixed

But... Having seen how google acts, for how long the next version could work, hours? Days? ... Minutes ? 8-/ 

There is not any other way to fix it?

**Comment by MaccabeeY** [comment]
> > > Thanks; On 15.9.9?
> > > So the only thing we can do is to wait for the next release?
> > 
> > 
> > yes, when there is a new release, the error will be fixed
> 
> But... Having seen how google acts, for how long the next version could work, hours? Days? ... Minutes ? 8-/
> 
> There is not any other way to fix it?

see https://github.com/chiteroman/PlayIntegrityFix/issues/329#issuecomment-2132564155
(just a hypothesis, but if helpful...)

**Comment by dandocmando** [comment]
Guys this has already been solved, you need to switch to a signed rom, most roms are only signed with test keys. LineageOS is passing. Maybe someone will find a bypass, maybe not, its more likely the major ROM maintainers will simply start signing the ROMs.

**Comment by dest4590** [comment]
> Guys this has already been solved, you need to switch to a signed rom, most roms are only signed with test keys. LineageOS is passing device integrity. Maybe someone will find a bypass, maybe not, its more likely the major ROM maintainers will simply start signing the ROMs.

Do they?
Their website says if it fails to pass the test, use playintegrity fix. 

![image](https://github.com/chiteroman/PlayIntegrityFix/assets/80628386/d44bbb13-e804-471d-9419-fe9d30cc3cc6)

**Comment by PNKP237** [comment]
> Guys this has already been solved, you need to switch to a signed rom, most roms are only signed with test keys. LineageOS is passing device integrity. Maybe someone will find a bypass, maybe not, its more likely the major ROM maintainers will simply start signing the ROMs.

There's more to that than the ROM being signed with test keys, I'm on LOS A13 on raphael which is signed with release-keys, yet it is not passing DEVICE.

**Comment by rogergithubbing** [comment]
> > Guys this has already been solved, you need to switch to a signed rom, most roms are only signed with test keys. LineageOS is passing device integrity. Maybe someone will find a bypass, maybe not, its more likely the major ROM maintainers will simply start signing the ROMs.
> 
> There's more to that than the ROM being signed with test keys, I'm on LOS A13 on raphael which is signed with release-keys, yet it is not passing DEVICE.

Ahah! Thanks for your clarification... There is too many people on internet that talk as fast as they are able to, to say non-valid answers and to disorient everybody.

I think we need a comprehensive and first-hand explanation about what is going on...

**Comment by PNKP237** [comment]
Disregard that, while the build number says release-keys, the otacerts file contains a testkey. 
Sorry for the confusion!

**Comment by PNKP237** [comment]
Just follow [osm0sis' instructions here](https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/page-796#post-89531433).

**Comment by rogergithubbing** [comment]
Ahah ! Thanks

unzip -l /system/etc/security/otacerts.zip
Archive:  /system/etc/security/otacerts.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     1675  2008-01-01 00:00   testkey.x509.pem
---------                     -------
     1675                     1 file

**Comment by dandocmando** [comment]
> > Guys this has already been solved, you need to switch to a signed rom, most roms are only signed with test keys. LineageOS is passing device integrity. Maybe someone will find a bypass, maybe not, its more likely the major ROM maintainers will simply start signing the ROMs.
> 
> Do they?
> Their website says if it fails to pass the test, use playintegrity fix. 
> 
> ![image](https://github.com/chiteroman/PlayIntegrityFix/assets/80628386/d44bbb13-e804-471d-9419-fe9d30cc3cc6)
> 

Yes it won't pass by default, once you use this module it will pass.

**Comment by dandocmando** [comment]
> Ahah ! Thanks
> 
> unzip -l /system/etc/security/otacerts.zip
> Archive:  /system/etc/security/otacerts.zip
>   Length      Date    Time    Name
> ---------  ---------- -----   ----
>      1675  2008-01-01 00:00   testkey.x509.pem
> ---------                     -------
>      1675                     1 file

Yeah you want a release key, eg: lineage/signing/signing-keys/releasekey.x509.pem 

Then after installing this module you will pass device integrity.

**Comment by chiteroman** [comment]
ROM must be signed with maintainer private key.
