### ISSUE TITLE
Install PIF make lsposed cant open

### ISSUE THREAD

**Issue by oldman20** [chiteroman/PlayIntegrityFix#333]
[log.zip](https://github.com/user-attachments/files/15529226/log.zip)
[log.old.zip](https://github.com/user-attachments/files/15529227/log.old.zip)
I can open lsposed manager without PIF, but when PIF enable, click lsposed shortcut has nothing happen (not force close even)
Please fix it if can, cause lsposed stop development, many thank!
Above lsposed log, i think log.old is lsposed working, and log is lsposed not work, hope can give little help for tracking issue

**Comment by mylogo1024** [comment]
meet too

**Comment by AllenChangMusic** [comment]
Lsposed no longer works on newer versions of Android.
You will have to use other branches that support it as the devs of Lsposed decided to take a hike

**Comment by oldman20** [comment]
> Lsposed no longer works on newer versions of Android. You will have to use other branches that support it as the devs of Lsposed decided to take a hike
I still using android 10, and it work before. I think maybe update of PIF, or ZygiskNEXT maybe related

**Comment by mylogo1024** [comment]
your know, the current devices are all Android 13/14

**Comment by oldman20** [comment]
Thank all! Im looking new fork of lsposed but seem no luck

**Comment by farline99** [comment]
> can suggest any fork?

[here you go](https://github.com/mywalkb/LSPosed_mod)

**Comment by oldman20** [comment]
> > can suggest any fork?
> 
> [here you go](https://github.com/mywalkb/LSPosed_mod)

i tried it before make issue post, same issue, even it not appear in notification bar

**Comment by farline99** [comment]
@oldman20, idk. PixelOS latest, PIF installed, lsposed mod installed, works no problem, checked right now specifically.

**Comment by chiteroman** [comment]
Seems like LSPosed issue...
