### ISSUE TITLE
15.9.9 Device integrity is not passing again. 

### ISSUE THREAD

**Issue by Yasen6275** [chiteroman/PlayIntegrityFix#335]
Just to let you know. Hope fix will come, eventually. ;)

**Comment by Maleficent-Magik** [comment]
On the one hand, I understand Google's desire to ban root because of SMS spam (well, in France we get our databases hacked every 5 minutes, so what's the point? Nop.) and on the other hand, it's quickly becoming a pain, because for certain tasks, root is necessary...

I hope I'll get a new update soon from this dev, who's doing a fantastic job of making it possible to recover RCS despite rooting!

**Comment by herbertwells** [comment]
I'm passing device integrity but RCS isn't working. Connects instantly but chats say "End-to-end encryption isn't available in this conversation"

**Comment by JesseRacine** [comment]
> I'm passing device integrity but RCS isn't working. Connects instantly but chats say "End-to-end encryption isn't available in this conversation"

I have the exact same issue that started today for me.

**Comment by TTVert** [comment]
Yep RCS is borked again.  This is ridiculous google.

**Comment by arifwinahyu** [comment]
hope will fixed soon

**Comment by TTVert** [comment]
> hope will fixed soon

They always fix things quickly.

**Comment by tgice** [comment]
When something like this happens, can I usually be fixed on an individual phone but finding a different fingerprint or whatever it's called to use?  Or do I have that wrong?

Yeah totally sucks with RCS goes out.  I'm also in passing integrity check for now and Wallet still seems to be working.

Boo hiss Google!  Figure out some other way to keep in us secure and also give those of us who want full access to our devices what we want!

**Comment by babyharpsea** [comment]
I hope it's fixed soon. Currently, Wallet is working, but I don't know when it'll stop working, and it's essential for me

The only thing that sucks about rooting is this.

**Comment by dongerlel** [comment]
> I hope it's fixed soon. Currently, Wallet is working, but I don't know when it'll stop working, and it's essential for me
> 
> The only thing that sucks about rooting is this.

Just ditch shitty xiaomi and buy Honor Magic 5 pro or 6. Did the switch and never coming back.

**Comment by joshphillysportsfan1** [comment]
RCS Messaging seems to be working again for me all I did was Flash the May 2024 Update again and then Flashed Magisk again and now RCS Messages are working again on my Google Pixel 8 Pro. Google really does need to stop messing with things though because it's like a Cat and Mouse game with Google and Third Party Developers.

**Comment by rom4ster** [comment]
> On the one hand, I understand Google's desire to ban root because of SMS spam (well, in France we get our databases hacked every 5 minutes, so what's the point? Nop.) and on the other hand, it's quickly becoming a pain, because for certain tasks, root is necessary...
> 
> I hope I'll get a new update soon from this dev, who's doing a fantastic job of making it possible to recover RCS despite rooting!

this is really bad logic. SMS spam can happen without root.

**Comment by rom4ster** [comment]
> > I hope it's fixed soon. Currently, Wallet is working, but I don't know when it'll stop working, and it's essential for me
> > The only thing that sucks about rooting is this.
> 
> Just ditch shitty xiaomi and buy Honor Magic 5 pro or 6. Did the switch and never coming back.

So Does RCS work on your honor phone? That phone has probably the worst notch after crapple.

**Comment by jgallinari** [comment]
It's not even a question of rooted device. I'm in the same boat with LineageOS v21, no root.
I seriously doubt I'll buy an Android again with that kind of sanction from Google...

**Comment by Maleficent-Magik** [comment]
In reality, it is much more complex than we think, and I have doubts that the PIF will be able to work again.  

the thing being that Google bases itself on criteria such as the blatant presence of root, of the unlocked bootloader, but it seems that there are criteria that we do not know. 

 some people are Root with a Custom ROM, others Root with original ROM and still have RCS and Wallet while others only have Root and original ROM yet Wallet works but not RCS ect ect... 

I am certified by Google  , I have Meet Device Integrity Yellow 2 rounds. Wallet works but not the RCS...

**Comment by rom4ster** [comment]
> In reality, it is much more complex than we think, and I have doubts that the PIF will be able to work again.
> 
> the thing being that Google bases itself on criteria such as the blatant presence of root, of the unlocked bootloader, but it seems that there are criteria that we do not know.
> 
> some people are Root with a Custom ROM, others Root with original ROM and still have RCS and Wallet while others only have Root and original ROM yet Wallet works but not RCS ect ect...
> 
> I am certified by Google , I have Meet Device Integrity Yellow 2 rounds. Wallet works but not the RCS...

You are mixing your data. There are numerous things that happen and if you just skim it thats the conclusion you draw. Likely google is banning the xiaomi.eu fingerprint spoof just like last time. The only way to know is for people with custom fingerprints to come forward and tell us what they experience.

Am curious what @osm0sis has to say about it.

**Comment by osm0sis** [comment]
The public print is banned for RCS use, private prints still all work fine. Check the XDA thread where we've discussed it extensively already. 👍

**Comment by DavidBerdik** [comment]
> Check the XDA thread where we've discussed it extensively already and it can't get deleted. 👍

Do you know if this is happening with playcurl-provided prints as well?

**Comment by osm0sis** [comment]
> Do you know if this is happening with playcurl-provided prints as well?

Everybody's using the same public print, for a long while now...

**Comment by DavidBerdik** [comment]
> Everybody's using the same public print, for a long while now...

Understood. Thank you! I did not realize that `playcurl` was giving everyone the same fingerprint.

**Comment by Maleficent-Magik** [comment]
> The only way to know is for people with custom fingerprints to come forward and tell us what they experience.
@rom4ster 

And how are we supposed to make them? If we have to use the pif.json, I've used 2 PIFs and none of them work...

**Comment by rom4ster** [comment]
> > The only way to know is for people with custom fingerprints to come forward and tell us what they experience.
> > @rom4ster
> 
> And how are we supposed to make them? If we have to use the pif.json, I've used 2 PIFs and none of them work...

So this is why the github issue was closed. Just fill in the pif.json with the private fingerprint info. There are tutorials on xda for this.

**Comment by jcgoble3** [comment]
Anyone care to link to such a tutorial or at least say where on xda it is? xda is a massive forum and I don't have the time in my days to hunt blindly through the whole thing - I find the layout of the xda forum confusing. 

(FWIW, I'm not knowledgeable about the gritty details of what's going on here. I'm just a techie user - and software engineer - who would like to keep root primarily for the sake of system level ad blocking and better Tasker functionality without having to sacrifice RCS. I don't even use Wallet on my phone anymore because I have it on my watch now.)

**Comment by rom4ster** [comment]
is it really that hard to google "pif custom fingerprint tutorial xda"

https://xdaforums.com/t/how-to-search-find-your-own-fingerprints-noob-friendly-a-comprehensive-guide-w-tips-discussion-for-complete-noobs-from-one.4645816/

Literal FIRST link.

**Comment by RGBok** [comment]
Just thought this might help. I downgraded my android version to UQ1A.240205.004 (because a certain magisk module wasn't working) but this allows me to send RCS chats now after installing play integrity fix.

**Comment by KikMyaz** [comment]
Okay so I currently have very few private prints for MEETS_DEVICE_INTEGRITY as of today, found by manually iteratively dissecting the stock firmware files. However, peculiarly some seem to only work on an API level 29 device but not the API level 34 (Xiaomi) device.

Some preliminary log checking seems to suggest GMS look for additional props on the newer device. I'm not sure the actual cause though. @osm0sis is there a way to resetprop or undeclare a certain prop in your PIF fork?

**Comment by osm0sis** [comment]
Yeah you can set whatever props you want via json. We've seen certain devices appear more "strict" than others but despite adjusting various prop and field values couldn't figure out exactly what's different that causes the different behavior.

**Comment by NguyenSon2310** [comment]
Hello @osm0sis I really wanna create a custom pif, but I'm stuck with extracting system.img of a samsung device, do you have experience about this.  I have tried to use simg2img, ImgExtractor & packsparseimg, SuperImg_Unpacker
My device is: Samsung Galaxy A25
When I unpack AP file it just has setting.img, and inside setting.img it contains system.img
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/33917382/e7308568-e0f8-4b04-886c-87e35eda1a32)

But when I tried to unpack system.img by the tools above, it didn't work, and I have tried to open system.img by 7zip, it shows like this
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/33917382/fd1c15a2-4b01-4df0-a71f-25d0bc07ea07)

**Comment by osm0sis** [comment]
Nope, and this isn't the place for discussing it, either.

**Comment by NguyenSon2310** [comment]
> Nope, and this isn't the place for discussing it, either. Go search XDA and open a Q&A thread there or something.

Okay, sorry for bothering you

**Comment by chiteroman** [comment]
Should be fixed in latest release
