### ISSUE TITLE
Doesn't pass any of the tests.

### ISSUE THREAD

**Issue by Gleb2372372** [chiteroman/PlayIntegrityFix#336]
![Screenshot_20240612-194724](https://github.com/chiteroman/PlayIntegrityFix/assets/76180186/4a9fc601-e69b-450a-ba73-f399d4320c52)
![Screenshot_20240612-194701](https://github.com/chiteroman/PlayIntegrityFix/assets/76180186/ae5f5bd2-92d9-4f21-a89d-e62e8d24b189)

**Comment by Gleb2372372** [comment]
v15.9.9

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
its been broken for everyone for the past few days ( 2 weeks ? )
Long long long thread about this issue on[ xda forums](https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89560098)

> Expect that RCS will remain broken for old phones, custom ROMs, third part ROMs  and older ROMs ~~indefinitely~~ for a while. So may as well turn off RCS, and pretend that it does not exist. Google wants everyone to buy a new phone, Googles new **Jack Welch-ian** management has made it the new Apple 😞

**Comment by Gleb2372372** [comment]
Ok, then we wait.

**Comment by Gleb2372372** [comment]
I solved the problem it was in LSPosed and in the left apk and did not touch the module in any way.
