### ISSUE TITLE
Google RCS Messaging Doesn't Work

### ISSUE THREAD

**Issue by OliverOil031** [chiteroman/PlayIntegrityFix#338]
![Screenshot_20240615-213228_Yet Another SafetyNet Attestation Checker.png](https://github.com/chiteroman/PlayIntegrityFix/assets/159832793/b0ae098c-5b52-4b32-bca5-52b14eb23bff)

Here is the YASNAC results

**Comment by bynarie** [comment]
RCS doesnt seem to be working for most people it seems right now.

**Comment by titanbubu** [comment]
Anybody find a fix to this yet? By the time apple rolls out with rcs support we will need this feature to be enabled or we will be "that guy" who gives everybody errors trying to send simple texts.

**Comment by bynarie** [comment]
> Anybody find a fix to this yet? By the time apple rolls out with rcs support we will need this feature to be enabled or we will be "that guy" who gives everybody errors trying to send simple texts.

I think we're done for unfortunately.. Nothing wants to play nice with rooted devices anymore.

**Comment by asdfjkluiop** [comment]
> Anybody find a fix to this yet? By the time apple rolls out with rcs support we will need this feature to be enabled or we will be "that guy" who gives everybody errors trying to send simple texts.

I believe osm0sis said that it's just the fingerprint chiteroman is shipping by default which is banned specifically from RCS. Apparently if you use a different fingerprint RCS does work. I haven't personally verified this but I'm more and more tempted to as RCS is the only reason I'm using PIF, I couldn't care less about the other things google bans, I just keep hoping for a new fingerprint as I haven't found the time to figure out building my own. https://github.com/chiteroman/PlayIntegrityFix/issues/335#issuecomment-2155749513

**Comment by chiteroman** [comment]
Sailfish is banned for RCS
