### ISSUE TITLE
Can't pass device integrity with 16.x

### ISSUE THREAD

**Issue by 46620** [chiteroman/PlayIntegrityFix#342]
After flashing any of the 16.x builds, I can only pass BASIC. Removing the module I start passing DEVICE.
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/29524794/7c8aa85d-b0c4-428d-ad9e-58927397a9d9)
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/29524794/f3096403-3ea1-4b94-85dd-b5aacf09bc4f)

When trying with release key, the ROM doesn't pass DEVICE with or without the module.

Evo-X: 9.0
A14
ROM is signed with a testkey

**Comment by BurakSomuncu** [comment]
how did you got v16.1?

**Comment by 46620** [comment]
@BurakSomuncu It's in the telegram group, same with 16.2 which I'm currently testing before updating this.

**Comment by BurakSomuncu** [comment]
@46620 yeah, it's still not working

**Comment by Sedat5665** [comment]
Yes, I have the same problem and it still doesn't go away.

**Comment by BotchedRPR** [comment]
Same for me.

Redmi K70 Pro, x.eu rom, 16.2

**Comment by 46620** [comment]
tested after signing my ROM, I now only pass device and fail everything else.

**Comment by BurakSomuncu** [comment]
> signing my ROM

how do we sign the ROM? or how do we check if the ROM is signed or not.

**Comment by 46620** [comment]
> > signing my ROM
> 
> how do we sign the ROM? or how do we check if the ROM is signed or not.

Ask your maintainer. Check with `adb shell unzip -l /system/etc/security/otacerts.zip`. If it doesn't say `releasekey` then you're most likely not signed.

**Comment by BurakSomuncu** [comment]
it's signed, thanks.

**Comment by 46620** [comment]
After flashing Evolution-X official and this module I can only pass DEVICE and nothing else. Will update the original issue with this information.

**Comment by BenJewell** [comment]
How did you get 16.2? 16.0 is the latest on GitHub here, and in the Magisk repo.

**Comment by BurakSomuncu** [comment]
@BenJewell search for "Play Integrity Fix Telegram" in Google, APK is in the Telegram channel.

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Same here , only passing baskic , CTS profile match = fail

Still No RCS 🥳

**Comment by osm0sis** [comment]
I've yet to see any proof anything but the testkey is banned.

**Comment by osm0sis** [comment]
> > I've yet to see any proof anything but the testkey is banned.
> 
> Users in a ROM group are reporting that that ROMs release keys are failing but maintainer private release keys are not. Can't independently verify it currently however.

More vague hearsay without the official ROM's name and the output of `unzip -l /system/etc/security/otacerts.zip`

**Comment by chiteroman** [comment]
ROM must be signed with a private key from maintainer.
