### ISSUE TITLE
Payback

### ISSUE THREAD

**Issue by Harry8472** [chiteroman/PlayIntegrityFix#343]
Unfortunately payback does not work since the version before the last version.

**Comment by damian-anlauf** [comment]
Yeah, Payback made their root-detection more agressive. I am able to bypass it with Shamiko, even without passing device integrity (the rom I'm using is not yet signed).

There is a XDA thread about this issue, from where I also got my solution: https://xdaforums.com/t/payback-pay-detecting-root.4153749/

**Comment by chiteroman** [comment]
PIF only fixes Play Integrity / SafetyNet.
