### ISSUE TITLE
cts profile match fail

### ISSUE THREAD

**Issue by SpaZ112** [chiteroman/PlayIntegrityFix#344]
Hello!
Im having problem with safenet. I can pass basic integrity, but in cts profile match it fails.
Device: Samsung Galaxy s5 sm-g900f
Os: Lineageos 21
Gapps: Fake gapps nlp ( https://fakegapps.github.io/ ), but I tried also on mind the gapps and other fake gapps packages and without gapps - same result
I tried versions 16.0 and 16.2 - same result
I tried Play integrity fix next ( https://github.com/daboynb/PlayIntegrityNEXT ) - same result
I tried universal safetynet fix ( https://github.com/kdrag0n/safetynet-fix ) - it fails both basic integrity and cts profile match.
I tried lsposed and pixel spoof ( https://github.com/LSPosed/LSPosed https://github.com/RisenID/PixelSpoof ) - lsposed keeps closing

What I consider weird (idk if it's related): I can open netflix and it works fine. I can't login into pokemon go (authentefication issue). On other device with same safetynet results (basic passed, cts failed) netflix yells that my device is not compatibile.

**Comment by buutske** [comment]
Here also not working on Pixel 7, stock and root

**Comment by chiteroman** [comment]
Maybe it's Gapps issue...
