### ISSUE TITLE
Only getting basic

### ISSUE THREAD

**Issue by bynarie** [chiteroman/PlayIntegrityFix#346]
So I'm trying to figure out what's going on. I was getting both device and basic but now I'm only getting basic after installing update 16. I have tried completely removing PIF and reinstalling it. No luck. Do I need to re-install magisk completely?

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Only Basic, CTS fail.
PIF v16.2

**Comment by bynarie** [comment]
I forgot to mention, I was on 15.9 getting device and basic, but RCS isn't working. So I uninstalled chiterlnan/pif, installed osmosis fork, then i was only getting basic. So I uninstalled the osmosis fork and went back to chiteroman pif 15.9 and it was still only giving me basic. So I installed the 16 and then 16.2 update and still only getting basic. I feel like installing the osm0sis fork broke something. I am on magisk 27 with zygisk enabled.

**Comment by MarciX12** [comment]
I have the same problem. I only have basic in 16.0 release and my device have tee so idk what's the problem. Strong is not passing for me lol
![IMG_20240620_085355](https://github.com/chiteroman/PlayIntegrityFix/assets/100400926/a5af5065-6d1c-4254-b98e-ee83ba1f12db)
