### ISSUE TITLE
Can't post strong integrity

### ISSUE THREAD

**Issue by MohamedAliClai** [chiteroman/PlayIntegrityFix#353]
Hi
I flashed the latest PIF 16.0
On POCO F6 MIUI EU
But can't pass strong integrity
Many apps not working 
Instapay
Uber driver
My fawry
And some other apps
Please check my modules and let me know what should I do to pass the strong integrity

![Screenshot_2024-06-20-19-27-28-153_com android settings](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/703296f5-3506-4c4c-aa5b-885a64b789f8)

![Screenshot_2024-06-20-19-10-46-504_com android shell](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/9427c74c-71a8-4c48-9175-77184a7a3d22)

![Screenshot_2024-06-20-19-10-57-052_com henrikherzig playintegritychecker](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/01dbfd7d-3fa6-4655-aeea-2cb246374799)
 
![Screenshot_2024-06-20-19-10-11-493_up mbjeyrzl kgto](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/66bafa67-a732-4b62-a428-29198f71acb9)

![Screenshot_2024-06-20-19-10-59-244_com henrikherzig playintegritychecker](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/d90778df-4bc2-42f2-b5b9-3c71ee353531)

![Screenshot_2024-06-20-19-11-12-402_io github vvb2060 keyattestation](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/5e9a7787-dd45-43e4-a5b1-781fc7998eea)

![Screenshot_2024-06-20-19-11-17-793_io github vvb2060 mahoshojo](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/4b2fd623-ff6c-4a51-a6c9-dfb4fdc02787)

![Screenshot_2024-06-20-19-24-35-636_com godevelopers OprekCek](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/9270b03b-2828-4802-abf0-5807bda0d33b)
![Screenshot_2024-06-20-19-25-52-788_krypton tbsafetychecker](https://github.com/chiteroman/PlayIntegrityFix/assets/101479148/85b847e1-1689-486d-8f43-51f1c045a610)

**Comment by AllenChangMusic** [comment]
You aren't supposed to be able to pass strong integrity

**Comment by MohamedAliClai** [comment]
> You aren't supposed to be able to pass strong integrity

Why ??

**Comment by MohamedAliClai** [comment]
> yes but v16 clearly says so `WORKING TEE = STRONG PASS`

I don't understand this 😞

**Comment by chiteroman** [comment]
Bug was patched, Strong cannot pass with SW keybox :(
