### ISSUE TITLE
Will the default FP (of PIF 16.3) prevent me from getting STRONG?

### ISSUE THREAD

**Issue by tpnonthealps** [chiteroman/PlayIntegrityFix#355]
Do i need a matching fingerprint (PIF.json) correspond to the keybox to have it working? Or just need working keybox (+default PIF.json) and should have STRONG?

**Comment by tpnonthealps** [comment]
I compiled `class.dex` with a valid keybox and it met STRONG (3/3) with FrameworkPatcherGO, but only met 2/3 with `/data/adb/keybox.xml` using the module. 

Since you said your private keybox works well, I'm not sure if it's because you are not using the default fingerprint.

**Comment by TheArtyomMDev** [comment]
no 
keybox dont contain any model specific data
but  i'm not totally  sure
can u send me your keybox?
u may send it by telegram or any other way to keep it private
