### ISSUE TITLE
CTS Profile Match Failed

### ISSUE THREAD

**Issue by solaluset** [chiteroman/PlayIntegrityFix#368]
Hello. Firstly, thank you for this module.

Unfortunately, I started experiencing issues with it:
![Screenshot_20240704-121836090 (1)](https://github.com/chiteroman/PlayIntegrityFix/assets/60041069/e2c4b72b-18df-485e-b0f6-55f98b86b796)

Play Store still shows that the device is certified, though.

Device: Redmi Note 8T
OS: Resurrection Remix 8.6.9 (based on Lineage), Android 10.
PIF version: 16.5

I'm aware of #236, the issue is (probably) not caused by this because I use custom kernel string (and it used to work earlier).

Please let me know if you need any other information.

**Comment by crok** [comment]
Highly doubt that the very old ROM you are using is properly signed with private key - I would bet on this and that's your problem.

**Comment by solaluset** [comment]
@crok thanks for your reply. Did Google start checking for this not a long time ago? Because it was working month ago or so.

**Comment by crok** [comment]
This started like 6..7 weeks ago (very end of May), it's mentioned as the first thing [in the Notes of the module in the README](https://github.com/chiteroman/PlayIntegrityFix?tab=readme-ov-file#note). I suggest to read the README and the [PIF FAQ on XDA](https://xdaforums.com/t/pif-faq.4653307/#post-89302976), too.

**Comment by solaluset** [comment]
Seems like it was indeed an issue with keys. It passes on the latest version, thanks for the help.
