### ISSUE TITLE
Failing to pass safetynet check

### ISSUE THREAD

**Issue by Hellohi3654** [chiteroman/PlayIntegrityFix#37]
OnePlus 7T Pro
Crdroid 9.10
Magisk delta 26301
Play integrity fix 12.3

YASNAC safetynet attestation failing 
Gpay doesn't work
Haven't changed anything in magisk or anywhere else just starting failing 
Was working fine yesterday morning but now the check fails

![Screenshot_20231116-091807_Yet Another SafetyNet Attestation Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/57390764/3bbe110b-8e49-4382-9e98-de1ec51370bb)

**Comment by PapineauD** [comment]
Do once local update and do format data, and all gonna work.

**Comment by Hellohi3654** [comment]
Have tried v12.4 doesn't help
Cleared all the data and caches and stuff as well and rebooted and stuff

**Comment by chiteroman** [comment]
Fixed in latest update.

**Comment by Hellohi3654** [comment]
Thank you
