### ISSUE TITLE
Bootloop after flashing PIF

### ISSUE THREAD

**Issue by heyshaquib** [chiteroman/PlayIntegrityFix#373]
I flashed the latest Beta build v16.6 on my device with KSU and it bootlooped. After removing the module, my phone booted back again just fine. Just to make sure, i flashed V16.5 and it worked fine as well. Just the v16.6 bootloops for some reason.

**Comment by osm0sis** [comment]
Can you try https://github.com/osm0sis/PlayIntegrityFork/actions/runs/10001375019 and see if it has the same issue?
