### ISSUE TITLE
Error, DRM generic plugin in one app, evaluates BASIC, verdict MEETS_DEVICE_INTEGRITY

### ISSUE THREAD

**Issue by asheroto** [chiteroman/PlayIntegrityFix#375]
In a few apps I'm getting issues related to DRM recently. Looks like device evaluates as `BASIC` and has a verdict of `MEETS_DEVICE_INTEGRITY`. Netflix and Hulu work.

CNN gives an error:
![Screenshot_2024-07-13-20-11-10-77_9e84370ed7979ebe37d3b23fcf79bf0c (Phone)](https://github.com/user-attachments/assets/c064908c-6a3d-4b54-b9fd-813416bcec35)

Fox News just spins. History Channel, Netflix, and Hulu appear to work.

![Screenshot_2024-07-15-09-52-46-55_710528209a6e8323786b539cad831607 (Phone)](https://github.com/user-attachments/assets/324c2fa4-8ea0-45fc-ad5e-475c71163af5)

![Screenshot_2024-07-15-09-52-38-55_710528209a6e8323786b539cad831607 (Phone)](https://github.com/user-attachments/assets/7f78287c-6422-4440-ae59-e82c6ce0e7fc)

**Comment by chiteroman** [comment]
When you unlock bootloader you lost L1 Widevine, nothing to do with PIF

You can check Widevine status with this app: https://play.google.com/store/apps/details?id=com.androidfung.drminfo

Locked bootloader (and certified) devices must have L1.

Also, most of Xiaomi phones, don't lose L1 when unlocked, for example, my vayu and duchamp didn't lose it.

**Comment by asheroto** [comment]
Ah, I see. Thanks.
