### ISSUE TITLE
Bootloop after flashing latest stable pif 16.6

### ISSUE THREAD

**Issue by pendi0098** [chiteroman/PlayIntegrityFix#376]
I flash the latest stable pif 16.6 on my realme c3 running on custom rom pixel os a14 qpr2 with may security patch, and the phone stuck on bootloop, revert to 16.5 solve the bootloop issue.

CPU - MTK Helio G70 (arm64-v8a)
Model - realme c3 (rmx2027)
OS - Android 14 QPR2
Security patch - May, 2024

**Comment by chiteroman** [comment]
Try: https://nightly.link/chiteroman/PlayIntegrityFix/workflows/android/main/PlayIntegrityFix.zip

**Comment by JunfXiao** [comment]
> Try: https://nightly.link/chiteroman/PlayIntegrityFix/workflows/android/main/PlayIntegrityFix.zip

Sadly the bootloop issue still persists on my side.😢

Model: Xiaomi 13 Ultra
CPU: Snapdragong 8 Gen 2
OS: HyperOS based on Android 14
Android Patch: 2024-06-01

**Comment by pendi0098** [comment]
> Try: https://nightly.link/chiteroman/PlayIntegrityFix/workflows/android/main/PlayIntegrityFix.zip

Yes, I already download this from your telegram, and same bootloop on pixel os a14

**Comment by victorballester7** [comment]
Hi, @pendi0098  how did you manage to restore the version 16.5? I am stuck in the Google logo (I have pixel os rom with it's default recovery). Thanks!

**Comment by pendi0098** [comment]
> Hi, @pendi0098 how did you manage to restore the version 16.5? I am stuck in the Google logo (I have pixel os rom with it's default recovery). Thanks!

You have to download magisk.zip from official GitHub, then rename that uninstall.zip & flash through recovery, it will uninstall all modules and magisk from your phone, then flash magisk again.

Btw u can flash pixel os boot.img from fastboot also, that should remove the root access but the modules will not gone

So the uninstall,zip method is necessary.

& The issue is fixed finally with 16.7

I just install that.

Thanks chiteroman.
