### ISSUE TITLE
Bootloop After Flashing Latest Stable PIF 16.6

### ISSUE THREAD

**Issue by U-surper** [chiteroman/PlayIntegrityFix#377]
I flashed the latest stable pif 16.6 on my Xiaomi Redmi Note 10 Pro (India) (sweet) running on custom rom pixel os a14(qpr3) with June security patch, and the phone got stuck on bootloop, reverting to 16.5 solve the bootloop issue.

Model:- Xiaomi Redmi Note 10 Pro (India) (sweet)

OS:- A14 (QPR3)

Security Patch:- 5 June

CPU:- Octa-core Kryo 470 (arm64-v8a)
2 x 2.3 GHz + 6 x 1.8 GHz

**Comment by chiteroman** [comment]
Try this version: https://nightly.link/chiteroman/PlayIntegrityFix/workflows/android/main/PlayIntegrityFix.zip

**Comment by U-surper** [comment]
> Try this version: https://nightly.link/chiteroman/PlayIntegrityFix/workflows/android/main/PlayIntegrityFix.zip

Google play services keeps stopping for some reason,also checking play integrity inside playstore it fails with integrity api error.

I will probably stick to 16.5 for now.

**Comment by chankruze** [comment]
For me result is attached below (is it ok) ?

Model: Motorola G84 5G
Android: 14

![Screenshot_20240721-193955](https://github.com/user-attachments/assets/d1dc26c9-b54c-4881-b9ea-812d1843e13b)
![Screenshot_20240721-193957](https://github.com/user-attachments/assets/efdd0515-c37e-4007-b73d-23f56e974844)

**Comment by victorballester7** [comment]
Hi, @U-surper  how did you manage to restore the version 16.5? I am stuck in the Google logo (I have pixel os rom with it's default recovery). Thanks!

**Comment by HattDroid** [comment]
> Hi, @U-surper how did you manage to restore the version 16.5? I am stuck in the Google logo (I have pixel os rom with it's default recovery). Thanks!

Hello,

You would have to go into your custom recovery, whichever you have installed, then put the 16.5 zip on the memory and flash it this way.

**Comment by victorballester7** [comment]
The custom recovery that I have is very simple (PixelOS recovery) and so I am using adb when I have to flash things. So after doing: `adb sideload playintegrity16.5.zip` I get first an error due to signature verification failing and if I continue doing "Install anyway", then the installation exists with error 1. What should I do? Thank you very much for your rapid answer.

**Comment by victorballester7** [comment]
I also tried to do the 
`adb wait-for-device shell magisk --remove-modules`
while opening the android, but nothing is happening anyway... :(

**Comment by HattDroid** [comment]
I don't think you can flash these modules this way, you would need a proper custom recovery like TWRP, OrangeFox and such...
If your bootloader is already unlocked, I would flash a custom recovery and then recover the phone this way. This would not delete any data.
If you bootloader is locked, it's a bit tricky as I don't know an easy way to flash magisk modules, besides maybe pushing and pulling files manually? And the second option of flashing a custom recovery would require you to unlock your bootloader, which means that the phone memory would reset, erasing all of your data.

**Comment by HattDroid** [comment]
If the user data partition is encrypted, typically TWRP will ask you to type in your unlock code/pin to decrypt it. Using /sdcard or /storage/emulated/0 is the preferred location where to put your 16.5 package and flash from.

If somehow it does not work and your user data is not accessible/decrypted, you would still be able to push the 16.5 package on another partition like /tmp and flash from there (it would depend phone by phone). In any case, do not put the package on /system or any protected location, as if your phone still has verified boot enabled, it will fail booting and it could be tricky to fix (depending on phone/rom).

**Comment by victorballester7** [comment]
Hi, I installed twrp and after changing the file system to ext2 and then back to ext4 in order to see and get rid of some errors concerning the data folder and system_root, I get an error `Updater process ended with ERROR: 1`. Do you know how can I solve it?
Thanks!

**Comment by HattDroid** [comment]
I'm not sure if changing file system was a good idea to be honest. Are you still able to see your data as you left it before the bootloop on /sdcard?

About your error, this is a generic error and does not mention the reason behind the failure. How did you transfer the 16.5 package to the phone?

**Comment by victorballester7** [comment]
In `sdcard` I only see a `TWRP` folder and the zip file of play integrity. I transfer it doing
`adb push PlayIntegrityFix_v16.7.zip /sdcard`

**Comment by victorballester7** [comment]
Omg I think I messed up, isn't it? Now, I am stuck on a bootloop in the Xiaomi logo... The google logo of Pixel does not appear anymore...

**Comment by HattDroid** [comment]
Did you have any other file in /sdcard/ or pretty much in the phone user memory before the bootloop?

**Comment by victorballester7** [comment]
No...

**Comment by victorballester7** [comment]
Factory reset is the only solution? At least I have my photos in google-photos... The other things are not that important I think...

**Comment by U-surper** [comment]
> Hi, @U-surper how did you manage to restore the version 16.5? I am stuck in the Google logo (I have pixel os rom with it's default recovery). Thanks!

Hey i did the hard way of removing all magisk modules then reflashing the patched boot image.

**Comment by U-surper** [comment]
So here's what i did

i)i first downloaded only the boot image of the rom i am using,then booted into fastboot and booted from that image.

ii)i enabled usb debugging,opened adb and removed all magisk modules

iii)finally i reflashed the boot image and then downloaded and installed all previous modules one by one,except this one with 16.5.

Maybe there was an easy way to fix this but this is what i did 😅

**Comment by HattDroid** [comment]
Wait before you factory reset, there's still high chances the data is still there, just that it's not showing or simply not mounted.
What is listed as currently mounted partitions in TWRP?
If you /data or /sdcard is not mounted, when you click it to mount it, does TWRP ask you an unlock pin or password?

Also, what @U-surper said just before can also work. I recently thought all my data was gone during a flash, and it was just my boot partition that was messed up.

**Comment by victorballester7** [comment]
As mounted partitions I can select: cache, system, vendor, data, firmware, cust, persiist. But I cannot select USB-OTG.

At any time I have been asked for a password, though I had a fingerprint lock (and therefore a pin password) in my phone.

Ok, I will try the option of @U-surper. I will put here the commands and if you can confirm me before executing, that would be fine! I am sweating like a chicken in the oven...

But where do I find the boot.img? I should extract the lastest build of my rom, say
PixelOS_davinci_xxxxxx.zip (which weights ~2.4 GB) and get the boot.img?

So I download the

**Comment by U-surper** [comment]
> As mounted partitions I can select: cache, system, vendor, data, firmware, cust, persiist. But I cannot select USB-OTG.
> 
> At any time I have been asked for a password, though I had a fingerprint lock (and therefore a pin password) in my phone.
> 
> Ok, I will try the option of @U-surper. I will put here the commands and if you can confirm me before executing, that would be fine! I am sweating like a chicken in the oven...
> 
> But where do I find the boot.img? I should extract the lastest build of my rom, say PixelOS_davinci_xxxxxx.zip (which weights ~2.4 GB) and get the boot.img?

yes only the boot.img file is needed,and make sure its the same rom that is currently installed on your phone.

**Comment by U-surper** [comment]
@chiteroman Hey I Reflashed the 16.7 update u recently released,Everything works like a charm, no bootloops,playintegrity passes with basic and device verdict.I think it is safe to close this issue.Thanks a Lot. :)

**Comment by victorballester7** [comment]
Yes, you can close the issue. My problem is a part. Even if you say that with 16.7 works fine. Whenever I can download the boot.img and try I will keep you updated. Thank to @U-surper  and @HattDroid  for all your help so far!

**Comment by victorballester7** [comment]
OK, bad news... Doing
`fastboot flash boot boot.img`
does not solve the problem of bootloop in the xiaomi logo (not even google logo). Is there any other thing I should do?

**Comment by U-surper** [comment]
> OK, bad news... Doing `fastboot flash boot boot.img` does not solve the problem of bootloop in the xiaomi logo (not even google logo). Is there any other thing I should do before doing a factory reset?

I Followed This 

https://www.reddit.com/r/Magisk/comments/y6qhl8/tutorial_getting_out_of_a_bootloop_caused_by_a/

**Comment by victorballester7** [comment]
It wasn't working for me... At the end I formated data. Now it's working well. Thanks anyway for everything!

**Comment by osm0sis** [comment]
@U-surper are you on latest Magisk 27004? If so can you please try this and see if you still have the same issues?

https://github.com/osm0sis/PlayIntegrityFork/actions/runs/10001375019
