### ISSUE TITLE
PIF conflicts with... magisk?

### ISSUE THREAD

**Issue by xparadoxical** [chiteroman/PlayIntegrityFix#378]
It works fine, but there was this when installing through Magisk Manager
![image](https://github.com/user-attachments/assets/1f2b720b-8601-4f23-b9c5-68aa111c103e)

**Comment by VisionR1** [comment]
No, just detect you have Magisk setup.
Mean the apps cause problems.
![IMG_20240721_183437](https://github.com/user-attachments/assets/350f301d-b35c-41c6-9439-4eb72f13bd57)

**Comment by xparadoxical** [comment]
I see. So a message saying "no conflicting apps were found" would remove any confusion.

**Comment by VisionR1** [comment]
> I see. So a message saying "no conflicting apps were found" would remove any confusion.

Yeah, i get your point.
