### ISSUE TITLE
Failed to pass MEETS_DEVICE_INTEGRITY

### ISSUE THREAD

**Issue by liyafe1997** [chiteroman/PlayIntegrityFix#38]
12.3 and 12.4 both don't work today...
![telegram-cloud-photo-size-5-6246971757156219284-y](https://github.com/chiteroman/PlayIntegrityFix/assets/18359157/e3089e5e-a358-4f4e-89ea-9455b7d35d93)

**Comment by fellowmean5** [comment]
Same

**Comment by liyafe1997** [comment]
Seems Google is doing something today....

> Same

**Comment by MarkusTieger** [comment]
Same, i know it worked today, but now it doesn't

**Comment by MarkusTieger** [comment]
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/77546847/0b49b55f-e9bd-4c97-9438-d655e9dfbb94)
Thx, we appreatiate your help.

But one question, for what is the privating source code? So that google can't fix it?

**Comment by YoussefVIP** [comment]
When will Safety Net be repaired?

**Comment by MarkusTieger** [comment]
It's Play Integrity which does not work. Safety Net should be fine

**Comment by 46620** [comment]
> When will Safety Net be repaired?

Snet is dead, long live play integrity. if you mean the module, asking for ETAs doesn't speed the process up. it'll be fixed when chiteroman updates the module

**Comment by YoussefVIP** [comment]
Everyone is waiting for integrity and the Google store is not approved

**Comment by YoussefVIP** [comment]
Google Store is not supported

**Comment by liyafe1997** [comment]
> ![image](https://github.com/chiteroman/PlayIntegrityFix/assets/77546847/0b49b55f-e9bd-4c97-9438-d655e9dfbb94)
> Thx, we appreatiate your help.
> 
> But one question, for what is the privating source code? So that google can't fix it?

Please check the discussion on XDA.

**Comment by chiteroman** [comment]
Fixed in latest update.

**Comment by vaknin** [comment]
> Fixed in latest update.

![image](https://github.com/chiteroman/PlayIntegrityFix/assets/26764607/f1dc84a9-4026-4083-831b-91e5291612c7)
Thanks a lot, it works!
<3
