### ISSUE TITLE
16.8 fails update

### ISSUE THREAD

**Issue by Shidapu** [chiteroman/PlayIntegrityFix#385]
Heya, 16.8 fails update via magisk. It keeps reverting back to 16.7 after reboot. No errors in install logs.

Magisk 27.0.

![Screenshot_20240724_162328_Settings](https://github.com/user-attachments/assets/e2670698-c103-4977-a3b6-d1ece7638479)

**Comment by Shanayara** [comment]
I think it's actually installing 16.8 but the .zip file incorrectly still refers to 16.7 in module.prop:
`id=playintegrityfix
name=Play Integrity Fix
version=v16.7
versionCode=16700
author=chiteroman
description=Universal modular fix for Play Integrity (and SafetyNet) on devices running Android 8-15
updateJson=https://raw.githubusercontent.com/chiteroman/PlayIntegrityFix/main/update.json
`

**Comment by mintss-zez0** [comment]
i created pull request #384

**Comment by fuzhengqu** [comment]
Same
