### ISSUE TITLE
Newer versions not working (after 16.5)

### ISSUE THREAD

**Issue by sifatefat** [chiteroman/PlayIntegrityFix#390]
I use Xiaomi.eu custom ROM with latest magisk 27.0. The last working version here is 16.5. Newer ones isn't working. 16.6 was only passing basic integrity (not the device one). I am not sure what's causing it. But it's concerning because I may not be able to pass the verdict when google again ban this fingerprint. Please take a look on this matter.

Device: POCO X5
ROM: Xiaomi.eu
Magisk version: 27.0
Android Version: 14
Android Security Patch: June, 2024

**Comment by InfinityAX** [comment]
I'm encountering a similar issue on my Motorola One Action (troika), running the July 22nd, 2024, LineageOS 21 (custom Android 14 ROM) build. I'm also using Magisk 27.0. It fails the SafetyNet CTS profile match and the Play Integery device integrity check. I attached some screenshots to this reply.
![IMG_20240726_210351](https://github.com/user-attachments/assets/34fdd099-9506-4180-aa59-88c68c3c6160)
![Screenshot_20240726-210222_Mal0](https://github.com/user-attachments/assets/f8a72f80-dad4-45af-bbe4-5f0cc1c3ccf8)
![Screenshot_20240726-210229_Mal0](https://github.com/user-attachments/assets/27a0aea6-7f4f-4141-bd23-c4593b6ebe7a)
![Screenshot_20240726-210240_Yet Another SafetyNet Attestation Checker](https://github.com/user-attachments/assets/4db99ca3-132b-4a0d-8290-84a3036c99ea)
![Screenshot_20240726-210248_Play Integrity API Checker](https://github.com/user-attachments/assets/cea1cf72-2e01-40b3-9eef-83339f5f20b4)

**Comment by GoodDrakon4ik** [comment]
Use this (for it help) https://github.com/daboynb/PlayIntegrityNEXT . I think problem last update in fingerprint what already blocked. Play Integrity Next try to find worked fingerprint. Or u can do it manual

**Comment by InfinityAX** [comment]
@GoodDrakon4ik, thanks for the reply. I was about to install the module when an update was released for Play Integrity Fix. Version 16.9 fixed the issue I was experiencing. I wonder if it also has a fix for @sifatefat's device.

**Comment by bphd** [comment]
> Version 16.9 fixed the issue

Still happens in 176
