### ISSUE TITLE
RCS stuck at configuring/veryfing phone number after the 16.6 update

### ISSUE THREAD

**Issue by Sevo9128** [chiteroman/PlayIntegrityFix#391]
Unfournately just a hour or two after installing the RCS update the RCS broke again this time it didn't even say Connected but is stuck at Configuring/Veryfing phone number

**Comment by selfmusing** [comment]
> Unfournately just a hour or two after installing the RCS update the RCS broke again this time it didn't even say Connected but is stuck at Configuring/Veryfing phone number


https://t.me/playintegrityfix/129
