### ISSUE TITLE
That didn't take long.  RCS broken again in google messages

### ISSUE THREAD

**Issue by TTVert** [chiteroman/PlayIntegrityFix#393]
Not much to describe, another day w/ google being difficult.

**Comment by selfmusing** [comment]
![Screenshot_20240801-125207_Messages](https://github.com/user-attachments/assets/f8602dbc-a25e-45a8-b16f-66303d1149f0)


it's just stuck here for me since they banned the last beta fingerprint 😭😭😭😭

@chiteroman any idea how to fix this shit ???

**Comment by TTVert** [comment]
Mine turned on fine.  The issue I had was the typical blocking of RCS texts.  Their last update fixed it again.  It's just a cat and mouse game at this point.

**Comment by e-t-l** [comment]
"typical blocking of RCS texts"?

**Comment by chiteroman** [comment]
Public fingerprints are banned for RCS.
