### ISSUE TITLE
After update 8.6 i can't access phone's internal storage

### ISSUE THREAD

**Issue by IAMOTAKU9** [chiteroman/PlayIntegrityFix#4]
![IMG_20230923_192721_723](https://github.com/chiteroman/PlayIntegrityFix/assets/87329950/99e0f197-190d-433f-b28c-4519544b7004)
just like what happen in that photo
and that happened since 8.5version,when I boot the phone into desktop,system media start crashing,and sometime I can fix it by direct reinstall Magisk,but after I install 8.6 today,the phone start random reboot,after I disable the module phone finally become normal,so I rollback to 8.4version,hope you can fix this
and these are my phone's system version and Play Store/GMS version
![Screenshot_20230923-195541](https://github.com/chiteroman/PlayIntegrityFix/assets/87329950/2733cbac-77e8-4af4-9be2-f896a88b5be3)
![Screenshot_20230923-194225](https://github.com/chiteroman/PlayIntegrityFix/assets/87329950/70ee0c8e-35f4-4f64-9854-f272005e65f3)
![Screenshot_20230923-194255](https://github.com/chiteroman/PlayIntegrityFix/assets/87329950/9bc56d0c-293e-411d-bea0-b3329893d6c5)

**Comment by chiteroman** [comment]
[PlayIntegrityFix.zip](https://github.com/chiteroman/PlayIntegrityFix/files/12709193/PlayIntegrityFix.zip)
Try this version

**Comment by IAMOTAKU9** [comment]
sorry for the late reply,after about one day with your new version,my phone seems normal for now,there's no reboot and internal storage is normally accessible,thanks for you work
