### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by 46620** [chiteroman/PlayIntegrityFix#41]
Due to releases and source being nuked, I'm now stuck with an update option in Magisk but can't update. Could you repush 12.3 even if it's not fully working yet?
![Screenshot_20231116-112917_M@gisk](https://github.com/chiteroman/PlayIntegrityFix/assets/29524794/7c1c2320-a69d-4405-932a-3459558dfdc4)
![Screenshot_20231116-112922_M@gisk](https://github.com/chiteroman/PlayIntegrityFix/assets/29524794/63406aa4-55cd-489c-ba30-4e42ebe0e324)
![Screenshot_20231116-112928_M@gisk](https://github.com/chiteroman/PlayIntegrityFix/assets/29524794/b90e353f-42ae-4dc9-a2b2-f7bfe9bf75c2)

**Comment by MarkusTieger** [comment]
I still have the zip file for 12.3 on my phone. One second

**Comment by MarkusTieger** [comment]
[PlayIntegrityFix_v12.4.zip](https://github.com/chiteroman/PlayIntegrityFix/files/13380226/PlayIntegrityFix_v12.4.zip)
[PlayIntegrityFix_v12.3.zip](https://github.com/chiteroman/PlayIntegrityFix/files/13380227/PlayIntegrityFix_v12.3.zip)

**Comment by zgfg** [comment]
As simple as that - open module.prop at /data/adb/modules/PlayIntegrityFix

and upgrade your versionCode to 123 (as if you already jave v12.3 installed)

Save file and reopen Magisk Modules tab, it won't bother you to update

When dev releases versionCode 124, your 123 will be lower and Magisk will offer you to update

**Comment by snd0cff** [comment]
I installed 12.4 from above comment, but google pay still not work(of course google play services was cleared)

**Comment by MarkusTieger** [comment]
> I installed 12.4 from above comment, but google pay still not work(of course google play services was cleared)

Tipp: Read the readme
Theres already been worked on and an open issue: https://github.com/chiteroman/PlayIntegrityFix/issues/38

But the discussion is mostly on xda: https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/page-102

**Comment by chiteroman** [comment]
Fixed in latest update.

**Comment by kartikmodi** [comment]
> Fixed in latest update.

It worked for me.
