### ISSUE TITLE
Set sys.oem_unlock_allowed to 0

### ISSUE THREAD

**Issue by axelkar** [chiteroman/PlayIntegrityFix#414]
It's one more detection vector for apps! I have the prop on my OnePlus Nord CE.

Note: this will likely disable `Allow OEM unlocking` in developer settings: https://xdaforums.com/t/oem-unlocking-greyed-out.4246725/

Btw, does PIF use my device's "original fingerprint" by default? If I upgrade to a device that has support for STRONG integrity, can I use e.g. my old device's fingerprint? Will it make all of Find My Device think my phone is not what it is?

**Comment by Endeavourl** [comment]
I see this `sys.oem_unlock_allowed=1` on Pixel 6 Pro as well.

**Comment by yoshimo** [comment]
does being able to unlock the bootloader and changing the recovery already trigger apps?
I thought you had to root the devices first.

**Comment by axelkar** [comment]
> does being able to unlock the bootloader and changing the recovery already trigger apps? I thought you had to root the devices first.

I don't know of any apps that currently read this but this can be a detection vector. All apps should check both for an unlocked bootloader and root, since you don't need root to e.g. cheat in games. You can just modify some framework stuff.
