### ISSUE TITLE
This phone can't be set up to use tap to pay.

### ISSUE THREAD

**Issue by defalt2003** [chiteroman/PlayIntegrityFix#42]
Hello I have been having issues with trying to get the Integrity Fix working again after resetting my phone due to a boot loop and I have reinstalled magisk, then I have also installed the Integrity Fix and its BASIC but I can't add my card so I am unable to use google wallet/ pay

**Comment by 46620** [comment]
the modules broken currently, check the readme

**Comment by chiteroman** [comment]
Fixed in latest update.
