### ISSUE TITLE
Not Working on Xiaomi

### ISSUE THREAD

**Issue by fouwaru** [chiteroman/PlayIntegrityFix#421]
Installed it Like Normal, enabled Zygisk and Enforce Denylist, but No luck.

My Phone: Redmi Note 12 Pro 5G with HyperOS 1.0.7.0 UMOMIXM

**Comment by fifi501** [comment]
My Mi 13 pro with hyper os 1.0.7.0 i use magisk alpha 270007, zygisk next and play intigrity, shamiko 1.1.1 and trickystore 1.1.3. all work fine. Importanr deinstall previous play intigrity before instsll 1.7.5. all fine after.

**Comment by TomHedwig** [comment]
I met the same problem on Xiaomi 13 EEA with Magisk 27.0 and Zygisk on.

The following figures are the result of Play Integrity Check in Google Play.

![Screenshot_2024-09-16-22-26-53-630_com.android.vending~2.jpg](https://github.com/user-attachments/assets/cd71762e-0c44-4dcf-9e66-ccbf9e4d2061)

![Screenshot_2024-09-16-22-26-43-123_com.android.vending~2.jpg](https://github.com/user-attachments/assets/7bbb42bf-3de9-4c4d-989c-1a2b34dd9630)

**Comment by KhanhNguyen9872** [comment]
> Installed it Like Normal, enabled Zygisk and Enforce Denylist, but No luck.
> 
> My Phone: Redmi Note 12 Pro 5G with HyperOS 1.0.7.0 UMOMIXM

I'm using Mi 11 Lite 5G with HyperOS CN 1.0.12.0 (KernelSU or APatch work same), install PlayIntegrityFix with PIFS China and it passed all without any problem.

**Comment by chiteroman** [comment]
No logs = no help
