### ISSUE TITLE
安装时会检测zygisk，但是对于magisk来说，检测的不是zygisk的开关状态

### ISSUE THREAD

**Issue by daxiaamu** [chiteroman/PlayIntegrityFix#423]
首次安装完magisk，打开zygisk开关，此时安装[PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix)17.4会提示没有开启zygisk。需要重启设备后，才能正常安装[PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix)。猜测[PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix)检测的是Zygisk进程。

这样会导致多重启一次手机。

建议通过magisk --sqlite "SELECT value FROM settings where key='zygisk';"  来查询Zygisk开关的状态。

**Comment by chiteroman** [comment]
Done, thanks for the idea 👍
