### ISSUE TITLE
some issues on lineageos

### ISSUE THREAD

**Issue by long-crypto** [chiteroman/PlayIntegrityFix#424]
i have checked your service.sh, you set resetprop_if_diff for some props but lingageos seems not have these props. so, i have to set resetprop ro.boot.flash.locked 1
resetprop ro.boot.verifiedbootstate green
resetprop ro.secureboot.lockstate locked
resetprop ro.boot.vbmeta.device_state locked again to bypass nativetest detection. can you add these for custom rom? not resetprop_if_diff but resetprop. thank you!

**Comment by long-crypto** [comment]
so, -z "$CURRENT"  Checks if CURRENT is empty. If it is empty, this condition is true. for lineageos, it is empty. so it will not do "resetprop" this command. but nativetest check this prop.
before i filled resetprop after service.sh conventional tests show 11, After it show 10.  i assumed the first 1 for check custom rom. so i ignored it.

**Comment by chiteroman** [comment]
If the props don't exist, why do you want to create them? Also, not a PIF issue.
