### ISSUE TITLE
Installed it Like Normal, enabled Zygisk and Enforce Denylist, but No luck.

### ISSUE THREAD

**Issue by cambierguillaume** [chiteroman/PlayIntegrityFix#425]
Installed it Like Normal, enabled Zygisk and Enforce Denylist, but No luck.

My Phone: Redmi Note 12 Pro 5G with HyperOS 1.0.7.0 UMOMIXM

_Originally posted by @fouwaru in https://github.com/chiteroman/PlayIntegrityFix/issues/421_
All magisk is broken when update play integrity after need too reinstall the phone no rolback work uninstall play integrity no work only reinstall the room of the phone 7 xiaomi broken like that I can confirm issu ![image](https://github.com/user-attachments/assets/6f86fec6-5289-4c60-b13a-ff96d117ce23)

All

**Comment by chiteroman** [comment]
Zygisk is disabled... Maybe it crashed. Also, no logs = no help.

**Comment by cambierguillaume** [comment]
How can I have logs of zygisk

**Comment by Harry8472** [comment]
Same problem here
