### ISSUE TITLE
I will flash play integrity v13 but Gpay don't working 

### ISSUE THREAD

**Issue by ganyask12** [chiteroman/PlayIntegrityFix#44]
I am follow all this steps

Clear Google Wallet cache.
Clear Google Play Store cache.
Clear GSF (com.google.android.gsf) data and cache.
Flash my module in Magisk/KernelSU (if you already have my module, just ignore this step)
Then reboot device and should work. Also some users recommend to clear GMS data and cache but for me it wasn't necessary.

Xiaomi mi 11 t pro. Help me please.
![Screenshot_2023-11-17-00-38-39-576_gr nikolasspyr integritycheck](https://github.com/chiteroman/PlayIntegrityFix/assets/54396881/ec81ea59-2177-47dc-b255-49cdc25032f3)

**Comment by Zzz212zzZ** [comment]
Same questions here. Even using the v13 plugin doesn't work.

**Comment by nyakze** [comment]
This is the checker api limit, not the module's fault.
To check if the module is working:
1. Go to Google Play Store
2. Tap on your avatar, open settings
3. In about, tap on the version number 6 times to enable developer options
4. Go to general - development options - check integrity
5. You should see MEETS_DEVICE_INTEGRITY there

**Comment by Zzz212zzZ** [comment]
> This is the checker api limit, not the module's fault. To check if the module is working:
> 
> 1. Go to Google Play Store
> 2. Tap on your avatar, open settings
> 3. In about, tap on the version number 6 times to enable developer options
> 4. Go to general - development options - check integrity
> 5. You should see MEETS_DEVICE_INTEGRITY there

Thank you for such detailed explanation! It's true this should be the fault of Integrity checker, instead of the module's!

**Comment by nyakze** [comment]
> Thank you for such detailed explanation! It's true this should be the fault of Integrity checker, instead of the module's!

The module doesn't have any checkers. You're using a third-party app. 
There are others:
Simple Play integrity checker
TB Checker
Play integrity API checker
Etc
