### ISSUE TITLE
v17.7 fails on Magisk 28.0

### ISSUE THREAD

**Issue by Error504TimeOut** [chiteroman/PlayIntegrityFix#444]
It always worked fine but since I think around 27006 both Play Integrity and SafetyNet fail. After updating to the stable 28.0 and reinstalling the module, the results are the same (see Screenshots). I'm running LineageOS 21 on rosemary using the last official build available.

![markup_1000012535.png](https://github.com/user-attachments/assets/1da531e7-1300-4c21-8cc1-580d222ec811)

![markup_1000012536.png](https://github.com/user-attachments/assets/0ca91ab8-b348-40c7-abe3-13d7c0a957ef)

**Comment by HighError** [comment]
Magisk 28001 (070719db) everything works

**Comment by fifi501** [comment]
also for me Magisk 28001 all works fine with 1.77

**Comment by Error504TimeOut** [comment]
even after a reinstall, the results are the same. very weird.
