### ISSUE TITLE
Confusing thing

### ISSUE THREAD

**Issue by mhnugr** [chiteroman/PlayIntegrityFix#45]
In app play intregity shows this 
![Screenshot_20231117-062257_Play Integrity API Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/151096119/153ed3cf-4d80-47d1-b119-dd0e5b5f10c7)

But in the TB checker app different results
![Screenshot_20231117-062243_TB Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/151096119/8bdd7281-1000-4a53-ae29-2244788d1754)

I use v13

**Comment by liyafe1997** [comment]
It is passed as the TB checker shows. The problem with your first screenshot is not your problem, its the app's problem, mostly like it run out of Google's API calling times.

**Comment by mhnugr** [comment]
> It is passed as the TB checker shows. The problem with your first screenshot is not your problem, its the app's problem, mostly like it run out of Google's API calling times.

Maybe this is just a problem with the app

**Comment by chiteroman** [comment]
https://developer.android.com/google/play/integrity/setup#increase-daily
