### ISSUE TITLE
Integrity check not passing

### ISSUE THREAD

**Issue by Hellohi3654** [chiteroman/PlayIntegrityFix#46]
OnePlus 7t pro
Magisk delta 26301
Crdroid android 13
Latest V13 of integrity module
Tried to clear cache of Google wallet Google play store
Cleared data and cache of Google services framework
Cleared cache of gms 
Rebooted tried removing and reinstalling module 
Still not passing

Checked in Google play store itself as well 

![Screenshot_20231117-111514_TB Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/57390764/5f8826f6-917f-478b-9c91-5f00c3c578c7)

**Comment by chiteroman** [comment]
If you fail BASIC, something in your setup is wrong... DroidGuard is detecting root or injection.

**Comment by PapineauD** [comment]
> OnePlus 7t pro Magisk delta 26301 Crdroid android 13 Latest V13 of integrity module Tried to clear cache of Google wallet Google play store Cleared data and cache of Google services framework Cleared cache of gms Rebooted tried removing and reinstalling module Still not passing
> 
> Checked in Google play store itself as well
> 
> ![Screenshot_20231117-111514_TB Checker](https://user-images.githubusercontent.com/57390764/283630628-5f8826f6-917f-478b-9c91-5f00c3c578c7.png)

You need to do format data, cuz i see you have RESTORE_TO_FACTORY_ROM issue

**Comment by Hellohi3654** [comment]
> If you fail BASIC, something in your setup is wrong... DroidGuard is detecting root or injection.

Yeah sorry seems like my rom had an issue

**Comment by Hellohi3654** [comment]
> > OnePlus 7t pro Magisk delta 26301 Crdroid android 13 Latest V13 of integrity module Tried to clear cache of Google wallet Google play store Cleared data and cache of Google services framework Cleared cache of gms Rebooted tried removing and reinstalling module Still not passing
> > Checked in Google play store itself as well
> > ![Screenshot_20231117-111514_TB Checker](https://user-images.githubusercontent.com/57390764/283630628-5f8826f6-917f-478b-9c91-5f00c3c578c7.png)
> 
> You need to do format data, cuz i see you have RESTORE_TO_FACTORY_ROM issue

No
