### ISSUE TITLE
[ pixel 8 - device integrity fail ]

### ISSUE THREAD

**Issue by Aarqw12** [chiteroman/PlayIntegrityFix#47]
![Screenshot_20231117-013316](https://github.com/chiteroman/PlayIntegrityFix/assets/38363978/dc116cfb-cb19-46c3-a1b2-20b7d5f95f0c)
![Screenshot_20231117-013028](https://github.com/chiteroman/PlayIntegrityFix/assets/38363978/0674ef3e-eced-4d43-9f00-ead630e78945)

Device : pixel 8 latest stock rom 

Bootloader : relocked - kernelsu resigned 

Using zygisk next + v13 play integrity fix 

Device integrity : NO

**Comment by amteza** [comment]
@Aarqw12 Give it some time, it happened to me and it started working after a few minutes. Same like you Pixel 8 Pro, KSU with resigned with my certs and bootloader locked.

**Comment by Aarqw12** [comment]
> @Aarqw12 Give it some time, it happened to me and it started working after a few minutes. Same like you Pixel 8 Pro, KSU with resigned with my certs and bootloader locked.

More 10hours After and reboot its still no pass... Its no that

**Comment by chiteroman** [comment]
I don't know why this happen... Very weird.

**Comment by liyafe1997** [comment]
Have you cleared the data of Google Play Service?

**Comment by Aarqw12** [comment]
> Have you cleared the data of Google Play Service?

Yes I will cut all process Google and reformate all data Google for see

**Comment by Hamood111** [comment]
me too I'm kernelsu user I tried on ksu it's not working but guess what it's working on alpha with built in zygisk I think the problem in zygisk next module or something in my kernel build only one time works on ksu but stays for few moments then Fall again I had to go back to alpha I can't live with broken safetynet by the way Play integrity api checker last night wasn't working but now before 5 meant to go it's come back to work again I think like some of guys here said it has something about time maybe today I will go back to ksu and trying again

**Comment by chiteroman** [comment]
Could it be that by having the bootloader locked with your own keys DroidGuard is detecting it somehow?
It's quite strange.

**Comment by Aarqw12** [comment]
> Could it be that by having the bootloader locked with your own keys DroidGuard is detecting it somehow? It's quite strange.

I have reformated and fixed for basic. I presume even in relocked strong still no possible ...

**Comment by amteza** [comment]
> Could it be that by having the bootloader locked with your own keys DroidGuard is detecting it somehow? It's quite strange.

No, no tiene nada que ver. Yo también tengo el bootloader locked y firmado con mis propias keys. Y funciona perfectamente. ¿Puedo preguntar cómo pasas STRONG?

**Comment by Aarqw12** [comment]
> > Could it be that by having the bootloader locked with your own keys DroidGuard is detecting it somehow? It's quite strange.
> 
> No, no tiene nada que ver. Yo también tengo el bootloader locked y firmado con mis propias keys. Y funciona perfectamente. ¿Puedo preg

Presumo que actualmente no es posible el STRONG incluso con el bootloader bloqueado. Lo siento, no he eludido el STRONG XD."

**Comment by amteza** [comment]
¡Ja! Eso tiene más sentido. Bueno, ye lo que hai. 😉
