### ISSUE TITLE
PIF 18.0 NOT WORKING

### ISSUE THREAD

**Issue by M3551** [chiteroman/PlayIntegrityFix#480]
Like the description, here is my modules and logs
[magisk_log_2024-11-18T08.28.21.log](https://github.com/user-attachments/files/17793263/magisk_log_2024-11-18T08.28.21.log)
![Screenshot_2024-11-18-08-24-59-685_rikka safetynetchecker](https://github.com/user-attachments/assets/200cc216-17da-4bd7-81dd-4ae2b9c85955)
![Screenshot_2024-11-18-08-25-06-990_ua odmtvbrfztr](https://github.com/user-attachments/assets/550285c2-23b2-42ae-ac57-5d1701631367)
![Screenshot_2024-11-18-08-25-12-762_ua odmtvbrfztr](https://github.com/user-attachments/assets/856d7b34-1d44-4fca-a2db-95f83188dc42)
![Screenshot_2024-11-18-08-25-17-644_ua odmtvbrfztr](https://github.com/user-attachments/assets/76828bf7-674e-4d65-9fb6-80eb2b7e4100)

**Comment by paladin4fan** [comment]
Same here on Pixel 9 Pro.
Neither working with nor without trick store.
Attestation passed. But Play Integrity only fit basic pass.

**Comment by JingMatrix** [comment]
The same at Pixel 6 with Android 15 QPR 2

**Comment by osrott61-gh** [comment]
Samsung seems to be fine (n20,s20,n8)

**Comment by chiteroman** [comment]
Remove TSupport Advance, Shamiko, Denylist and try again.

**Comment by u3l6** [comment]
Same here

**Comment by NikkaGames** [comment]
> Same here

Had same issue on RedMagic 8 Pro (OS9 9.0.12) when I had TrickyStore, disabled it and PIF started to work after reboot.

**Comment by gladykov** [comment]
Works on ZenFone 9 with Android 14: PIF + playcurl_NEXT

Tested with YASNAC

**Comment by Noslen004** [comment]
It's working very well for me![Screenshot_20241118_183052_TB Checker.png](https://github.com/user-attachments/assets/44fe04fb-1c88-4e1f-b3c0-ce62f5de51c0)

**Comment by alphapuggle** [comment]
v18 is working fine for me. RCS, wallet, and device all pass. Pixel 8 Pro. I don't have anything that modifies play integrity other than PIF installed

**Comment by M3551** [comment]
> Remove TSupport Advance, Shamiko, enable Denylist and try again.

thank you for your support as always, you'll be always the goat in our community. Just removing Tsupport passed my play integrity 
![Uploading Screenshot_2024-11-19-21-44-07-825_rikka.safetynetchecker.jpg…]()
