### ISSUE TITLE
Integrity Failing

### ISSUE THREAD

**Issue by Absarock** [chiteroman/PlayIntegrityFix#484]
Until recently, I didnt need Playcurl to pass integrity check. But all of a suddent even with playcurlnext, the integrity checks are failing. I am unable to use google wallet.

- Magisk KS 27001
- Pixel 8 Pro, rooted with magisk
- Android Build: 15 (AP41.240925.009) stock

![WhatsApp Image 2024-11-25 at 11 27 19_25ba1798](https://github.com/user-attachments/assets/f1b39d27-1ee6-4e2c-82e2-facbe451e0f4)
![WhatsApp Image 2024-11-25 at 11 27 19_a5651f54](https://github.com/user-attachments/assets/073ef31d-e6a7-4c69-bed7-dfd0b78be9cc)
![WhatsApp Image 2024-11-25 at 11 27 19_b47f6dba](https://github.com/user-attachments/assets/0446cf07-09fe-48dd-8bc3-3a36702e78fb)

**Comment by Absarock** [comment]
Turning off Lsposed mod 1.9.3 has fixed the integrity from failing

**Comment by mirh** [comment]
So you can close this?

**Comment by Absarock** [comment]
Oh sorry. I thought only mods could do it.

**Comment by Absarock** [comment]
Solved
