### ISSUE TITLE
Error getting token from Google 

### ISSUE THREAD

**Issue by Bbonee77** [chiteroman/PlayIntegrityFix#49]
"The calling app is making too many requests to the API and hence is throttled.

This shouldn't happen. If it does please open an issue on Github" 
the message I've got when API checking. Payments wasn't working, but when I deleted your module from magisk it have worked. Thank you

**Comment by buihien224** [comment]
https://github.com/herzhenr/spic-android

use this app

**Comment by Bbonee77** [comment]
> https://github.com/herzhenr/spic-android
> 
> use this app

**Comment by Bbonee77** [comment]
> https://github.com/herzhenr/spic-android
> 
> use this app

![Screenshot_20231117-093612_Simple Play Integrity Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/151122264/7e8bee6a-bf22-48cb-aa02-1da0fb986cdd)

**Comment by Bbonee77** [comment]
![Screenshot_20231117-093811_Simple Play Integrity Checker~2](https://github.com/chiteroman/PlayIntegrityFix/assets/151122264/6d6a4198-3ac2-43ec-acbc-7021a235708d)
Now it's seems okay
