### ISSUE TITLE
pif 18 no longer gives device integrity

### ISSUE THREAD

**Issue by myroad94** [chiteroman/PlayIntegrityFix#493]
I use Google Pixel 5 rooted with magisk 28.1, pif 18. No other relevant module: no shamiko, no lsposed, no playintegrynext.

I put all Google apps in denylist. Cleaned wallet, services, play, multiple time, rebooted multiple time.

At first I have basic and device integrity, and after a few minutes only basic integrity. But before December this all worked!!

**Comment by myroad94** [comment]
I thought the device fingerprint was banned from Google and tried pifnext, and downloaded new fingerprint with it, but no change.

**Comment by myroad94** [comment]
Ok it seems not enabling denylist , but only zygist, make it work! Although Google wallet still does not work well

**Comment by myroad94** [comment]
@chiteroman is-it normal we need to not put google services in DenyList to have BASIC and DEVICE integrity? Until now, I always put any Google application in DenyList.

**Comment by myroad94** [comment]
Not to mention even if Google Play and Wallet says I pass security requirements, I stil cannot use Google Wallet. In another phone (same model Google Pixel 5 same OS version) not rooted, I could.

**Comment by DanGLES3** [comment]
> @chiteroman is-it normal we need to not put google services in DenyList to have BASIC and DEVICE integrity? Until now, I always put any Google application in DenyList.

Yes because Magisk normally unloads all Zygisk modules to apps in the denylist (that includes Play Integrity Fix), so having Play Services in the denylist will prevent PIF from working
