### ISSUE TITLE
RCS Broken Again

### ISSUE THREAD

**Issue by SkeleBones** [chiteroman/PlayIntegrityFix#497]
RCS seems to be not working again on the latest build.

**Comment by bradhoschar** [comment]
Pixel 9 pro XL.
RCS broken on AP4A.241205.013.C1

**Comment by TTVert** [comment]
I don't think it's the build. I 'm on AP3A.241105.007 and it started today.

**Comment by bradhoschar** [comment]
> I don't think it's the build. I 'm on AP3A.241105.007 and it started today.

Are you on T-Mobile?

**Comment by TTVert** [comment]
> > I don't think it's the build. I 'm on AP3A.241105.007 and it started today.
> 
> Are you on T-Mobile?

I am.

**Comment by SkeleBones** [comment]
I am on T-Mobile and my phone is a Nothing Phone 1.

**Comment by bradhoschar** [comment]
> I have T-Mobile and my phone is a Nothing Phone 1. Also, to be clear it started not working recently. So, it probably just started getting detected.

Oh. I guess I didn't notice it till the latest update. Nobody texts me enough 😂

**Comment by redfighter22** [comment]
RCS is broken for me as well, happened about 18hrs ago. OnePlus 6T and on T-Mobile.

**Comment by cyagl643** [comment]
RCS is broken for me too, and Im running it on OP7pro on Verizon

**Comment by seandop** [comment]
RCS is also broken for me on v18.1. OnePlus Open on Verizon.

**Comment by cyagl643** [comment]
Use the playintegrity fork everyone, that worked for me to fix RCS

**Comment by bradhoschar** [comment]
> Use the playintegrity fork everyone, that worked for me to fix RCS

On Vaca without my Linux machine. Anyway you could create a zip file for me?

**Comment by cyagl643** [comment]
Just search it on github playintegrityfix fork... Make sure enforcedenylist is on if you don't have zygisk assitant or shamiko module

**Comment by TTVert** [comment]
> Just search it on github playintegrityfix fork... Make sure enforcedenylist is on if you don't have zygisk assitant or shamiko module

I installed and it works but quick question, did I have to run action in magisk or would it have just worked?  

Dave

**Comment by cyagl643** [comment]
That's a good question, I ran it and then it worked.. but who knows I had just rebooted my phone so now sure what did the trick or not. Either case it works for you now?

**Comment by TTVert** [comment]
> That's a good question, I ran it and then it worked.. but who knows I had just rebooted my phone so now sure what did the trick or not. Either case it works for you now?

Yep, works perfect.  I sent a test RCS and also got a few texts I didn't get over the last few days.  That's a bit concerning to me as a few were from clients.  I figured if RCS didn't go through the sender would be notified and/or it would be sent via SMS>

**Comment by bradhoschar** [comment]
> > That's a good question, I ran it and then it worked.. but who knows I had just rebooted my phone so now sure what did the trick or not. Either case it works for you now?
> 
> Yep, works perfect. I sent a test RCS and also got a few texts I didn't get over the last few days. That's a bit concerning to me as a few were from clients. I figured if RCS didn't go through the sender would be notified and/or it would be sent via SMS>

Is the lates fork from Nov 17th?

**Comment by cyagl643** [comment]
Yes it is

**Comment by TTVert** [comment]
> > Use the playintegrity fork everyone, that worked for me to fix RCS
> 
> On Vaca without my Linux machine. Anyway you could create a zip file for me?

https://github.com/osm0sis/PlayIntegrityFork/releases/download/v12/PlayIntegrityFork-v12.zip

**Comment by bradhoschar** [comment]
Not working for me on Pixel 9 XL. Made sure enforcedenylist was on, Magisk 28.1. Ran action in Modules, and still prompts me to 'send as SMS'

**Comment by seandop** [comment]
> > Just search it on github playintegrityfix fork... Make sure enforcedenylist is on if you don't have zygisk assitant or shamiko module
> 
> I installed and it works but quick question, did I have to run action in magisk or would it have just worked?
> 
> Dave

You have to run the Action. I tried it without doing that (went into airplane mode, force stopped messages, wiped data and cache, etc) and it didn't work. Running the action fixed it immediately.

**Comment by TTVert** [comment]
> > > Just search it on github playintegrityfix fork... Make sure enforcedenylist is on if you don't have zygisk assitant or shamiko module
> > 
> > 
> > I installed and it works but quick question, did I have to run action in magisk or would it have just worked?
> > Dave
> 
> You have to run the Action. I tried it without doing that (went into airplane mode, force stopped messages, wiped data and cache, etc) and it didn't work. Running the action fixed it immediately.

Thanks much.  I have to assume if an update comes out we will update, reboot then run action?  I didn't see any real documentation on how to do it on their github.

**Comment by bradhoschar** [comment]
When I run the action (multiple times) it always picks a device I'm not using. On a P9Proxl, and it'll pick Pixel 6, tablet, fold. Never picks my device.

**Comment by seandop** [comment]
> When I run the action (multiple times) it always picks a device I'm not using. On a P9Proxl, and it'll pick Pixel 6, tablet, fold. Never picks my device.

Yeah, I'm pretty sure that's by design. It's generating a unique fingerprint that isn't blacklisted. The actual device doesn't matter.

**Comment by bradhoschar** [comment]
Just flashed 18.2 
Pixel 9 pro XL. 
Cleared data of messages, still stuck on 'setting up'
What did u do to get it to work?
