### ISSUE TITLE
pif 18.1 no longer gives device integrity

### ISSUE THREAD

**Issue by myroad94** [chiteroman/PlayIntegrityFix#499]
Hi again,

I have updated to PIF 18.1 just now and cannot pass DEVICE INTEGRITY.

I have:
* a Google Pixel 5 on latest OS version Android 14
* clear storage data of Play Store and Google Services
* Magisk 28.1 with PIF 18.1, but no other modules like Zygist Next, Zygist Assistant, Shamiko, Lsposed, etc.
* Zygist enabled
* Enforced DenyList disable (and tried enabled)
* Google Play and Google Services in DenyList, but also not in DenyList
* disabled usb debugging
* disabled developer mode

I don't know what to do now.

**Comment by myroad94** [comment]
I don't know if I will get better result with Magisk Kitsune? And Zygist Assistant? Is-it working for you and what setup do you have?

**Comment by myroad94** [comment]
Hmm I changed from pif to playintegrityfork, did the action of getting a new fingerprint, now google play and wallet says I am certified.

However I can still not add bank card, meaning it still detects the root.

**Comment by DanGLES3** [comment]
> Hmm I changed from pif to playintegrityfork, did the action of getting a new fingerprint, now google play and wallet says I am certified.
> 
> However I can still not add bank card, meaning it still detects the root.

Fixing integrity doesn't immediately fix Google Pay as it's still using the cached failed integrity result, it takes a day or two for it to refresh

**Comment by GUUser91** [comment]
@DanGLES3
Thanks for the info. The ElevenLabs reader app wouldn't start until I cleared the data in the Google Play Store.

**Comment by myroad94** [comment]
> > Hmm I changed from pif to playintegrityfork, did the action of getting a new fingerprint, now google play and wallet says I am certified.
> > However I can still not add bank card, meaning it still detects the root.
> 
> Fixing integrity doesn't immediately fix Google Pay as it's still using the previously cached failed integrity result, it takes a day or two for it to refresh, such cache is stored on Google Play Services (so reinstalling pay/wallet won't fix it)

I always clear data of play and services, so that I don't wait a day or two... But will retry again tomorrow Google wallet

**Comment by EbananLinfal** [comment]
Same, goolag fixed it again

**Comment by AkioSe7en** [comment]
+, Magisk 27.0, today it stopped working (Device_integrity and CTS profile false). We are waiting for the fix

**Comment by chiteroman** [comment]
Module updated: https://github.com/chiteroman/PlayIntegrityFix/releases/latest
