### ISSUE TITLE
刷了Play Integrity Fix  8.6   《Momo,BL锁未锁定》

### ISSUE THREAD

**Issue by LHC12580** [chiteroman/PlayIntegrityFix#5]
Momo BL锁  提示  未锁定。

原因是 原来的改机型模块被禁止

**Comment by chiteroman** [comment]
Momo will always report unlocked bootloader if you have Magisk except in devices with a bad TEE implementation like Asus Rog phones.

**Comment by LHC12580** [comment]
使用kernelsu也是一样 BL未锁定！&nbsp; 必须刷入改机型模块。&nbsp;&nbsp;
Play Integrity Fix 模块刷完最新版以后， Universal SafetyNet Fix会自动被禁用！ 然后Momo检测环境就会出现 BL未锁定！ 两个只能开启一个， 有没有完美方法，可以过谷歌安全验证，既能隐藏BL


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月26日(周二) 中午1:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chiteroman/PlayIntegrityFix] 刷了Play Integrity Fix  8.6   《Momo,BL锁未锁定》 (Issue #5)




 
Momo will always report unlocked bootloader if you have Magisk except in devices with a bad TEE implementation like Asus Rog phones.
