### ISSUE TITLE
Cannot pass SafetyNet check on magisk on wsa

### ISSUE THREAD

**Issue by yige-yigeren** [chiteroman/PlayIntegrityFix#5]
"basicIntegrity": false,
  "ctsProfileMatch": false,
  "evaluationType": "BASIC",

I use my build verson https://github.com/yige-yigeren/MagiskOnWSAOnlineBuild/releases/tag/WSA_2308.40000.3.0 and make sure shamiko is enable and reboot devices.
![image](https://github.com/chiteroman/PlayIntegrityFix/assets/53390868/bab867db-5908-4849-9ff7-43e23735a6f2)
magisk verson 26300, should I update to 26302?

**Comment by yige-yigeren** [comment]
Maybe WSA doesn't support CTS profile at all? But it is true that Microsoft does not intend to let us install Google Play. :(

**Comment by chiteroman** [comment]
> Maybe WSA doesn't support at all? But it is true that Microsoft does not intend to let us install Google Play. :(

Well, one user reported that this module works in Nintendo Switch running Android..

Uninstall my module and try this: https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.3

**Comment by yige-yigeren** [comment]
> > Maybe WSA doesn't support at all? But it is true that Microsoft does not intend to let us install Google Play. :(
> 
> Well, one user reported that this module works in Nintendo Switch running Android..
> 
> Uninstall my module and try this: https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.3

Thanks, but now it seems that wsa can only install version 26300, which is not compatible with this module. Maybe I should wait for the maintainer of Lsposed to update it.

Thanks for your suggestion QwQ

**Comment by mio-19** [comment]
> If BASIC verdict is ❌ it means DroidGuard is detecting root or injection...

If DroidGuard detected root or injection what could I possibly do to find out what and how did it detected root?

**Comment by chiteroman** [comment]
> If DroidGuard detected root or injection what could I possibly do to find out what and how did it detected root?

SELinux, root not hidded correctly, orange verified boot... You need to manually check, there isn't a log :(

**Comment by yige-yigeren** [comment]
> > If DroidGuard detected root or injection what could I possibly do to find out what and how did it detected root?
> 
> SELinux, root not hidded correctly, orange verified boot... You need to manually check, there isn't a log :(

I dont know why I open shamiko write list mode it still not hide :(
