### ISSUE TITLE
Device mismatched by Google

### ISSUE THREAD

**Issue by 0x11DFE** [chiteroman/PlayIntegrityFix#50]
The props that are being modified by the module breaks Google device detection and makes some Pixel features unusable.

To reproduce :
Goto [Google Device Activity](https://myaccount.google.com/device-activity) then disconnect from your device then reconnect, Your device will change it's name, In my case it either detects as Nexus or Asus.

**Comment by chiteroman** [comment]
Some do, some don't. It doesn't happen to me, but there's nothing I can do about it, sorry :(

**Comment by xantrk** [comment]
https://github.com/chiteroman/PlayIntegrityFix/issues/62#issuecomment-1817870990
I think this may be relavant from Google's wording. It seems like chrome refuses to decrypt passkeys if the device is new, i.e the missmatch :(
