### ISSUE TITLE
Help, it stopped working.

### ISSUE THREAD

**Issue by strokeros** [chiteroman/PlayIntegrityFix#500]
Yesterday it worked without a problem until I opened Google Play, I don't know what was updated, but since then it stopped working, it only passes the filter, meets_basic. My cell phone is a moto edge fusion and I use magisk.

**Comment by brylee123** [comment]
I am having the same issue. CTS profile match fail, it does pass integrity check though. I am on Android 15 on OnePlus Open rooted with Magisk.

**Comment by strokeros** [comment]
@foxi69 what can be done?

**Comment by strokeros** [comment]
> banned fingerprint boys

@foxi69 what can be done?

**Comment by DotSule** [comment]
> Yesterday it worked without a problem until I opened Google Play, I don't know what was updated, but since then it stopped working, it only passes the filter, meets_basic. My cell phone is a moto edge fusion and I use magisk.

same

**Comment by chiteroman** [comment]
Module updated: https://github.com/chiteroman/PlayIntegrityFix/releases/latest
