### ISSUE TITLE
Question: Xiaomi.eu

### ISSUE THREAD

**Issue by mgrybyk** [chiteroman/PlayIntegrityFix#54]
Hello, thank a lot for your work!

I tried to look for a reason why the play integrity checks don't work in Xiaomi.eu roms but I failed to understand the exact cause.

It seems that even though the checks fail I can still use Google Wallet but I find it somewhat fragile. It used to work for a couple of days and then stopped working.
Is it because of Xiaomi.eu rom? 

May I ask you to provide more details related to the issue?
I'd also be very glad if you can suggest some alternatives, workarounds, additional modules to use, etc.

Thank you!

**Comment by mgrybyk** [comment]
Here is a workaround I got after reading issues reported by others.
The module worked for me in combination with https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/releases

1. I installed both modules
2. Followed instructions in https://github.com/chiteroman/PlayIntegrityFix#certify-play-store-and-fix-google-wallet but also cleared gsf data.
3. Followed https://github.com/chiteroman/PlayIntegrityFix#make-fcm-push-back-to-work-after-cleared-gsf-data and rebooted device in the end. 

_Thanks a lot for the detailed instructions to the module author!_

I didn't configure the props hide module anyhow.

I'd love if the PlayIntegrityFix module would be the only one needed as far as the hide props module is deprecated and will stop working eventually.

I can use the wallet and some checks are passing for me now, see the screenshot.

**Comment by mgrybyk** [comment]
Please ignore my previous comment. It stopped working for me after clicking around for a dozen of minutes.

**Comment by SquadCraftFTW** [comment]
I replaced Magisk with kernelsu and installed zygisknext and playingtegrity fix, now instead of failing all checks it intermittently switches between failing and passing, and Google wallet doesn't warn me that the device is incompatible anymore. 

Is this the same behaviour you're experiencing?


Firmware/Device: Xiaomi.eu (stable) v14.0.20.0/Xiaomi 13 Ultra (ishtar)

**Comment by mgrybyk** [comment]
U think so, looks quite similar. The wallet doesn't work well for me. I can't delete my cards. I tried to pay with it twice earlier today. The first time it worked, the second time it didn't work.

**Comment by xVANKO** [comment]
> I replaced Magisk with kernelsu and installed zygisknext and playingtegrity fix, **now instead of failing all checks it intermittently switches between failing and passing**, and Google wallet doesn't warn me that the device is incompatible anymore.

same, some checks are passing with both basic and device integrity and some are failing

**Comment by knasiotis** [comment]
bumping. I really pray for a eu rom fix

**Comment by xVANKO** [comment]
> bumping. I really pray for a eu rom
There is no need to bump this issue. It won't be fixed on @chiteroman side. You need to wait for next MIUI stable release which won't include Xiaomi.eu fixes for Play Integrity. You will have 2 options there: install Xiaomi.eu weekly ROM (without @chiteroman PlayIntegrityFix, but included with Xiaomi.eu fixes) or Xiaomi.eu stable ROM (with @chiteroman PlayIntegrityFix installed in Magisk, bit without Xiaomi.eu fixes included in ROM).

**Comment by daboynb** [comment]
We understand that the dev can't do anything for xiaomi.eu problems but it will be cool if he can provide details to us.
Which fixes xiaomi.eu made to the rom?
Why those fixes break the module?

**Comment by chiteroman** [comment]
https://xiaomi.eu/community/threads/google-wallet-stopped-working-device-doesnt-meet-security-requirements.70444/post-705700

**Comment by mgrybyk** [comment]
@chiteroman this doesn't answer the question or provide any useful information.
It says that whatever a user want is not possible. Stable rom won't update, dev roms are outdated and not planned at the moment.

The question remains open. What should I do in order to make Xiaomi.eu rom pass the Google integrity checks?

Can you please describe what changes are required to make the module work with Xiaomi.eu rom?

Thank you

**Comment by NotCrissss** [comment]
> Can you please describe what changes are required to make the module work with Xiaomi.eu rom?

Thank you for sharing your experience, do you mean other xiaomi models (like 12s ultra) need to flash the latest stable xiaomi.eu rom and use the play integrity fix for the google wallet?

If this is the case and the google play "not certified" does not matter at well, I will try to install the stable + play integrity fix.

**Comment by kacskrz** [comment]
> @chiteroman this doesn't answer the question or provide any useful information. It says that whatever a user want is not possible. Stable rom won't update, dev roms are outdated and not planned at the moment.
> 
> The question remains open. What should I do in order to make Xiaomi.eu rom pass the Google integrity checks?
> 
> Can you please describe what changes are required to make the module work with Xiaomi.eu rom?
> 
> Thank you

As far as I see, you have Xiaomi 12 Pro with latest beta. So you have two options:
- wait few weeks for a new beta build with Android 14 and HyperOS (Xiaomi didn't release it for 12 Pro until now) which will have the newest fix by us (xiaomi.eu) or
- wait for stable rebuild which will come in few days and on which you will be able to flash PlayIntegrityFix.

Regards

**Comment by mgrybyk** [comment]
@kacskrz @NotCrissss  what I'd prefer is to get some build props from the stable eu rom or stable global rom, set them in my current eu dev rom, and just keep using the latest Android 13 build with the PlayIntegrityFix module.

Ideally, I'd like it to be automatic, but manual approach is also fine.

I'm talking about these props that you can get with getprop

```
getprop ro.build.date.utc
getprop ro.build.date
getprop ro.build.fingerprint
getprop ro.build.flavor
getprop ro.build.host
getprop ro.build.host
getprop ro.build.keys
getprop ro.build.version.incremental
getprop ro.build.version.security_patch
getprop ro.system.build.date.utc
getprop ro.system.build.date
getprop ro.system.build.fingerprint
getprop ro.system.build.version.incremental
```

For the dev rom the output is like this
```
ro.build.date.utc=1697358010
ro.build.date=Sun Oct 15 08:20:10 UTC 2023
ro.build.fingerprint=Xiaomi/zeus/zeus:13/SKQ1.220303.001/V14.0.23.10.15.DEV:user/release-keys
ro.build.flavor=missi_phone_cn-user
ro.build.host=xiaomi.eu
ro.build.keys=release-keys
ro.build.version.incremental=V14.0.23.10.15.DEV
ro.build.version.security_patch=2023-10-01
ro.system.build.date.utc=1697358010
ro.system.build.date=Sun Oct 15 08:20:10 UTC 2023
ro.system.build.fingerprint=qti/missi_phone_cn/missi:13/TKQ1.220807.001/V14.0.23.10.15.DEV:user/release-keys
ro.system.build.version.incremental=V14.0.23.10.15.DEV
```

I'm looking for the same output from the stable (eu) rom where play integrity checks are passing.

**Comment by mgrybyk** [comment]
Here is props from xiaomi.eu stable ROM 23.11.18
```
ro.build.date.utc=1696861647
ro.build.date=Mon Oct 9 14:27:27 UTC 2023
ro.build.fingerprint=Xiaomi/zeus/zeus:13/SKQ1.220303.001/V14.0.15.0.TLBCNXM:user/release-keys
ro.build.flavor=missi_phone_cn-user
ro.build.host=xiaomi.eu
ro.build.keys=release-keys
ro.build.version.incremental=V14.0.15.0.TLBCNXM
ro.build.version.security_patch=2023-10-01
ro.system.build.date.utc=1696861647
ro.system.build.date=Mon Oct 9 14:27:27 UTC 2023
ro.system.build.fingerprint=qti/missi_phone_cn/missi:13/TKQ1.220807.001/V14.0.15.0.TLBCNXM:user/release-keys
ro.system.build.version.incremental=V14.0.15.0.TLBCNXM
```

It is sufficient to mock these props in dev rom to make PlayIntegrityFix work there:
```
ro.build.fingerprint=Xiaomi/zeus/zeus:13/SKQ1.220303.001/V14.0.15.0.TLBCNXM:user/release-keys
ro.build.version.incremental=V14.0.15.0.TLBCNXM
ro.build.version.security_patch=2023-10-01
ro.system.build.fingerprint=qti/missi_phone_cn/missi:13/TKQ1.220807.001/V14.0.15.0.TLBCNXM:user/release-keys
ro.system.build.version.incremental=V14.0.15.0.TLBCNXM
```
