### ISSUE TITLE
Automatically clear the cache of the apps

### ISSUE THREAD

**Issue by oSumAtrIX** [chiteroman/PlayIntegrityFix#55]
# Issue

When Google updates their signatures, we have to update the module and clear the caches of each of the mentioned apps manually. This is tedious work that can be automated.

# Solution

Automatically clear the cache of the apps (with approval by pressing the volume buttons for example) when installing the module.

**Comment by oSumAtrIX** [comment]
How would that work? Let's say you install this module. Then you would need to install another?

**Comment by liyafe1997** [comment]
> How would that work? Let's say you install this module. Then you would need to install another?

Yes, but actually you can use `Tasker` to make it automatically. Tasker can access root shell so you can do everything on it.

**Comment by oSumAtrIX** [comment]
I don't think the complication of buying, using and setting up tasker for just this purpose is a good solution. The purpose of the module is to fix play integrity. Considering that anyone using this module, additionally with high certainty, does the manual work, this should be a module feature.

**Comment by chiteroman** [comment]
No lol

**Comment by oSumAtrIX** [comment]
Yes this is the case. I'd like to see how many people don't and I am pretty sure it's one out of 100
