### ISSUE TITLE
Reboot not necessarily required

### ISSUE THREAD

**Issue by oSumAtrIX** [chiteroman/PlayIntegrityFix#56]
# Issue

The README says to clear the caches,.optionally install the module and restart the app. If the user has installed the module but forgot to clear caches or did not do it correctly, they do not necessarily need to reboot the device.

# Solution

Reword the README so that it includes that if the module is correctly installed, but integrity is still failing, clearing the cache, as well as stopping Google Wallet in the settings and starting it again works too.

# Additional context

I assume rebooting effectively does the same. We clear the cache, so that at the next time the app starts the integrity status does not persist. Stopping the app after clearing the cache has the same effect.

**Comment by liyafe1997** [comment]
You can direct make a PR for the README

Actually, seems clear the GSF data is not necessarily and it also can cause FCM problem.

**Comment by ippocratis** [comment]
I actually had to follow the readme precisely for the wallet to work


Clear wallet cache
Clear store cache
Clear gsf data
Reboot
