### ISSUE TITLE
Suggestion: Closed Source But Code Audited By Trusted Members

### ISSUE THREAD

**Issue by adrianmmiller** [chiteroman/PlayIntegrityFix#57]
Hi, person formerly known on XDA as 73Sydney here, 

Just wanted to float a suggestion here, as i no longer XDA, but given years worth of questioning over closed source root related apps/frameworks...Magisk Alpha springs to mind as one closed source project that still garners FUD (i use it myself and dont panic), i thought id float the idea of perhaps negating mistrust with this project going closed source by suggesting it be peer reviewed by a trusted XDA member, and theres a very short list i would suggest and at the top of mine would be @osm0sis, as his knowledge of magisk etc and involvement gives him rare experience and credibility.

While in some projects, see Magisk Alpha as mentioned earlier, this isnt always possible, i personally believe where possible anything thats injecting code on a users device should be either open sourced or ideally at worst peer reviewed/audited.

Just my 5 cents....

**Comment by chiteroman** [comment]
Yes, I was thinking of doing just that. I think it's a very good idea. 👍

**Comment by osm0sis** [comment]
Might want someone who knows Java better than me, maybe someone who's been involved in a Zygisk module before, e.g. perhaps @Displax can review even if not able to maintain his own fork at the moment?

**Comment by adrianmmiller** [comment]
> Not outright declining, but.. Might (also?) want someone who knows Java better than me, maybe someone who's been involved in a Zygisk module before, e.g. perhaps @Displax can review even if not able to maintain his own fork at the moment?

sorry if i dobbed you in, but you do have "brand recognition" and are trusted :)

havent seen a lot of @Displax in a while, life is like that though, everyone gets busy and all are only volunteers

even ipdev is currently unaccounted for....
