### ISSUE TITLE
[Not an issue] Discord Server

### ISSUE THREAD

**Issue by Pheggas** [chiteroman/PlayIntegrityFix#58]
Hello. Would you mind creating a discord server for Play Integrity Fix? I think it would be really benefitial to create some private rooms for development so google employees can't clearly see what are you trying to achieve in order to bypass play integrity other way than just replacing fingerprint.

If you would be into it, i can, of couse, help you with setting up the discord server.

**Comment by chiteroman** [comment]
I prefer a Telegram channel to Discord. I'll think about it.
