### ISSUE TITLE
Module breaks Google Play Services 

### ISSUE THREAD

**Issue by pareekyashovardhan** [chiteroman/PlayIntegrityFix#6]
Hello, I'm using Nothing Phone 2. 
The fix was working for me earlier but now it breaks play services for me when I flash it. Nothing works. Google/Chrome/ Other Apps all stop working. 

They start to function again when I disable the module. 

I'm using lsposed as well but that doesn't seem to affect anything.

**Comment by pareekyashovardhan** [comment]
These are the modules that I'm currently using. 


![Screenshot_20231031-062741](https://github.com/chiteroman/PlayIntegrityFix/assets/66310623/7078a016-ee66-4c65-9923-c7e2dfb63756)
![Screenshot_20231031-062755](https://github.com/chiteroman/PlayIntegrityFix/assets/66310623/8379cae2-24fc-47c6-ad67-fc84919251b5)

**Comment by pareekyashovardhan** [comment]
> You are running v8.7, check latest version: https://github.com/chiteroman/PlayIntegrityFix/releases/latest

I had the same issue with 9.8. I switched to Magisk now from Magisk Delta and the problem is now resolved. 

However, I had to ask.. will there be anytime where we'll be able to spoof a locked bootloader?

A few features of banking apps still don't work like contact less card payments even after passing safety net.

![Screenshot_20231101-151717.png](https://github.com/chiteroman/PlayIntegrityFix/assets/66310623/8a30dcbb-df7e-4a37-833f-c2243b2f2660)

![Screenshot_20231101-151733.png](https://github.com/chiteroman/PlayIntegrityFix/assets/66310623/644072d2-d963-4fd8-92b1-d5354192a66a)

**Comment by chiteroman** [comment]
> However, I had to ask.. will there be anytime where we'll be able to spoof a locked bootloader?

You can try to use my Xposed module: https://github.com/chiteroman/BootloaderSpoofer

But very few apps checks for locked bootloader, maybe apps are detecting Zygisk.

**Comment by pareekyashovardhan** [comment]
> > However, I had to ask.. will there be anytime where we'll be able to spoof a locked bootloader?
> 
> You can try to use my Xposed module: https://github.com/chiteroman/BootloaderSpoofer
> 
> But very few apps checks for locked bootloader, maybe apps are detecting Zygisk.

Thank you for replying.

I'm using shamiko, HMA to hide root. And no app is detecting root as of now except this particular app that is working for bank transfer but doesn't allow me to add my card details to enable contact less payments using NFC.

**Comment by pareekyashovardhan** [comment]
I tried your spoofer, it doesn't work in my case.

**Comment by chiteroman** [comment]
Try using Magisk Alpha: https://t.me/s/magiskalpha
