### ISSUE TITLE
Pixel 8 Pro cannot pass CTS profile match(KernelSU)

### ISSUE THREAD

**Issue by isJasonYeh** [chiteroman/PlayIntegrityFix#60]
On the same system and device, Magisk 26.4 can work normally, but KernelSU cannot pass the verification.

![Screenshot_20231118-192223](https://github.com/chiteroman/PlayIntegrityFix/assets/107638373/0b5aab6d-5c29-4ed5-b1b9-bf71a988c9f1)
![Screenshot_20231118-192253](https://github.com/chiteroman/PlayIntegrityFix/assets/107638373/07769079-e5dc-4c44-b1cf-1b5e0152490f)
![Screenshot_20231118-192300](https://github.com/chiteroman/PlayIntegrityFix/assets/107638373/ff064c40-5036-403b-b223-7374efb78ac8)

Thank you for reading. 

Device: Google Pixel 8 Pro(husky)
System: Android 14 UD1A.231105.004
KernelSU: 11366
Play Integrity Fix: v13.0
Zygisk Next: v4.0.8.1

**Comment by chiteroman** [comment]
Send module logs, this is weird...

Do you have the bootloader locked with your own keys ?

**Comment by NiceSk1ll3r** [comment]
Latest v13 is also failing the YASNAC test for me, everything was working fine with v12.3

Mi 9T
Latest stable LineageOS 
Magisk v26.4

Sorry for stupid question, but how can I send module logs?

**Comment by isJasonYeh** [comment]
> Send module logs, this is weird...
> 
> Do you have the bootloader locked with your own keys ?

Thanks for your reply.

Do you mean the command "adb shell "logcat | grep 'PIF'""?
But when I input this command, nothing appeared (but "adb shell logcat" is worked).
Are there any other ways to confirm if the module is working properly? Should I uninstall and reinstall the module?

I'm not sure what you mean by "bootloader locked keys". I enabled OEM unlock from Developer Options, then input the command "fastboot flashing unlock" in Bootloader mode to unlock the device.

In the past, I used Magisk 26.4 (with built-in Zygisk) with Play Integrity Fix v13.0 on the same device and it worked fine.

Thanks,
Jason

**Comment by Xynonners** [comment]
Same issue, S8 Ultra with microG, used to pass safetynet but updated to 26.4/13/0.3microg and it broke

**Comment by Xynonners** [comment]
hmm, seems to be an issue with microg 0.3 or Micro Installer Revived, downgraded to 0.28/MinMicroG and all is well again.

**Comment by xzl0326** [comment]
The same problem, my Xiaomi 10Pro has no effect on ksu.

**Comment by isJasonYeh** [comment]
> hmm, seems to be an issue with microG 0.3 or Micro Installer Revived, downgraded to 0.28/MinMicroG and all is well again.

I am using a stock ROM with built-in GMS. A few days ago, there may have been an update that caused Google Pay to stop working. However, the issue was resolved after updating Play Integrity Fix to v13.0. However, after switching to KernelSU, Play Integrity Fix is not working.

**Comment by chiteroman** [comment]
Mmm seems like an issue with KernelSU and ZygiskNext 🤔

**Comment by isJasonYeh** [comment]
> Mmm seems like an issue with KernelSU and ZygiskNext 🤔

I'm sorry to hear that. It looks like I'll have to keep trying to hide Magisk.

The recently released v13.3 and v13.4 updates worked fine after installation, but they failed after reboot...🤔

**Comment by isJasonYeh** [comment]
> Maybe check latest v13.4, I updated scripts

After installing 13.4, it worked normally after the first reboot. However, it failed after clearing the cache of those 4 Google apps and rebooting.

Is there any other information I can provide you with?

**Comment by chiteroman** [comment]
Send module logs

**Comment by isJasonYeh** [comment]
> Send module logs
Thank you for your reply.

I did not pass the CTS profile match on 13.4. The command "adb shell "logcat | grep 'PIF'"" did not output any content.
I also did not pass the CTS profile match on 13.5, but log was log exist.
[PIF_13,5_log.txt](https://github.com/chiteroman/PlayIntegrityFix/files/13466444/PIF_13.5_log.txt)
After updating to 13.7, the log content still does not exist again.

Jason

**Comment by chiteroman** [comment]
> After updating to 13.7, the log content still does not exist again.

As a last resort you could try the beta version: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/PROPS

**Comment by isJasonYeh** [comment]
> Check: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8

As you mentioned before, it might be a ZygiskNext issue. I tried to install ZygiskNext v4-0.8.0 (Zygisk-on-KernelSU).

Zygisk-on-KernelSU (v4-0.8.0) passed the CTS profile match on both PIF v13.7 and v13.8, but ZygiskNext (v4-0.8.1) failed to work on both versions of PIF.

|  | Zygisk-on-KernelSU (v4-0.8.0) | Zygisk Next (v4-0.8.1) |
| --- | --- | --- |
| PIF v13.7 | pass | not work, no log |
| PIF v13.8 | pass | not work, no log |

[PIFv13.7_Zygisk-on-KernelSU_4.0.8.0_log.txt](https://github.com/chiteroman/PlayIntegrityFix/files/13470430/PIFv13.7_ZygiskNext_4.0.8.0.txt)
[PIFv13.8_ZygiskNext_4.0.8.0_log.txt](https://github.com/chiteroman/PlayIntegrityFix/files/13470432/PIFv13.8_ZygiskNext_4.0.8.0.txt)

**Comment by CanerKaraca23** [comment]
Clearing GSF is not necessary and clearing GMS not requires logging again.

**Comment by isJasonYeh** [comment]
> Clearing GSF is not necessary and clearing GMS not requires logging again.

Thank you for your information. Currently, I can use Google Pay with PIF v13.8 and Zygisk-on-KernelSU (v4-0.8.0) without clearing any data.
