### ISSUE TITLE
Error getting token from Google -Api error 

### ISSUE THREAD

**Issue by mavrovelos** [chiteroman/PlayIntegrityFix#61]
When I try the play integrity API checker on my pixel 7 pro a message shows up:"Error getting token from Google
The calling app UID (user id) does not match the one from Package Manager.
This shouldn't happen. If it does please open an issue on Github."

When I use  YASNAC the result is:"Google Play Services API error
17: APLNOT_CONNECTED"

**Comment by lunaberryyyy** [comment]
Same thing for me

**Comment by chiteroman** [comment]
Did you removed GSF data?

**Comment by mavrovelos** [comment]
How can I do this(remove gsf data)? By the way, everything works properly(wallet, banks etc) but when I perform the test with the programs mentioned above the result is what I wrote to you.

**Comment by daiaji** [comment]
I had the same glitch using mircoG.

**Comment by chiteroman** [comment]
Maybe a lot of users requesting an attestation. I don't think it's a module problem.
