### ISSUE TITLE
Passkeys don't work

### ISSUE THREAD

**Issue by Joushahissui** [chiteroman/PlayIntegrityFix#62]
After flashing the module, passkeys do not work. For example, when accessing Uber you get the error "Error to get credentials" and in other apps and pages there is also an error.

**Comment by xantrk** [comment]
![Screenshot_20231119-142512](https://github.com/chiteroman/PlayIntegrityFix/assets/1756795/b037fe15-34ba-4793-adf6-95e9457dc6b8)
I'm seeing similar in Chrome

**Comment by rushiranpise** [comment]
i think this maybe due to spoofing only gms , and other apps reading device values which mismatches
