### ISSUE TITLE
Error getting token from Google.

### ISSUE THREAD

**Issue by Jackboy001** [chiteroman/PlayIntegrityFix#63]
The error message is below. (Not very sure abt if I have to open issue in PFI or the checker)

![Screenshot_20231119-114143_Play Integrity API Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/48660972/28686de6-0aeb-450e-9483-72a920db32e8)

Thanks for your effort!

Device: Redmi Note 12 Turbo
Android Version: 13
PIF version: V13.0
Play integrity API checker version: 1.1
Security patch is September 5th.

If you need more info, please let me know!

**Comment by lunaberryyyy** [comment]
Same here on one plus 9 android 13

**Comment by DanGLES3** [comment]
> The error message is below. (Not very sure abt if I have to open issue in PFI or the checker)
> 
> ![Screenshot_20231119-114143_Play Integrity API Checker](https://user-images.githubusercontent.com/48660972/284035490-28686de6-0aeb-450e-9483-72a920db32e8.png)
> 
> Thanks for your effort!
> 
> Device: Redmi Note 12 Turbo Android Version: 13 PIF version: V13.0 Play integrity API checker version: 1.1 Security patch is September 5th.
> 
> If you need more info, please let me know!

This isn't a bug, too many people are testing Play Integrity through this app that it's exceeding the app's free API quota

It's best to test it through the Play Store

Enable play store dev options by tapping its version name in about 7 times, then a developer options menu show up in its general page and a Play Integrity option will be there

**Comment by NastyaGrifon** [comment]
Getting the same error. The other testing apps work just fine. Does seem like the free API quota is overrun

I'm using [this](https://play.google.com/store/apps/details?id=com.henrikherzig.playintegritychecker&pcampaignid=web_share) app now

**Comment by fleamour** [comment]
Error: -100: Integrity API error (-100): Unknown error processing integrity request.
Retry with an exponential backoff. Consider filing a bug if fails consistently.
 (https://developer.android.com/google/play/integrity/reference/com/google/android/play/core/integrity/model/IntegrityErrorCode.html#INTERNAL_ERROR).
