### ISSUE TITLE
Google not working after flashing

### ISSUE THREAD

**Issue by m4rc3lk00zak** [chiteroman/PlayIntegrityFix#65]
Hi after I cleared gsf data and flashed the module Google play isn't working anymore and it shows this error. Same for wallet and integrity checker. And I don't get notifications anymore from any of my apps
![Screenshot_20231119_115614_Play Integrity API Checker](https://github.com/chiteroman/PlayIntegrityFix/assets/65109395/b9245b4d-0da7-49e6-a703-f940e4cee97e)
![Screenshot_20231119_115559_Google Play Store](https://github.com/chiteroman/PlayIntegrityFix/assets/65109395/17dfda9d-5c64-4a95-9866-413d4808cc1a)

**Comment by m4rc3lk00zak** [comment]
Now anything related to Google crashes, literally my whole phone is now broken any fixes?

**Comment by ethicalresearch** [comment]
same happening to me. any update/fixes? trying to uninstall the module/entire magisk but nothing seems to work.

**Comment by chiteroman** [comment]
I have never seen this error... I have no idea.

**Comment by m4rc3lk00zak** [comment]
Tried everything and nothing worked. Literally my whole phone is broken now all of the Google aps are crashing, can't add or remove Google account

**Comment by ethicalresearch** [comment]
> I have never seen this error... I have no idea.

That's because it's not an error by your module per se. It's because you "recommend" to clean GSF data on the README.

But if you do a lil research like me on the recent hours, clearing the GSF data also clears the "gservicies.db" this database includes something very important; the GSF ID of the device. With that thing deleted you can't use any type of Google services because Google thinks you're doing a "factory reset" of the phone, and it needs to be "verified".
This information would be very important for #68  and it's also mentioned by #70 
If you had done some little research before recommending deleting the GSF data, you wouldn't have people asking about an almost unfixable issue.

**Comment by privacyguy123** [comment]
> > I have never seen this error... I have no idea.
> 
> That's because it's not an error by your module per se. It's because you "recommend" to clean GSF data on the README.
> 
> But if you do a lil research like me on the recent hours, clearing the GSF data also clears the "gservicies.db" this database includes something very important; the GSF ID of the device. With that thing deleted you can't use any type of Google services because Google thinks you're doing a "factory reset" of the phone, and it needs to be "verified". This information would be very important for #68 and it's also mentioned by #70 If you had done some little research before recommending deleting the GSF data, you wouldn't have people asking about an almost unfixable issue.

@NastyaGrifon

I wouldn't fucking never touch GSF. Imo needs removed from the Wiki. Play Services is what needs reset when playing with these modules.

**Comment by ethicalresearch** [comment]
Anyone found a solution? the stuff on the README is not working for me. 
Im guessing an new gapps flash could fix this problem... because is not even letting me add another google acc.

**Comment by m4rc3lk00zak** [comment]
> Anyone found a solution? the stuff on the README is not working for me. Im guessing an new gapps flash could fix this problem... because is not even letting me add another google acc.

I don't think there's any fix. Just flashed a new rom and obviously everything works

**Comment by chiteroman** [comment]
Seems like clearing GSF data is not a great idea, removed from README.

**Comment by ethicalresearch** [comment]
> > Anyone found a solution? the stuff on the README is not working for me. Im guessing an new gapps flash could fix this problem... because is not even letting me add another google acc.
> 
> I don't think there's any fix. Just flashed a new rom and obviously everything works

When you reflash your phone, did you use another type of gapps?
Im trying to reflash my phone too. Using nikgapps (i was using the same type before) but when im on the new ROM the google servicies keep crashing. 

"java.lang.RuntimeException: Unable to instantiate application co.g.App package com.google.android.gms: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority"

This is like a fucking joke. The gsf error carry over in the next ROM... could you tell me what ROM/gapps you're using?

**Comment by m4rc3lk00zak** [comment]
> > > Anyone found a solution? the stuff on the README is not working for me. Im guessing an new gapps flash could fix this problem... because is not even letting me add another google acc.
> > 
> > 
> > I don't think there's any fix. Just flashed a new rom and obviously everything works
> 
> When you reflash your phone, did you use another type of gapps? Im trying to reflash my phone too. Using nikgapps (i was using the same type before) but when im on the new ROM the google servicies keep crashing.
> 
> "java.lang.RuntimeException: Unable to instantiate application co.g.App package com.google.android.gms: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority"
> 
> This is like a fucking joke. The gsf error carry over in the next ROM... could you tell me what ROM/gapps you're using?

Well i actually flashed the official ROM and locked the bootloader, I'm done with rooting. Maybe try wiping like literally everything idk
