### ISSUE TITLE
wallet not fixed in samsung android 12

### ISSUE THREAD

**Issue by ahronshor** [chiteroman/PlayIntegrityFix#66]
We have a group of device support
I can confirm that we tried the solution on about 60-70 SAMSUNG devices
We tested FIP 13 and it worked on all Android 13 devices
But devices with Android 12 and below it didn't work out yet.

A test on Google Play in developer mode says that it passed successfully and the same with YASNAC,
But in Google Wallet it still says it is not supported even after deleting data in GSF GMS and Google Play.

**Comment by Masamune3210** [comment]
You have to clear the cache of wallet itself, not just Google Pay and the Framework

**Comment by ahronshor** [comment]
If you press and hold Google Wallet and go to app info, you get information about the GMS application,
so I only deleted there and it was not enough,
Now I ran it with the command
pm clear com.google.android.apps.walletnfcrel
And it succeeded
But I only tested on one device
I will check some more devices and I will update.

**Comment by Masamune3210** [comment]
On my phone, it showed up as its own app in the list once system apps were set to viewable

**Comment by ahronshor** [comment]
> On my phone, it showed up as its own app in the list once system apps were set to viewable

That was exactly my problem
And I solved it by doing the reset with the adb command
`pm clear com.google.android.apps.walletnfcrel`

**Comment by ahronshor** [comment]
And now I can confirm that it really helped us on many devices
And so I close the issue here.
