### ISSUE TITLE
Flashed to a Redmi Note 10 Pro, now none of the google apps work.

### ISSUE THREAD

**Issue by patsore** [chiteroman/PlayIntegrityFix#68]
It's about what's the described in the title. After flashing, GPS stopped working (maybe others, not sure), giving error DF-DFERH-01. Ideally add a way to delete this that would revert all changes.

**Comment by ethicalresearch** [comment]
seems to be the same issue as #65 
im having the same problems too. sim card having problems, adding/del google accounts from the device its not working. error (-12)
let's hope there's a way to revert the changes without a total wipe.

**Comment by chiteroman** [comment]
Which module version do you have? It's very strange this...

**Comment by chiteroman** [comment]
Wait, did you remove GSF data?

**Comment by AbdelrahmanMohamedDesoky** [comment]
I have stock MIUI 14.0.7 Global and same Device (Redmi Note 10 Pro) and everything works as expected.

If you want me to test something specific or provide some log/app please let me know and I would be glad to help

**Comment by Asia81** [comment]
MEETS_DEVICE_INTEGRITY
MEETS_BASIC_INTEGRITY
MEETS_STRONG_INTEGRITY

are all red on my redmi note 10 pro using this module, google wallet say my phone is not secure so I can't pay using it

**Comment by daiaji** [comment]
It seems that the fault occurred in version 13.1, and when updated to 13.3, Play can be used normally.

In fact, the fault is concentrated in Google Play version 37.5.24. If you downgrade to Google Play 33.0.16, you can still use Google play.

**Comment by chiteroman** [comment]
Check latest update
