### ISSUE TITLE
I pass all but gpay doesn't work

### ISSUE THREAD

**Issue by LiftedRocket01** [chiteroman/PlayIntegrityFix#69]
Hi, I've passed yasnac and meet device/basic integrity but google pay doesn't work it detects root or something in some way (basic error msg saying device is rooted), also I'm not sure which Google apps I shoud enforce to the deny list either, so I've been trying to trial and error but no luck. I've realised though if I enforce deny list like the the apps the module modifys (I assume) it fails everything yasnac and all. I've been trying this for 2 hrs cleared cache (and data at other times) too as well . Please help.

**Comment by tuyennn** [comment]
Use https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck&hl=en&gl=US

**Comment by LiftedRocket01** [comment]
> Use https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck&hl=en&gl=US to check

I've used integrity checker to check whether it passed or not
