### ISSUE TITLE
Clear GSF or GMS? Must be a typo

### ISSUE THREAD

**Issue by privacyguy123** [chiteroman/PlayIntegrityFix#70]
Clearing GSF fucks everything ... clearing GMS (Google Play Services) I think is the recommended procedure.

**Comment by NastyaGrifon** [comment]
Clearing GSF data is necessary for the procedure to work. Clearing GMS sometimes is reported to help with the issue, but it's not directly related or confirmed.

What  exactly  is broken after clearing GSF?

**Comment by privacyguy123** [comment]
> Clearing GSF data is necessary for the procedure to work. Clearing GMS sometimes is reported to help with the issue, but it's not directly related or confirmed.
>
I've never cleared GSF, only Play Services to get any of these mods to work and pass. I cleared nothing last update and it fixed itself on reboot it seems. 
> What exactly is broken after clearing GSF?
Everything. It changes your Google push notification token so all your apps push notifications to the wrong ID which requires extra steps to fix. It's documented on the front page of this GitHub. Why would anybody recommend that? It unnecessary breaks everything.

**Comment by PalmDevs** [comment]
> I've never cleared GSF, only Play Services to get any of these mods to work and pass. I cleared nothing last update and it fixed itself on reboot it seems.

Just because you've never had to do that troubleshooting step yourself does not mean anyone else wouldn't need to. It's put in there for a reason, and a fix is also documented. There are almost 0 downsides to this except wasting maybe like 5 minutes of your time fixing the side effects.

**Comment by privacyguy123** [comment]
> > I've never cleared GSF, only Play Services to get any of these mods to work and pass. I cleared nothing last update and it fixed itself on reboot it seems.
> 
> Just because you've never had to do that troubleshooting step yourself does not mean anyone else wouldn't need to. It's put in there for a reason, and a fix is also documented. There are almost 0 downsides to this except wasting maybe like 5 minutes of your time fixing the side effects.

I've cleared that app data and it fucked my whole phone. Search and you'll find many in similar positions. It's GMS that needs cleared.

**Comment by PalmDevs** [comment]
> I've cleared that app data and it fucked my whole phone. Search and you'll find many in similar positions. It's GMS that needs cleared. 

And there's a fix documented, you're welcome. I will not repeat the previous sentence again.

**Comment by ethicalresearch** [comment]
> > I've cleared that app data and it fucked my whole phone. Search and you'll find many in similar positions. It's GMS that needs cleared.
> 
> And there's a fix documented, you're welcome. I will not repeat the previous sentence again.

Doesn't work. The only fix is waiting a few days until google register the new ID or re-flash.

**Comment by PalmDevs** [comment]
> Doesn't work. The only fix is waiting a few days until google register the new ID or re-flash.

Have you followed all the steps including deleting `*gms.appid-no-backup` files and relaunching the apps? It worked out just fine for me.

**Comment by ethicalresearch** [comment]
> > Doesn't work. The only fix is waiting a few days until google register the new ID or re-flash.
> 
> Have you followed all the steps including deleting `*gms.appid-no-backup` files and relaunching the apps? It worked out just fine for me.

Twice. I can't add to the playstore (no network) or add another account. There's no ID on android_id in the .db also.

**Comment by Saoirse042** [comment]
> > I've cleared that app data and it fucked my whole phone. Search and you'll find many in similar positions. It's GMS that needs cleared.
> 
> And there's a fix documented, you're welcome. I will not repeat the previous sentence again.
> 
> It's clearly intentional considering the fix was also documented.

unfortunately, this didn't work for me either - but I'm reflashing the firmware regardless though so will check in if that fixes things, and deliberately _not_ wipe GSF this time. For what it's worth - I'm using a Xiaomi.eu rom, so it might be a unique issue? (I deeeeeefinitely do not expect this module to run perfectly due to, well, everything weird Xiaomi themselves have going on though.)

**Comment by chiteroman** [comment]
Don't need to clear data, just clear cache should be enough.

**Comment by ethicalresearch** [comment]
> > > I've cleared that app data and it fucked my whole phone. Search and you'll find many in similar positions. It's GMS that needs cleared.
> > 
> > 
> > And there's a fix documented, you're welcome. I will not repeat the previous sentence again.
> > It's clearly intentional considering the fix was also documented.
> 
> unfortunately, this didn't work for me either - but I'm reflashing the firmware regardless though so will check in if that fixes things, and deliberately _not_ wipe GSF this time. For what it's worth - I'm using a Xiaomi.eu rom, so it might be a unique issue? (I deeeeeefinitely do not expect this module to run perfectly due to, well, everything weird Xiaomi themselves have going on though.)

Did it fix it? Im reflashing my phone too. But the gsf error keeps carrying over to the next ROM. 

"java.lang.RuntimeException: Unable to instantiate application co.g.App package com.google.android.gms: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority" 
Im using crDroid 8.8 (android12L) > crDroid 8.10 with nikgapps CORE.

**Comment by Saoirse042** [comment]
> > > > I've cleared that app data and it fucked my whole phone. Search and you'll find many in similar positions. It's GMS that needs cleared.
> > > 
> > > 
> > > And there's a fix documented, you're welcome. I will not repeat the previous sentence again.
> > > It's clearly intentional considering the fix was also documented.
> > 
> > 
> > unfortunately, this didn't work for me either - but I'm reflashing the firmware regardless though so will check in if that fixes things, and deliberately _not_ wipe GSF this time. For what it's worth - I'm using a Xiaomi.eu rom, so it might be a unique issue? (I deeeeeefinitely do not expect this module to run perfectly due to, well, everything weird Xiaomi themselves have going on though.)
> 
> Did it fix it? Im reflashing my phone too. But the gsf error keeps carrying over to the next ROM.
> 
> "java.lang.RuntimeException: Unable to instantiate application co.g.App package com.google.android.gms: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority" Im using crDroid 8.8 (android12L) > crDroid 8.10 with nikgapps CORE.

Sorry for the delay! I had some other fun issues appear with my laptop, which took priority. I'll be re-flashing my phone this evening!
