### ISSUE TITLE
Improvement: Clear app data on install

### ISSUE THREAD

**Issue by NastyaGrifon** [chiteroman/PlayIntegrityFix#71]
The README.md states:

```
Follow this steps:

    Clear Google Wallet cache.
    Clear Google Play Store cache.
    Clear GSF (com.google.android.gsf) data and cache.
```

Can't we include the clear data function in the module itself? SafetyNetFix clears the data on install as far as I can remember

**Comment by furdiburd** [comment]
No its unnecesary. Pif work on most devices without clearing data, it just a backup solution

**Comment by VisionR1** [comment]
Bad solution, because most user don't want delete GSF (com.google.android.gsf) data, like me

**Comment by chiteroman** [comment]
Removed from README.md.
