### ISSUE TITLE
PIF 13.1

### ISSUE THREAD

**Issue by Rezazahmad** [chiteroman/PlayIntegrityFix#73]
Google Pay still not working after installing PIF 13.1. I uninstalled magisk and unrooted the device but the problem persists. Maybe that's because of the unlocked bootloader? 
Android 13 & Poco X3 NFC

**Comment by chiteroman** [comment]
If your ROM doesn't include the fix you can't pass Device verdict so Google Wallet won't work. With unlocked bootloader you must install Magisk, enable Zygisk and install my module. Then follow the tutorial in the README.md.
