### ISSUE TITLE
Magisk delta incompatibility

### ISSUE THREAD

**Issue by ShiroBlank** [chiteroman/PlayIntegrityFix#74]
As the title says, all Google services refuse to work when installing with magisk delta but the module works as intended with normal magisk, not sure if this is considered out of scope but a fix would be super nice.

**Comment by VisionR1** [comment]
> As the title says, all Google services refuse to work when installing with magisk delta but the module works as intended with normal magisk, not sure if this is considered out of scope but a fix would be super nice.

I have Magisk Delta v25.2 with this module v13 and works. What Magisk Delta and module version you have ?

**Comment by chiteroman** [comment]
In my device is working fine with latest stable Magisk Delta and Magisk Alpha, check your setup.

**Comment by jason-stream** [comment]
Fine here on Magisk Delta and KSU, only had to clear Play Services.
