### ISSUE TITLE
Bootloop after downgrade

### ISSUE THREAD

**Issue by sallygal1** [chiteroman/PlayIntegrityFix#75]
I had `v13.1` before, flashed `v13.2`, accidentily flashed `v13.1` again, now the device is stuck in bootloop. Can still access recovery but LineageOS won't boot.

Any ideas?

**Comment by chiteroman** [comment]
Go to /data/adb/modules and remove "playintegrityfix" folder 👍

**Comment by rushiranpise** [comment]
> I had `v13.1` before, flashed `v13.2`, accidentily flashed `v13.1` again, now the device is stuck in bootloop. Can still access recovery but LineageOS won't boot.
> 
> Any ideas?

1. if you dont have custom recovery which supports data mount,
flash stock boot img of phone which will disable the root method magisk/ksu

2. you can try to enable safe mode in magisk/ksu which disables all the modules|

for magisk - long press vol down button for more than 3 secs after the boot logo
for ksu - press volume down button more than 3 times  after the boot logo

**Comment by patrickdrd** [comment]
strange, I downgraded as well because of lsposed problems (I'll open my issue) and
I didn't face any problems

**Comment by sallygal1** [comment]
Hello @chiteroman @rushiranpise @patrickdrd 

Thank you for your answers. Problem is, I have TWRP but it doesn't support decrypting the data partition. So while I can see the folder /data/adb I cannot remove specific modules folder. Is it safe do just delete the whole adb content?

I have tried everything to disable all modules, even create .disable_magisk files etc. Also tried flashing boot.img from my original LineageOS img but still not booting...

Any other ideas?

**Comment by rushiranpise** [comment]
> Hello @chiteroman @rushiranpise @patrickdrd
> 
> Thank you for your answers. Problem is, I have TWRP but it doesn't support decrypting the data partition. So while I can see the folder /data/adb I cannot remove specific modules folder. Is it safe do just delete the whole adb content?
> 
> I have tried everything to disable all modules, even create .disable_magisk files etc. Also tried flashing boot.img from my original LineageOS img but still not booting...
> 
> Any other ideas?

you can try, it will remove all modules and magisk/ksu settings

if still not then format is the only option i think

**Comment by chiteroman** [comment]
> I have TWRP but it doesn't support decrypting the data partition.

Check if your device supports OrangeFox and install it instead TWRP. If not, you can just flash original boot.img
