### ISSUE TITLE
Issue with 8.7 & 8.6

### ISSUE THREAD

**Issue by CiLiBi18** [chiteroman/PlayIntegrityFix#8]
Hi,

I wanted to report an issue with those 2 la test versions.
I just made a fresh and complete install for my OnePlus 11 (EU-CPH2449) with Magisk Delta & Zygisk.
Before format I used to have safetynet fix 2.40 and now it doesn't work anymore.
So I tried the mod, no luck, finally I found this module and I think it has the potential to be the next fully working and useful module to bypass safetynet.

Anyway, I tried the 8.7 and it failed, then I tried the 8.6 and they both (the other modules as well) had this same result : Chrome freeze and crash (same for some other GApps I tested)..

Here some device info :
OnePlus 11 CPH2449
Android 13 (OxygenOS 13.1)
CPH2449_13.1.0.591(EX01)
Google Play Services : 23.36.14 (190408-567131450) (233614045)
Magisk Delta 26.1 with Zygisk enabled

Hope it will be helpful for you and thank you for the good hard work.

Have a great day.

**Comment by chiteroman** [comment]
Displax mod gives you the same problems?

**Comment by CiLiBi18** [comment]
Yes, same result with mods 1.3 and 2.0

**Comment by chiteroman** [comment]
Try with latest official Magisk: https://github.com/topjohnwu/Magisk/releases/latest
