### ISSUE TITLE
Don't passing

### ISSUE THREAD

**Issue by danehcan** [chiteroman/PlayIntegrityFix#80]
![Screenshot_20231122-082722](https://github.com/chiteroman/PlayIntegrityFix/assets/73938845/b79f9ec6-2740-4df2-aa38-e4a964cd0d18)
Magisk + module safetynet pass 
phone: moto g30 caprip

**Comment by norz3n** [comment]
Tell me, have you enabled the Zygisk in the Magisk settings?

**Comment by Zarpyk** [comment]
Same to me
![Screenshot_2023-11-22-15-00-16-492_leygjznnhq xewlv](https://github.com/chiteroman/PlayIntegrityFix/assets/30746531/92ab04df-deb0-4082-8a4b-272da550e9ef)
![Screenshot_2023-11-22-15-09-20-078_leygjznnhq xewlv](https://github.com/chiteroman/PlayIntegrityFix/assets/30746531/02085003-6581-4c2f-8bee-dd7ae5123065)
![Screenshot_2023-11-22-15-08-22-434_gr nikolasspyr integritycheck](https://github.com/chiteroman/PlayIntegrityFix/assets/30746531/1c1bfec3-797b-4dc4-a0a4-523180a9d9c4)
![Screenshot_2023-11-22-15-11-04-548_leygjznnhq xewlv](https://github.com/chiteroman/PlayIntegrityFix/assets/30746531/73740d53-aa75-4e8e-beba-5c703d934ca6)

**Comment by chiteroman** [comment]
Which rom

**Comment by Zarpyk** [comment]
Xiaomi.eu 14.0.5.0.SJKCNXM Poco F2

**Comment by Arbitrate3280** [comment]
Same on xiaomi.eu poco f5 V14.0.25.0.TMRCNXM

**Comment by crok** [comment]
And which build? The second rebuild from 2023-11-19? Did you update the stable ROM you are using to the latest, which doesn't include any fix and thus not interfering with the operation of PIF?

**Comment by chiteroman** [comment]
Check the latest update from Xiaomi.eu

**Comment by nocturn9x** [comment]
Yeah, uh, this module doesn't work at all. SN passes but PI doesn't.

**Comment by Zarpyk** [comment]
After updating to the latest update it seem work now

I follow this: https://xiaomi.eu/community/threads/how-to-flash-magisk-and-play-integrity-fix-on-xiaomi-eu.70553/

But it keep failing on the last one, but I tested with Google Wallet and McDonald's app and it seems work (I haven't used it yet, but the error messages don't appear)
![Imagen de WhatsApp 2023-11-23 a las 01 28 03_c2a3473a](https://github.com/chiteroman/PlayIntegrityFix/assets/30746531/cdac6ad1-3563-47c1-b36e-469210cc258f)

**Comment by danehcan** [comment]
> Tell me, have you enabled the Zygisk in the Magisk settings?

Yes, the most ridicules think is : I passed the play integrity but few days ago pass was broke

**Comment by danehcan** [comment]
> Which rom

motorola g30 official rom moded by magisk app.

**Comment by chiteroman** [comment]
Latest should work
