### ISSUE TITLE
lsposed problems after updating to 13.2

### ISSUE THREAD

**Issue by patrickdrd** [chiteroman/PlayIntegrityFix#81]
as I said on telegram group, 
I faced problems with lsposed and version 13.2:
first of all I noticed that my modules weren't running,
I installed lsposed apk to see what happens and lsposed showed as not installed,
I downloaded its zip and flashed it through magisk and restarted,
still nothing, 
so this version wasn't allowing lsposed to install / show as installed on my case, no idea why,
I flashed version 13 of this module and lspoed was working again

**Comment by chiteroman** [comment]
Check latest

**Comment by patrickdrd** [comment]
much, much worse now, all my apps crashing, wow!

**Comment by chiteroman** [comment]
> much, much worse now, all my apps crashing, wow!

Which rom, Android version, Magisk.

Nobody reported me something like this before... Very weird.

**Comment by patrickdrd** [comment]
just a moment mr , my phone has become unusable, how do I fix it now? 
how do  I remove your module?

**Comment by chiteroman** [comment]
> just a moment mr , my phone has become unusable, how do I fix it now? how do I remove your module?

From custom recovery you can remove the module folder.

**Comment by patrickdrd** [comment]
which folder? data/app and?

**Comment by chiteroman** [comment]
> which folder? data/app and?

From recovery you can remove /data/adb/modules/playintegrityfix folder.

**Comment by patrickdrd** [comment]
ok, done, back to your question

**Comment by patrickdrd** [comment]
> > much, much worse now, all my apps crashing, wow!
> 
> Which rom, Android version, Magisk.
> 
redmi note 9 pro, android version 10, magisk 25.2,
rom miui global 11.0.6

**Comment by patrickdrd** [comment]
I'm not a fan of such critical updates because I've seen they create issues,
that's why I don't update lsposed modules either or lsposed itself (I'm using 1.8.5 I think),
anyway, my older phone broke, so I got myself a new one to use outside for shopping etc, unrooted this time,
rooting etc takes so much time, which I wouldn't want to afford this period of my life,
I prefer to spend it elsewhere,
so nevermind me, using google pay/wallet in this device would be very rare, if any

**Comment by CanerKaraca23** [comment]
> I'm not a fan of such critical updates because I've seen they create issues, that's why I don't update lsposed modules either or lsposed itself (I'm using 1.8.5 I think), anyway, my older phone broke, so I got myself a new one to use outside for shopping etc, unrooted this time, rooting etc takes so much time, which I wouldn't want to afford this period of my life, I prefer to spend it elsewhere, so nevermind me, using google pay/wallet in this device would be very rare, if any

You're using obsolete version of LSPosed and Magisk but trying to update Play Integrity Fix module. Always use latest MIUI, Magisk, LSPosed and modules. No problem with me.

**Comment by patrickdrd** [comment]
trust me , everything is working absolutely fine,
of course it's your fault, you released a module that created a mess on my device, and two times, not me, come on

**Comment by chiteroman** [comment]
https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.5

Can you check this version?

**Comment by patrickdrd** [comment]
great, this worked!!

**Comment by patrickdrd** [comment]
it worked after restart from magisk but no on the next reboot, same as before

**Comment by NBruderman** [comment]
> it worked after restart from magisk but no on the next reboot, same as before

Why don't you use an older module, that fits with your older system, magisk and lsposed versions? When you use deprecated versions, don't expect everything to work. You can try the safetynet fix module by kdrag0n, or its modded version by displax. It's an older module, and the older versions might work for you. This is a new module, so for it to work you should use compatible apps.

**Comment by patrickdrd** [comment]
no. that doesn't work,
that's what I was using but wallet broke for me as for everyone out there when google starred using play integrity

**Comment by CanerKaraca23** [comment]
Bro just try updating Magisk and LSPosed.

**Comment by nakcont** [comment]
> as I said on telegram group,
> I faced problems with lsposed and version 13.2:
> first of all I noticed that my modules weren't running,
> I installed lsposed apk to see what happens and lsposed showed as not installed,
> I downloaded its zip and flashed it through magisk and restarted,
> still nothing,
> so this version wasn't allowing lsposed to install / show as installed on my case, no idea why,
> I flashed version 13 of this module and lspoed was working again

same issue, lsposed not working when installl PlayIntegrityFix v13.5.
LSPOSED 192
KERNELSU 0.7.1
ZYGISK NEXT 4081

**Comment by nakcont** [comment]
> > as I said on telegram group,
> > I faced problems with lsposed and version 13.2:
> > first of all I noticed that my modules weren't running,
> > I installed lsposed apk to see what happens and lsposed showed as not installed,
> > I downloaded its zip and flashed it through magisk and restarted,
> > still nothing,
> > so this version wasn't allowing lsposed to install / show as installed on my case, no idea why,
> > I flashed version 13 of this module and lspoed was working again
> 
> same issue, lsposed not working when installl PlayIntegrityFix v13.5. LSPOSED 192 KERNELSU 0.7.1 ZYGISK NEXT 4081
> 
> Test on Pixel 6, Android 13.

I have successfully fixed it,  i'm push again pif.prop into /data/adb/modules/playintegrityfix and worked. Version 135  /data/adb/modules/playintegrityfix/pif.prop move to /data/adb/pif.prop.old.
 "Modules use default props for attestation" => cause error lsposed.

**Comment by thanasistrisp** [comment]
> > as I said on telegram group,
> > I faced problems with lsposed and version 13.2:
> > first of all I noticed that my modules weren't running,
> > I installed lsposed apk to see what happens and lsposed showed as not installed,
> > I downloaded its zip and flashed it through magisk and restarted,
> > still nothing,
> > so this version wasn't allowing lsposed to install / show as installed on my case, no idea why,
> > I flashed version 13 of this module and lspoed was working again
> 
> same issue, lsposed not working when installl PlayIntegrityFix v13.5. LSPOSED 192 KERNELSU 0.7.1 ZYGISK NEXT 4081
> 
> Test on Pixel 6, Android 13.

Same for me, tested on lineageos 20. However, v13.4 works.

**Comment by omer-1080314** [comment]
Same for me tested on Realme UI 4.0, Zygisk Next 4081 KSU 0.7.1

**Comment by patrickdrd** [comment]
13.6 beta worked for me (without updating lsposed or magisk)

**Comment by omer-1080314** [comment]
> 13.6 beta worked for me (without updating lsposed or magisk)

Same for me

**Comment by andrea-musci** [comment]
Also for me lsposed stopped working with version 13.4 and 13.6. I'm on standard magisk 26.4  and latest lsposed. Going back to 13 as for now.

**Comment by andrea-musci** [comment]
Seems to work now in 13.6. I'll test it further

**Comment by chiteroman** [comment]
Check: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8

**Comment by maxrave-dev** [comment]
Conflict with Zygisk Next in KSU, cause zygote to crash. On latest PIF version
