### ISSUE TITLE
Chrome privileged process crash g965f version > v13.0

### ISSUE THREAD

**Issue by 7thbitch** [chiteroman/PlayIntegrityFix#83]
Google chrome started to crash after update to version newer than 13.3, even 13.5 beta. After downgrade, no crashes on samsung g965f android 10.

**Comment by 7thbitch** [comment]
After checking all other versions, the last working is 13.3!

**Comment by 7thbitch** [comment]
After checking all other versions, the last working is 13.3!

**Comment by chiteroman** [comment]
Check latest version.
