### ISSUE TITLE
thanks for nothing 

### ISSUE THREAD

**Issue by Hamood111** [chiteroman/PlayIntegrityFix#84]
it's me hamood the one who got ban from xda for no reason maybe because I talked about Zionist maybe it's to much I just mention that as example Idn who reported me I hope u have no relation with it cuz I respect u or may I will say I was respect u before but not anymore it's dependent on your answer if you answered in the first place anyway it should be warning before ban now I can see the truth what a disgusting world we are living in free Palestine go ahead ban me from GitHub or whatever I don't care and I don't wanna know or deal with Zionist killed kids people anymore I can live without root shit but I can't live with disgusting people shame on you technology developers community shit

**Comment by mgrybyk** [comment]
@Hamood111 people might listen to you eventually if you learn to communicate. It's a long long way though.

This is not a proper place to spread the propaganda deasese. 
It's not a normal to beg for a reaction in a pity way pretending to be a victim either. 
This is disgusting. Shame is that you don't want to realize or accept it.

I wonder what kind of creatures feed on negative emotions? It's not a good choice to be a puppet of such.

I wish you all the best.
