### ISSUE TITLE
13.5 failing Device Integrity & CTS Profile Match

### ISSUE THREAD

**Issue by Jon8RFC** [chiteroman/PlayIntegrityFix#85]
Pixel 8 Pro
Magisk 26400
System version UD1A.231105.004, Nov 2023
Play Store version 38.4.19-29 [O] [PR] 582389963
Play Services version 23.44.14 (190408-580326705)

**13.4 and prior versions work properly.**
Is there anything else helpful to share and how would I get that data?

Thanks for this module--it's great!

**Comment by nakcont** [comment]
SAME isuue, 13.4 worked for me.

**Comment by Bonoboo** [comment]
Will add a bit uncertainty. For me 13.4 caused failing integrity, reverting to 13.3 fixed it. After update to 13.5 all fine.

**Comment by Jon8RFC** [comment]
Would you all mind adding your phone, magisk, and oa version to your replies for Chiteroman to have as helpful data, please? 

The play store and services versions may not matter much, in this case. But if you can share that too, that'd be good.
Settings>apps>see all apps
Play store
Play services

Scroll to the bottom and then you can use the "switch apps gesture"  (unsure of how) or the square on the 3-button navigation, then use the "select" button below that screen to get the version without typing.
Alternatively, screenshot, open in photos, use Google lense to copy the version.

**Comment by olimondo** [comment]
Same for me, all versions up to 13.4 worked great, now failing Basic Int Check with 13.5

Magisk 26.4
OnePlus 7 Pro
Lineage OS 20

**Comment by Bonoboo** [comment]
@Jon8RFC, sorry, my fault.

- Xiaomi Redmi Note 10 Pro on Android 11 (LineageOS 18.1)
- Magisk: 26.3
- Play Store: 38.4.19-29
- Play Services: 23.44.14

And now I recalled, integrity was ok, but GPay broken, even after another reboot.
_______________________________
Totally not related to issue, just to post somewhere.
It's possible to automatically detect when GPay refuses to work. As we know, it can happen any time due server-changes by Google.
I use Tasker app to check it at every screen on. Should be installed `sqilte3` binary (e.g. from [here](https://github.com/EXALAB/sqlite3-android/tree/master/binary)).

Run this shell "code":
`sqlite3 /data/data/com.google.android.gms/databases/android_pay "SELECT fails_attestation FROM Wallets"`
If it returns at least one "1", then GPay broken due root detection. I've set Tasker to post notification in this case.

BTW there is another (seems less realible) indicator: line `<"last_attestation_result" value="false">` in file
`/data/data/com.google.android.gms/shared_prefs/com.google.android.gms.tapandpay.service.TapAndPayServiceStorage.xml`

**Comment by voklav** [comment]
I use the app [TB Checker.](https://play.google.com/store/apps/details?id=krypton.tbsafetychecker&pcampaignid=web_share)
Basic Integrity: pass
Device Integrity: pass
Strong Integrity: Fail

Is there any way to pass Strong Integrity? :)

**Comment by Klusio19** [comment]
> I use the app [TB Checker.](https://play.google.com/store/apps/details?id=krypton.tbsafetychecker&pcampaignid=web_share)
> Basic Integrity: pass
> Device Integrity: pass
> Strong Integrity: Fail
> 
> Is there any way to pass Strong Integrity? :) 

It's literally shown in the FAQ that you can't pass strong integrity. Is it really THAT hard to read?

**Comment by Jon8RFC** [comment]
Device Integrity & CTS Profile Match fixed for me in 13.6-beta:
https://github.com/chiteroman/PlayIntegrityFix/releases

**Comment by olimondo** [comment]
13.6 beta fixed for me also, thanks for the work!!

**Comment by AnritoKun** [comment]
13.5 LSPosed does not work correctly. 13.4 Works better, 13.6 I haven't tested.

**Comment by Jon8RFC** [comment]
Just to share, the new, non-beta 13.6 release also works fine, as does 13.7.
