### ISSUE TITLE
Some apps lose all network access

### ISSUE THREAD

**Issue by gilcu3** [chiteroman/PlayIntegrityFix#87]
Device: Oneplus 7T
Lineage OS: 20 Official
Magisk: 26.4 Official
Magisk Modules:
Shamiko: 0.7.4
Zygisk - LSPosed: 1.9.2
This module: 13.7

I am currently passing device integrity, but a very weird issue is that some apps lose network access after reboot. If I uninstall and install them again, they work again as normal. There is one step that I have not done, which is erasing GSM data, because I dont want to lose the Android Wear config etc.
Do you know why would this happen, and if there is any fix that can be done through adb or root terminal? Let me know if you need any log in particular, I dont know exactly which would be useful in this case.

PS: Even more weird behavior, if I reboot the device a second time, some apps recover networks, some others lose it, and play integrity may or may not work anymore. Uninstalling the module and rebooting fixes everything except that the device cannot pass basic play integrity nor safetynet, as expected (?).

**Comment by NBruderman** [comment]
Did you try older versions as well? Did you try to remove the module and see if the problem is gone?
This module in general has nothing to do with internet access, and shouldn't have anything to do with it.

**Comment by bengalih** [comment]
I would do some more controlled testing to separate reboots from PIF being loaded.  If you are removing PIF and rebooting, hard to tell what solved it.

Are you 100% sure that reboots alone don't fix it?  Can you remove PIF, reboot, work no problem for a day and then when the only thing changed is PIF, things break in short order?

**Comment by NBruderman** [comment]
The latest version (1.37) doesn't have a pif file or custom props in it...

________________________________

**Comment by chiteroman** [comment]
Try: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8

**Comment by gilcu3** [comment]
> Try: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8

After flashing and reboot, I am passing integrity check and all apps have network access, thank you!
I will test for a day and close this issue if I find no network loss in the meantime.

**Comment by gilcu3** [comment]
I can safely close this. After a day of everything working I rebooted and everything is still working. Furthermore yesterday even gpay began working as well!
