### ISSUE TITLE
Integrity check only passes every 2x request

### ISSUE THREAD

**Issue by marrobHD** [chiteroman/PlayIntegrityFix#89]
Hi,

I've installed the patch. After a while, the integrity check now passes sometimes.
The first request always fails, the second passes, the third fails...

The result of this is that Google Pay does not work every time.

![Screenshot_2023-11-26-16-24-02-944_com.henrikherzig.playintegritychecker.jpg](https://github.com/chiteroman/PlayIntegrityFix/assets/29308361/8cfef004-d075-443b-b895-3187cee9b57d)

![Screenshot_2023-11-26-16-24-05-499_com.henrikherzig.playintegritychecker.jpg](https://github.com/chiteroman/PlayIntegrityFix/assets/29308361/1cd17461-0a87-4262-b17c-dc1711a7b5d0)

**Comment by chiteroman** [comment]
Try this: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8

**Comment by Manueh333** [comment]
I tried 13.8 and it passes every 2x request too

**Comment by marrobHD** [comment]
> Try this: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8

I can confirm that the issue persists after upgrading to this version.

**Comment by pannal** [comment]
Can't confirm with 13.8 on A13 and Kitsune Mask.

**Comment by if0s** [comment]
I've had the same behavior as @marrobHD (since v13 to v13.7).
Today tried to update my firmware to latest version (I use `xiaomi.eu`) clear all app data (not only cache) in `Google Wallet`, `Google Play Services`, `Google Play Store` and `Google Services Framework`, then reboot and add cards to `Google Wallet` again, seems no issue anymore, SPIC response successfully each time

**Comment by osm0sis** [comment]
Can't confirm this either. Every request works great on my Pixel 8 Pro on latest 13.8 beta.

**Comment by recreationx** [comment]
Behaviour is replicable for me on v13.8, using `xiaomi.eu`. Issue persisted even after clearing Google Wallet, Google Play Services, Google Play Store and GSF following what @if0s mentioned.

**Comment by marrobHD** [comment]
> Check latest: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8
> 
> Seems like the problem was resetprop utility.

Issue is still there. 
Play integrity info:
`Labels: []
Build fingerprint: Xiaomi/star/star:13/RKQ1.211001.001/V14.0.23.9.18.DEV:user/release-keys
Brand: Xiaomi
Device: star
Model: M2102K1G
TestId: dGVzdGluZy0yM2NjMDgzZC1jNmMwLTRmNzMtODJkNS0xYmYzNDkyOTM3NDc`=

**Comment by mikal** [comment]
> Behaviour is replicable for me on v13.8, using `xiaomi.eu`. Issue persisted even after clearing Google Wallet, Google Play Services, Google Play Store and GSF following what @if0s mentioned.

I have the same issue since yesterday. My phone is Xiaomi 13 with Eu Rom as the below.
![Screenshot_2023-11-28-20-08-21-720_rikka safetynetchecker](https://github.com/chiteroman/PlayIntegrityFix/assets/59812419/643dedf6-0d34-4b7c-91f0-916ee25e6a88)
.

**Comment by Rona-chan54** [comment]
Same problem here on a mondrian (POCO F5 Pro) running xiaomi.eu hyperOS.
Ratio of success is much lower though, maybe 1 success for 10 tries.

**Comment by if0s** [comment]
So, the problem seems to be with the `xiaomi.eu` ROM.
My issue was resolved after upgrading to the latest [STABLE](https://xiaomi.eu/community/threads/miui-14-stable-release.67685/) version, which was rebuilt and reuploaded on 18.11.2023 (followed by installing Magisk, PlayIntegrityFix, and clearing app data).
This last build does not have an integrated Google Pay fix, and it works for me. However, the previous version (built)  caused an issue, so the reason might be due to some conflicts between the built-in fix and this plugin, and solution is to upgrade to latest build (after 18.11.2023) ?
P.S. My device is a POCO F3 (Redmi K40).

**Comment by jason-stream** [comment]
13.9 is out

**Comment by mikal** [comment]
> > Behaviour is replicable for me on v13.8, using `xiaomi.eu`. Issue persisted even after clearing Google Wallet, Google Play Services, Google Play Store and GSF following what @if0s mentioned.
> 
> I have the same issue since yesterday. My phone is Xiaomi 13 with Eu Rom as the below. ![Screenshot_2023-11-28-20-08-21-720_rikka safetynetchecker](https://private-user-images.githubusercontent.com/59812419/286244532-643dedf6-0d34-4b7c-91f0-916ee25e6a88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzMxNjIsIm5iZiI6MTcwMTIzMjg2MiwicGF0aCI6Ii81OTgxMjQxOS8yODYyNDQ1MzItNjQzZGVkZjYtMGQzNC00YjdjLTkxZjAtOTE2ZWUyNWU2YTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA0NDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzhjZjg2Y2E3Yzk5ZjMzYTQzNTBkNTAzY2Y3OTE1Y2Q0NDJhYjRlZWI3MDMyOWE0ZjQ2NTc2ZWZhYjkyMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5afHKeSnRdsyzGAh7oQXn1sGb-_nlVMUKGVDkoYlRg) .

My issue has been resolved by v13.9 + Magisk Alpha + Shamiko 189 blacklist mode after cleaning up cache and re-instaling those affected Apps. 
Thank you so much, the dev team!
