### ISSUE TITLE
Can you please publish the full source code?

### ISSUE THREAD

**Issue by valievkarim** [chiteroman/PlayIntegrityFix#9]
Hello and thank you for releasing and supporting such a good module!

Being security-paranoid, i'm afraid of using closed-source root modules.
Can you please publish all the rest of the source code and build scripts?
Especially sources for the java part (classes.dex)
And also module building parts like post-fs-data.sh etc
I think it would be useful for supporting the android root ecosystem security

Thank you again!

**Comment by chiteroman** [comment]
You can see Java code loading classes.dex in Jadx, and scripts just need to open .zip and edit it.

I will publish everything if I can fix the new Google update.
