### ISSUE TITLE
I have tried 13.8 and 13.7 but none could make the app of McDonald's to work

### ISSUE THREAD

**Issue by Manueh333** [chiteroman/PlayIntegrityFix#90]
As I say in the tittle I have some problems with McDonald's App, I use a Custom ROM (xiaomi.eu) and It has worked until last week or so.
So I tried to install Magisk and this PlayIntegrityFix. But It doesn't fix the McDonald's App could anyone help me pls. Thank you.

**Comment by chiteroman** [comment]
Do you have latest xiaomi.eu ROM version? This module only works in latest stable builds.

**Comment by Manueh333** [comment]
Aaaaaa, only in STABLE right? I have weekly ones. Okay thank you.
