### ISSUE TITLE
CTS profile match isn't passing

### ISSUE THREAD

**Issue by CanerKaraca23** [chiteroman/PlayIntegrityFix#94]
After updating to 13.8 from 13.7, CTS profile isn't passing. I cleared caches of Play store and Play services but still same. I have Xiaomi EU ROM with the latest stable build. Play store says device isn't certified. I wan't to try downgrade to 13.7 back but in all old versions changelog, it says unstable, use at your own risk, so i didn't tried to downgrade.

![Screenshot_2023-11-27-17-40-34-749_rikka safetynetchecker](https://github.com/chiteroman/PlayIntegrityFix/assets/37447503/402044c1-b868-4bc7-925b-8a1046bc5aad)

**Comment by CanerKaraca23** [comment]
> Download again: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v13.8 and try.

After reinstallation, it worked thanks!

**Comment by CanerKaraca23** [comment]
Update: After reinstalling, YASNAC said passed but in Play Store, it still says device is not certified. I cleared data of Play Store, cleared cache of GSF and GMS and rebooted phone and then device certification section is gone on Play Store about settings. What should i do know? Should i clear data again?

**Comment by chiteroman** [comment]
Clear GMS and Play Store data and cache.

Don't touch GSF.

**Comment by CanerKaraca23** [comment]
> Clear GMS and Play Store data and cache.
> 
> Don't touch GSF.

Worked, thanks!
