### ISSUE TITLE
Testing suggestion

### ISSUE THREAD

**Issue by adrianmmiller** [chiteroman/PlayIntegrityFix#95]
Am i the only one concerned that with every release theres a bunch of people spamming Google with tests, and thats even factoring in they are doing the sane thing and using Google Play Store Developer Options to do it to telegraph what we're up to less obviously), with the same default fingerprint (a lot of the time) and that this behaviour risks perhaps them reacting in a more harsh way and more quickly, than if perhaps you signed up a dozen or so people with different devices, and got them to test any new release for a few days, before releasing it generally.

It might also reign in the abject chaos the TG group has become....

Just me?

**Comment by chiteroman** [comment]
1. I cannot prohibit anyone from making an Play Integrity attestation.
2. The Telegram group is better now, I removed the permissions to send unnecessary things and set strict rules.
